### ISSUE TITLE
蜂箱生成

### ISSUE THREAD

**Issue by senlinhuaji** [LeavesMC/Leaves#106]
### 服务端版本 LeavesMC Version

This server is running Leaves version git-Leaves-"bce5870" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: bce5870) You are 23 version(s) behind Download the new version at: https://leavesmc.top/downloads/leaves Previous version: git-Kaiiju-"794ce3b" (MC: 1.20.1)

### 预期的行为 Expected behavior

单人模式1.20.1的存档下，蜂箱树场的蜂箱只会刷新在一边

### 观测到的实际行为 Observed/Actual behavior

服务器中，蜂箱树场的蜂箱会在两边都刷新，导致树场损坏

### 复现步骤 Steps/models to reproduce

![9V`5SX~)2YHH~XVEI$0KQ](https://github.com/LeavesMC/Leaves/assets/99373997/98c1987c-ae8a-4f3a-abd0-cf141728e429)
![25{) _}8IYAN7}OP62TFM_D](https://github.com/LeavesMC/Leaves/assets/99373997/5be69aaa-6693-4c09-91a8-e8cd3430f0b8)
图一为错误位置，图二为正确位置。在单人存档中只会出现图二情况，而在服务器中两种情况会随机出现

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (3):Bukkit Plugins:Geyser-Spigot, PlayerTitle, skinsRestorer
已启用2个数据包: [vanilla 内置)],[file/ bukkit 世界)]已无更多可用的数据包

**Comment by s-yh-china** [comment]
需要提供更多信息和复现 比如蜂巢农场的具体架构
目前在最新版本下我不能复现此问题

**Comment by senlinhuaji** [comment]
> 需要提供更多信息和复现 比如蜂巢农场的具体架构 目前在最新版本下我不能复现此问题

谢谢,我更新一下版本试试

**Comment by s-yh-china** [comment]
无法证明此问题存在 暂时关闭
