### ISSUE TITLE
漏斗矿车在玩家远离时不工作

### ISSUE THREAD

**Issue by little-boluo** [LeavesMC/Leaves#108]
### 服务端版本 LeavesMC Version

git-leaves-"710267d"(MC:1.20.1)

### 预期的行为 Expected behavior

漏斗矿车能在任何加载的区块中工作（吸取物品等），无需玩家在附近挂机，比如在被地狱门加载器加载的区块吸取掉落物

### 观测到的实际行为 Observed/Actual behavior

尽管区块被加载，漏斗矿车保持运动，但是玩家远离后漏斗矿车并没有吸取容器内的物品

### 复现步骤 Steps/models to reproduce

制作一个需要用到漏斗矿车的地狱门加载器，装填足够的加载用矿车后迅速远离，加载器未离开视距时正常工作，离开视距返回后能看到从对面维度返回的矿车掉落物没有被漏斗矿车吸取
![huge_2023-08-15_20 29 36](https://github.com/LeavesMC/Leaves/assets/102218562/43706392-5da4-4418-a15a-57ce96975b93)
![huge_2023-08-15_20 31 19](https://github.com/LeavesMC/Leaves/assets/102218562/9e3ce801-b79d-4218-98a1-c75b0b7a1013)

### 插件与数据包列表。 Plugin and Datapack List.

插件：AnimatedScoreboard, Brewery, CoreProtect, GraveStonesPlus, LeavesTestPlugin, LuckPerms, NexEngine, PlaceholderA
PI, PluginPortal, SkinsRestorer,spark, TrChat, TrMenu, ViaBackwards, ViaVersion, WorldEdit
数据包：[vanilla (built-in)], [file/XKsmallmap1.17-1.zip (world)], [file/craft_head_data
pack.zip (world)], [file/fast_Dispenser.zip (world)], [file/bukkit (world)]

### 更多详细信息。 The more information.

这算个bug还是提议？
虽然知道leaves是paper魔改而来而且paper本身就不支持漏斗矿车自己工作
不过还是希望能修改一下
这对加载器和一些全自动的机器很重要
非常感谢
（服务器的leaves还没升级，如果已经发布新版本修复了的话就当我是个清朝老兵好了）

**Comment by s-yh-china** [comment]
我并不能复现这个问题 需要更多测试

**Comment by little-boluo** [comment]
可以构建一个像https://www.bilibili.com/video/BV17M4y1G7gZ/?spm_id_from=333.337.search-card.all.click&vd_source=f667cc2d220cc41efbb80f975a3cc1a5视频中的加载器
然后启动后跑远一点
回来就会看到散落在地上的矿车掉落物了

**Comment by s-yh-china** [comment]
最新版本已修复 待测试
