### ISSUE TITLE
TNT相关优化

### ISSUE THREAD

**Issue by little-boluo** [LeavesMC/Leaves#114]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望能添加carpet中的一些TNT功能
1 TNT放置不产生方块更新
2 TNT高优先级
3 TNT合并

**Comment by s-yh-china** [comment]
放置方块不方块更新指令已经有了
请问tnt高优先级是个什么东西.?

**Comment by little-boluo** [comment]
想问问能不能把只在放置TNT时方块不更新做为一条单独的规则，只针对玩家放置TNT的情况
TNT高优先级是我多打了，这个放到leaves上面没有意义

**Comment by safesaffawa** [comment]
114是吧 迟早给你关咯

**Comment by safesaffawa** [comment]
> ### 描述你希望添加的功能。 Describe the feature you'd like.
> 希望能添加carpet中的一些TNT功能 1 TNT放置不产生方块更新 2 TNT高优先级 3 TNT合并
> 
> ### 其他 Other
> _No response_

我给你这个问题提 内容修正
1 TNT放置点燃后 不产生方块更新
2 TNT比其他方块有更高优先级（就是先来）
3 TNT合并（万宁tnt 就是威力 X n）

**Comment by WhitePhosphor** [comment]
> 114是吧 迟早给你关咯

。非答辩issues下面尽量不要玩梗
