### ISSUE TITLE
分离额外的协议支持

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Leaves#119]
是否可以尝试将额外的协议支持分离为单独的插件，可以让其他支持bukkit的服务端使用(例如purpur)

**Comment by s-yh-china** [comment]
有何必要呢 并且这很麻烦 我暂时没有时间

**Comment by Error-106** [comment]
那我尝试一下吧

**Comment by WhitePhosphor** [comment]
实际上这真的没有必要
毕竟leaves是为生做支持的 肯定要为一些mod做protocol支持
但是如果单独分离出来写插件......不是很支持
首先就和violetc说的一样很麻烦
其次开发会消耗大量时间
第三没办法保证写出来的插件和别的插件不冲突
