### ISSUE TITLE
AppleSkin Support

### ISSUE THREAD

**Issue by FrtHone** [LeavesMC/Leaves#12]
### 描述你希望添加的功能。 Describe the feature you'd like.

Could you add support for AppleSkin to make saturation and exhaustion display working on servers?

### 其他 Other

AppleSkin Mod: https://modrinth.com/mod/appleskin

Spigot/Paper plugin:
https://github.com/jmattingley23/AppleSkinSpigot
https://www.curseforge.com/minecraft/bukkit-plugins/paperapple

**Comment by s-yh-china** [comment]
done
