### ISSUE TITLE
假人无法像正常玩家一样被压为潜行/躺下

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Leaves#123]
### 服务端版本 LeavesMC Version

git-Leaves-"bd1484f"

### 预期的行为 Expected behavior

假人像正常玩家一样被压为潜行/躺下

### 观测到的实际行为 Observed/Actual behavior

假人无法像正常玩家一样被压为潜行/躺下

### 复现步骤 Steps/models to reproduce

使用活板门/活塞等尝试挤压假人

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins(11):
CatSeedLogin,CoreProtect,floodgate,LuckPerms,*MCBot,MySqlAPI,placeholderapi,*SimpleTpa,SkinRestorer,TAB,*Vault

**Comment by s-yh-china** [comment]
目前已有假人动作来使假人潜行/躺下，自动完成较为复杂，不打算制作

**Comment by Error-106** [comment]
无法自动完成意味着一些利用压头的等调整视角的机器无法使用假人挂机以及会导致一些穿模/卡死假人的情况发生

**Comment by s-yh-china** [comment]
合理
