### ISSUE TITLE
为minihud添加额外协议支持

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Leaves#124]
### 描述你希望添加的功能。 Describe the feature you'd like.

Masa Gadget已于3.0.0版本删除minihud使用BBOR协议获取数据的支持，是否能为minihud添加carpet相关协议/Servux协议的支持

**Comment by s-yh-china** [comment]
为什么不用BBOR呢(

**Comment by Error-106** [comment]
玩家是可以转为使用BBOR，但一般生电玩家用masa全家桶多一些

**Comment by s-yh-china** [comment]
但是我用 所以此功能会做 但是优先级会很低

**Comment by Error-106** [comment]
结构边界没有正常报告给客户端，不管是minihud还是bbor都无法使用leaves的servux协议获取结构信息(其他待测试)

**Comment by s-yh-china** [comment]
未知的情况 我这边测试完全正常

**Comment by Error-106** [comment]
似乎装载部分(仅测试了iseeyou不清楚是否存在于其他插件)插件会导致不显示结构边界(在使用默认生成的配置文件且仅打开servux协议的服务端上测试通过，但在加入ISeeYou插件后无结构边界显示)

**Comment by Error-106** [comment]
不仅仅局限于iseeyou插件，其他插件也存在此问题(正在缩小范围)

**Comment by s-yh-china** [comment]
需要测试1.20.2
~起码我这边没问题~

**Comment by s-yh-china** [comment]
done
