### ISSUE TITLE
fakeplayer.always-send-data在从末地返回主世界后失效

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Leaves#125]
### 服务端版本 LeavesMC Version

git-Leaves-"becbb7a"

### 预期的行为 Expected behavior

在进入末地再通过传送门重新回到主世界后假人后继续向玩家报告假人位置

### 观测到的实际行为 Observed/Actual behavior

在进入末地再通过传送门重新回到主世界后假人后不再向玩家报告假人位置，直到重新进入玩家实体加载范围内

### 复现步骤 Steps/models to reproduce

进入末地再通过龙坛回来(地狱传送门不会出现此问题)

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins(11):
CatSeedLogin,CoreProtect,floodgate,LuckPerms,*MCBot,MySqlAPI,placeholderapi,*SimpleTpa,SkinRestorer,TAB,*Vault

**Comment by s-yh-china** [comment]
很高兴你能发现这些问题，我建议加入qq群603461533进行详聊issue聊天还是不好
