### ISSUE TITLE
给僵尸村民喂食金苹果后masagadget显示的治愈时间不正确

### ISSUE THREAD

**Issue by YouQi-0v0** [LeavesMC/Leaves#128]
### 服务端版本 LeavesMC Version

git-Leaves-"bd1484f" (MC: 1.20.1)

### 预期的行为 Expected behavior

向僵尸村民丢虚弱药水喂金苹果后，显示出治愈所需时间，并倒数读秒
![singleplay](https://github.com/LeavesMC/Leaves/assets/91328191/567a10af-a63e-4fc0-971a-6abd40e98c62)
单人世界里测试是这样的

### 观测到的实际行为 Observed/Actual behavior

向僵尸村民丢虚弱药水喂金苹果后，仅显示出治愈所需时间，但不读秒；玩家重新进服后，显示的治愈所需时间变回-1

### 复现步骤 Steps/models to reproduce

![test](https://github.com/LeavesMC/Leaves/assets/91328191/83617ae2-210c-4ccd-ab35-5382e0e46d85)

### 插件与数据包列表。 Plugin and Datapack List.

2023/9/6 17:19 在leaves官服内复现问题

### 更多详细信息。 The more information.

这些mod使用的测试版本是
MasaGadget-all-3.2.326+05982dc-beta.jar
magiclib-all-0.7.382+17856bd-beta.jar

**Comment by s-yh-china** [comment]
link plusls/MasaGadget#56
