### ISSUE TITLE
Xaero's World Map Multiple World Detection Support

### ISSUE THREAD

**Issue by FrtHone** [LeavesMC/Leaves#13]
### 描述你希望添加的功能。 Describe the feature you'd like.

Could you add support for Xaero's World Map multiworld detection? The map of the client can be automatically switched between servers with this feature.

### 其他 Other

Xaero's World Map mod:
https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map

Third party's implementation using Spigot Plugin:
https://www.spigotmc.org/resources/xaero-map-spigot.105695/

**Comment by s-yh-china** [comment]
done
