### ISSUE TITLE
剪刀无法旋转已充能的比较器

### ISSUE THREAD

**Issue by Error-106** [LeavesMC/Leaves#131]
### 服务端版本 LeavesMC Version

git-Leaves-"becbb7a"

### 预期的行为 Expected behavior

剪刀可以正常旋转已充能的比较器

### 观测到的实际行为 Observed/Actual behavior

剪刀无法旋转已充能的比较器

### 复现步骤 Steps/models to reproduce

对比较器充能

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins(11):
CatSeedLogin,CoreProtect,floodgate,LuckPerms,*MCBot,MySqlAPI,placeholderapi,*SimpleTpa,SkinRestorer,TAB,*Vault

**Comment by Error-106** [comment]
是否可以尝试在旋转后更新比较器或直接将其设为未充能？直接禁用旋转充能的比较器会导致一些不方便断开充能信号的情况无法旋转(例如信号源为蛋糕或者已填充的堆肥桶)

**Comment by s-yh-china** [comment]
不可以直接进行更新 那会导致一些问题 比如放飞世吞 设置为不充能也会导致不可能存在的方块状态出现
