### ISSUE TITLE
使用fabric拾取经验球机制

### ISSUE THREAD

**Issue by minecraft-fff** [LeavesMC/Leaves#136]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望使用fabric经验球机制，而不是paper

**Comment by s-yh-china** [comment]
我不明白你的意思，你可以详细描述一下

**Comment by minecraft-fff** [comment]
就是和fabric存档一样的经验求拾取，一个一个的，不是一个球涨了一级，或者在配置文件中加一个开启或关闭这个功能的选项

**Comment by s-yh-china** [comment]
这是一个paper配置文件中已有的功能，请自行寻找并修改，我没有必要为此单独制作一个功能

**Comment by minecraft-fff** [comment]
好的
