### ISSUE TITLE
假人潜行无效

### ISSUE THREAD

**Issue by little-boluo** [LeavesMC/Leaves#138]
### 服务端版本 LeavesMC Version

git-leaves-"e439872"(MC:1.20.1)

### 预期的行为 Expected behavior

使用/bot action … sneak使假人潜行
此时假人能直接对着发射器放置树苗

### 观测到的实际行为 Observed/Actual behavior

使用该指令无法是假人潜行
没有蹲下的动作显示也不能对着容器放置方块

### 复现步骤 Steps/models to reproduce

![mmexport1695393436110](https://github.com/LeavesMC/Leaves/assets/102218562/ff92b2cf-e0d6-496d-97bd-0f0e59c441de)

### 插件与数据包列表。 Plugin and Datapack List.

插件: AnimatedScoreboard, Brewery, CoreProtect, GraveStonesPlus, LeavesTestPlugin, LuckPerms, NexEngine, PlaceholderA
PI, PluginPortal, SkinsRestorer, spark, TrChat, TrMenu, ViaBackwards, ViaVersion, WorldEdit
数据包: [vanilla (built-in)], [file/XKsmallmap1.17-1.zip (world)], [file/craft_head_data
pack.zip (world)], [file/datapack.zip (world)], [file/bukkit (world)]

**Comment by little-boluo** [comment]
并不是所有时间都无效，有随机性

**Comment by s-yh-china** [comment]
请更新服务端后重新进行尝试

**Comment by little-boluo** [comment]
重启服务器可以解决，暂时没有再次复现该bug
