### ISSUE TITLE
同时支持正版与外置登录

### ISSUE THREAD

**Issue by MC-XiaoHei** [LeavesMC/Leaves#14]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望能同时支持正版玩家和外置玩家登入，并保留其UUID，实现类似Velocity+Fabric Proxy的效果
（能支持统一通行证就更好辣）

**Comment by IlyaIvanovsky** [comment]
我在配置文件里发现了extra-yggdrasil
所以是不是这个功能？

**Comment by s-yh-china** [comment]
> 我在配置文件里发现了extra-yggdrasil 所以是不是这个功能？

是的

**Comment by s-yh-china** [comment]
done
