### ISSUE TITLE
希望同时加载paper插件和fabric模组（做不了也没关系）

### ISSUE THREAD

**Issue by minecraft-fff** [LeavesMC/Leaves#140]
### 描述你希望添加的功能。 Describe the feature you'd like.

能同时添加paper和fabric模组（做不了也没关系）

**Comment by s-yh-china** [comment]
没有任何类似的计划 任何此类尝试都是有根本上的缺陷的

**Comment by WhitePhosphor** [comment]
是这样的
这种计划只能是天方夜谭
或者你可以左转出门cardboard
而不是在这个专门在paper恢复生电特性的地方提这种没有意义的issue

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月01日 13:05 |
| 收件人 | LeavesMC/Leaves ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [LeavesMC/Leaves] 希望同时加载paper插件和fabric模组（做不了也没关系） (Issue #140) |

Closed #140 as not planned.
