### ISSUE TITLE
伪和平装置无法正常运作

### ISSUE THREAD

**Issue by baishabft** [LeavesMC/Leaves#141]
### 服务端版本 LeavesMC Version

mc 1.20.1

### 预期的行为 Expected behavior

在一个加载的区块放了大量的凋灵（>1000）
足以撑满原版的刷怪上限（没有改过上限）
已达到其他区块不刷敌对生物的效果
此装置在1.20版本和原版1.21可以正常使用

### 观测到的实际行为 Observed/Actual behavior

更新leaves1.20.1后
此装置失效
区块确实任然在加载，但是里面的怪物只能让附近几个区块停止刷怪，走远后装置失效

### 复现步骤 Steps/models to reproduce

在一个区块内通过基岩放置大量凋灵
并在旁边做一个区块加载器

### 插件与数据包列表。 Plugin and Datapack List.

插件： - CoreProtect, floodgate, FWDeathSwap, Geyser-Spigot, InvSeePlusPlus, iShop, Logger, Metamorph, OpeNLogin, PlayerBan
 PlugMan, QuickSave, SkinsRestorer, spark, ViaVersion

**Comment by s-yh-china** [comment]
请给出具体的服务端版本号和paper的配置文件

**Comment by baishabft** [comment]
This server is running Leaves version git-Leaves-"847357b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 847357b)
You are 9 version(s) behind
Download the new version at: https://leavesmc.top/downloads/leaves
Previous version: git-Leaves-"1771f7e" (MC: 1.20)

**Comment by baishabft** [comment]
# Configuration file for Leaves.

settings:
  protocol:
    alternative-block-placement: CARPET
    leaves-carpet-support: true
    bladeren:
      protocol: true
      mspt-sync-tick-interval: 20
      mspt-sync-protocol: false
    servux-protocol: false
    syncmatica:
      enable: false
      quota: false
      quota-limit: 40000000
    jade-protocol: false
    bbor-protocol: true
    pca-sync-player-entity: EVERYONE
    pca-sync-protocol: false
    xaero-map-protocol: true
    xaero-map-server-id: -1212195110
    appleskin-protocol: false
  performance:
    optimize-sun-burn-tick: true
    use-optimized-collection: true
    skip-entity-move-if-movement-is-zero: true
    optimized-CubePointRange: true
    cache-ignite-odds: true
    skip-negligible-planar-movement-multiplication: true
    check-frozen-ticks-before-landing-block: true
    cache-CubeVoxelShape-shape-array: true
    skip-unnecessary-mob-spawning-computations: true
    optimize-world-generation-and-block-access: true
    cache-world-generator-sea-level: true
    optimized-dragon-respawn: false
    use-fast-item-merge-raytracing: true
    faster-chunk-serialization: true
    optimize-noise-generation: false
    cache-BlockStatePairKey-hash: true
    fix-villagers-dont-release-memory: false
    store-mob-counts-in-array: true
    skip-cloning-advancement-criteria: false
    cache-ominous-banner-item: true
    skip-secondary-POI-sensor-if-absent: true
    check-spooky-season-once-an-hour: true
    reduce-chuck-load-and-lookup: true
    biome-temperatures-use-aging-cache: true
    optimize-chunk-ticking: true
    remove:
      damage-lambda: true
      tick-guard-lambda: true
      range-check-streams-and-iterators: true
      inventory-contains-iterators: true
      get-nearby-players-streams: true
    optimize-entity-coordinate-key: true
    reduce-entity-allocations: true
    dont-send-useless-entity-packets: true
    skip-poi-find-in-vehicle: true
    use-more-thread-unsafe-random: true
    improve-fluid-direction-caching: true
    simpler-vanilla-shapeless-recipes: true
    reduce-entity-fluid-lookup: true
    strip-raytracing-for-entity: true
    enable-suffocation-optimization: true
    cache-climb-check: true
    fix:
      fix-paper-9372: true
      fix-paper-6045: true
    inactive-goal-selector-disable: false
    entity-target-find-optimization: true
    async-mob-spawning: false
    async-entity-tracker: false
    async-pathfinding: false
  modify:
    minecraft-old:
      instant-block-updater-reintroduced: false
      redstone-wire-dont-connect-if-on-trapdoor: false
      zero-tick-plants: false
      mending-compatibility-infinity: false
      shears-in-dispenser-can-zero-amount: false
      loot-world-random: false
    container-passthrough: false
    avoid-anvil-too-expensive: false
    creative-no-clip: false
    disable-check-out-of-order-command: false
    despawn-enderman-with-block: true
    no-block-update-command: false
    spider-jockeys-drop-gapples: -1.0
    bow-infinity-fix: false
    disable-packet-limit: true
    raider-die-skip-self-raid-check: false
    tick-command: false
    ignore-lc: false
    lava-riptide: false
    hopper-counter: false
    shave-snow-layers: true
    elytra-aeronautics:
      no-chunk-load: false
      no-chunk-height: 500.0
      no-chunk-speed: -1.0
      message: true
      message-start: Flight enter cruise mode
      message-end: Flight exit cruise mode
    force-void-trade: false
    snowball-and-egg-can-knockback-player: true
    fix-update-suppression-crash: true
    instant-block-updater-reintroduced: false
    return-nether-portal-fix: false
    spectator-dont-get-advancement: false
    budding-amethyst-can-push-by-piston: false
    no-feather-falling-trample: false
    shared-villager-discounts: false
    stackable-shulker-boxes: 'false'
    stick-change-armorstand-arm-status: true
    disable-distance-check-for-use-item: false
    shears-in-dispenser-can-zero-amount: false
    player-operation-limiter: false
    redstone-shears-wrench: true
    flatten-triangular-distribution: false
    mc-technical-survival-mode: true
    use-vanilla-random: false
    renewable-elytra: -1.0
    fakeplayer:
      spawn-phantom: false
      enable: true
      unable-fakeplayer-names:
      - player-name
      limit: 10
      prefix: ''
      suffix: ''
      always-send-data: true
      resident-fakeplayer: false
      open-fakeplayer-inventory: true
      skip-sleep-check: true
    bedrock-break-list: false
  misc:
    server-mod-name: Leaves
    server-lang: en_us
    dont-respond-ping-before-start-fully: true
    bstats-privacy-mode: false
    auto-update:
      enable: false
      time:
      - '14:00'
      - '2:00'
    no-chat-sign: true
    disable-method-profiler: true
    extra-yggdrasil-service:
      login-protect: false
      enable: false
      urls:
      - https://url.with.authlib-injector-yggdrasil
config-version: 5
world-settings:
  default: {}
  world: {}
  world_nether: {}
  world_the_end: {}

**Comment by s-yh-china** [comment]
请尝试修改paper设置中的entities.spawning.per-player-mob-spawns为false

**Comment by baishabft** [comment]
请问是在哪个文件，leaves中没找到此设置

**Comment by s-yh-china** [comment]
config/paper-world-defaults.yml 中

**Comment by baishabft** [comment]
请问是什么新增内容导致了此问题吗，我们之前并没有这样

**Comment by s-yh-china** [comment]
> 请问是什么新增内容导致了此问题吗，我们之前并没有这样

上游服务端paper的功能导致的 这个功能使得刷怪被平均分配了 和leaves没啥关系

**Comment by baishabft** [comment]
修复了部分，目前任然存在问题，测试发现，必须先强加载一下储存凋灵的区块再弱加载才行，单纯弱加载依然不会生效

**Comment by baishabft** [comment]
请问leaves或者paper有对tnt进行什么更改或优化吗，发现正常单人里卡好时间不会炸膛的机器，放到leaves服务器中会出现概率早炸导致机器炸膛

**Comment by s-yh-china** [comment]
> 请问leaves或者paper有对tnt进行什么更改或优化吗，发现正常单人里卡好时间不会炸膛的机器，放到leaves服务器中会出现概率早炸导致机器炸膛

可能是pape干了什么，但我也不清楚，如果能找到具体原因我就修了XD

**Comment by baishabft** [comment]
好的好的

**Comment by s-yh-china** [comment]
> 请问掉落物聚集这个可以修改吗，后续发现机器中的掉落物会出现抽搐等行为，可以看下视频:BV1Qc411f7n7 已将spigot.yml中的merge-radius: item:的值改为1.0并且重启，但任然会这样

可以尝试关闭paper-world-defaults.yml的fix-items-merging-through-walls选项，如果还是不行，请重新提交issue，我会尝试修复

**Comment by baishabft** [comment]
此选项已经是false了

**Comment by baishabft** [comment]
请问paper的掉落物聚集目前没办法直接关掉或改为原版吗

**Comment by baishabft** [comment]
已提交新的issue

**Comment by baishabft** [comment]
很抱歉在这个issue下继续打扰您，假人方面也有一部分问题，就是发现，假人的攻击无法造成真实伤害（假人在攻击，也有受击粒子，但是无法造成伤害和击退）break指令也无法使用，假人在挖掘，但是挖不掉
以及好像没发现有让假人可以放置方块的指令

**Comment by s-yh-china** [comment]
> 很抱歉在这个issue下继续打扰您，假人方面也有一部分问题，就是发现，假人的攻击无法造成真实伤害（假人在攻击，也有受击粒子，但是无法造成伤害和击退）break指令也无法使用，假人在挖掘，但是挖不掉 以及好像没发现有让假人可以放置方块的指令

https://docs.leavesmc.top/zh/leaves/fakeplayer
请确定自己是最新版本，我不为旧版本提供支持

**Comment by baishabft** [comment]
换了最新的版本，但是假人任然如上述无法正常使用

**Comment by LeafletXD** [comment]
> 换了最新的版本，但是假人任然如上述无法正常使用

登录插件会阻止假人做任何交互动作，比如Authme对于未登录的玩家会阻止攻击、破坏和放置等行为，有人发过Issues了（导致我对假人无法自动钓鱼纳闷了快1个月，逛Issues才看到）

**Comment by s-yh-china** [comment]
> > 换了最新的版本，但是假人任然如上述无法正常使用
> 
> 登录插件会阻止假人做任何交互动作，比如Authme对于未登录的玩家会阻止攻击、破坏和放置等行为，有人发过Issues了（导致我对假人无法自动钓鱼纳闷了快1个月，逛Issues才看到）

这个问题将会在接下来的版本得到修正 我会分离假人的事件 如果你需要查看何时完成 可以发个新的issue(

**Comment by LeafletXD** [comment]
> > > 换了最新的版本，但是假人任然如上述无法正常使用
> > 
> > 登录插件会阻止假人做任何交互动作，比如Authme对于未登录的玩家会阻止攻击、破坏和放置等行为，有人发过Issues了（导致我对假人无法自动钓鱼纳闷了快1个月，逛Issues才看到）
> 
> 这个问题将会在接下来的版本得到修正 我会分离假人的事件 如果你需要查看何时完成 可以发个新的issue(

好耶！:D

**Comment by s-yh-china** [comment]
最新版应该已经修复了这个问题 try



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月22日(周四) 中午12:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 伪和平装置无法正常运作 (Issue #141)




    
换了最新的版本，但是假人任然如上述无法正常使用
  
登录插件会阻止假人做任何交互动作，比如Authme对于未登录的玩家会阻止攻击、破坏和放置等行为，有人发过Issues了（导致我对假人无法自动钓鱼纳闷了快1个月，逛Issues才看到）
  
这个问题将会在接下来的版本得到修正 我会分离假人的事件 如果你需要查看何时完成 可以发个新的issue(
  
好耶！:D

**Comment by LeafletXD** [comment]
假人没有修复，只装了Authme :(
