### ISSUE TITLE
刷沙机器无法使用

### ISSUE THREAD

**Issue by HaoServer** [LeavesMC/Leaves#143]
### 服务端版本 LeavesMC Version

Leaves 1.20.2

### 预期的行为 Expected behavior

刷沙机可以正常使用

### 观测到的实际行为 Observed/Actual behavior

刷沙机器无法使用，沙子传送到末地后消失，主世界沙子并未消失

### 复现步骤 Steps/models to reproduce

-

### 插件与数据包列表。 Plugin and Datapack List.

CMI
res领地

**Comment by s-yh-china** [comment]
请提供一下刷沙机的架构 我这边测试是没问题的
![image](https://github.com/LeavesMC/Leaves/assets/58360096/8008912d-701b-418f-9dee-186eb737d0da)

**Comment by HaoServer** [comment]
使用的是下方链接的机器：
【【铁砧龙蛋也能刷】8gt动能通用重力方块复制机 每小时108000】 https://www.bilibili.com/video/BV1FQ4y1a7YU/?share_source=copy_web&vd_source=2b484c73842cdc9e48865163300b3dc3

**Comment by s-yh-china** [comment]
> 使用的是下方链接的机器： 【【铁砧龙蛋也能刷】8gt动能通用重力方块复制机 每小时108000】 https://www.bilibili.com/video/BV1FQ4y1a7YU/?share_source=copy_web&vd_source=2b484c73842cdc9e48865163300b3dc3

测试过后是可以使用的 这个机器有方向性 请检查一下
有问题再开
