### ISSUE TITLE
掉落物较多时可能会卡在奇怪的地方抽搐

### ISSUE THREAD

**Issue by baishabft** [LeavesMC/Leaves#144]
### 服务端版本 LeavesMC Version

mc 1.20.1

### 预期的行为 Expected behavior

正常情况下掉落物应该顺着水流冲走

### 观测到的实际行为 Observed/Actual behavior

但是掉落物卡在奇怪的地方抽搐
可以参考视频BV1Qc411f7n7

### 复现步骤 Steps/models to reproduce

复刻了一台地毯铁轨机
单人档中无此问题
机器视频:BV13M411b7KC

### 插件与数据包列表。 Plugin and Datapack List.

插件： - CoreProtect, floodgate, FWDeathSwap, Geyser-Spigot, InvSeePlusPlus, iShop, Logger, Metamorph, OpeNLogin, PlayerBan
PlugMan, QuickSave, SkinsRestorer, spark, ViaVersion

**Comment by s-yh-china** [comment]
先关了
