### ISSUE TITLE
盔甲架受击掉落动量

### ISSUE THREAD

**Issue by little-boluo** [LeavesMC/Leaves#146]
### 服务端版本 LeavesMC Version

git-Leaves-"847357b" (MC: 1.20.1)

### 预期的行为 Expected behavior

![huge_2023-10-27_21 38 14](https://github.com/LeavesMC/Leaves/assets/102218562/ed863856-1a23-482c-a060-370e39c8b118)
![huge_2023-10-27_21 37 55](https://github.com/LeavesMC/Leaves/assets/102218562/8ab28de4-3730-4528-883d-2a813f2df933)
使用不可堆叠分类机可以分类出盔甲而且收集里不会进盔甲架

### 观测到的实际行为 Observed/Actual behavior

在leaves端里可以分类出盔甲但是收集里会进盔甲架

### 复现步骤 Steps/models to reproduce

![huge_2023-10-27_21 41 05](https://github.com/LeavesMC/Leaves/assets/102218562/94a79224-cca6-4f5a-ac32-b09f22b425e0)
使用这种架构盔甲架被破坏后有很大概率使盔甲架掉落物拥有一个向上的动量上浮沿着水道进入中间的漏斗，但是理应进入底下的漏斗
测试了多种机器都有相同情况

### 插件与数据包列表。 Plugin and Datapack List.

Bukkit Plugins:
[Server] [21:46:11 INFO]:  - AnimatedScoreboard, Brewery, CoreProtect, GraveStonesPlus, LeavesTestPlugin, LuckPerms, NexEngine, PlaceholderA
PI, PluginPortal, SkinsRestorer
[Server] [21:46:11 INFO]:  spark, toNeko, TrMenu, ViaBackwards, ViaVersion, WorldEdit

[vanilla (built-in)], [file/XKsmallmap1.17-1.zip (world)], [file/craft_head_datapack.zip (world)], [file/datapack.zip (world)], [file/bukkit (world)]

### 更多详细信息。 The more information.

没有更改盔甲架相关的配置文件

**Comment by s-yh-china** [comment]
(?) 尝试把配置文件中的settings.modify.use-vanilla-random打开?

**Comment by little-boluo** [comment]
打开了，依然会复现以上问题

**Comment by s-yh-china** [comment]
> 打开了，依然会复现以上问题

请尝试升级到最新版本
