### ISSUE TITLE
添加单个玩家允许召唤的最大假人数量

### ISSUE THREAD

**Issue by owen233666** [LeavesMC/Leaves#147]
### 描述你希望添加的功能。 Describe the feature you'd like.

添加单个最大的假人生成数量，管理员无限制，普通玩家由权限节点bukkit.command.bot.perplayersummon.<amount>(只是一个设想具体无所谓)，或者设置单个权限，额外用指令规定单个玩家生成的数量，并且给每个生成的假人打上生成玩家的uuid标签以辨别

**Comment by s-yh-china** [comment]
已经提供api支持，插件自己写吧(x)
