### ISSUE TITLE
Moved quickly 不能在配置文件中关闭提示

### ISSUE THREAD

**Issue by sekaom** [LeavesMC/Leaves#150]
### 服务端版本 LeavesMC Version

git-Leaves-"10acfe9"

### 预期的行为 Expected behavior

在配置文件里设置disable-moved-wrongly-threshold为true来关闭关于移动产生的moved quickly

### 观测到的实际行为 Observed/Actual behavior

![362EC553-BF39-42A9-9E80-47C3CFDE31E2](https://github.com/LeavesMC/Leaves/assets/90206655/d223468b-8d6b-495a-a6b1-93107909b828)

### 复现步骤 Steps/models to reproduce

leaves配置文件中开启disable-moved-wrongly-threshold后正产启动服务端。玩家使用传送传送到远地方

### 插件与数据包列表。 Plugin and Datapack List.

ARedstoneDisable, AdvancedBan, AntiCreeper, AuthMe, AuthMeVelocity, BanItem, CMILib, Chunky, Citizens, CoreProtect, CrazyAuctionsPlus, CrazyEnchantments, CrisTreeCapitator, DeathMessages, DeluxeMenus, GSit, HuskHomes, HuskHomesGUI, HuskSync, ItemJoin, JoinMessagePlus, LiteSignIn, LocketteX, LuckPerms, McMmoView, Multiverse-Core, Multiverse-NetherPortals, MusicBox, NBTAPI, NoteBlockAPI, PlaceholderAPI, ProtocolLib, QuickShop, Residence, SellGUI, ServerUtils, SkinsRestorer, SlimeGlue, Slimefun, SmoothSleep, TAB, TrChat, UltimateTrash, Vault, ViaBackwards, ViaVersion, WkKit, XConomy, craft233 and mcMMO

**Comment by s-yh-china** [comment]
漏了咳咳，fixed
