### ISSUE TITLE
Authme的问题

### ISSUE THREAD

**Issue by QRNW** [LeavesMC/Leaves#151]
### 描述你希望添加的功能。 Describe the feature you'd like.

假人无法登录导致无法使用action类功能

### 其他 Other

none

**Comment by s-yh-china** [comment]
不考虑 插件导致的问题 应该去找插件作者适配

**Comment by QRNW** [comment]
假人输指令呢

**Comment by QRNW** [comment]
> 不考虑 插件导致的问题 应该去找插件作者适配

那可不可弄假人自动输指令

**Comment by s-yh-china** [comment]
没有必要 并且会导致更多权限混乱问题 不考虑
