### ISSUE TITLE
Replay API Not Work

### ISSUE THREAD

**Issue by MC-XiaoHei** [LeavesMC/Leaves#152]
### 服务端版本 LeavesMC Version

all ver after 1.20.2

### 预期的行为 Expected behavior

replay api能正常使用

### 观测到的实际行为 Observed/Actual behavior

一旦使用replay api将导致服务器崩溃

### 复现步骤 Steps/models to reproduce

安装ISeeYou插件，进入服务器即可

### 插件与数据包列表。 Plugin and Datapack List.

ISeeYou

**Comment by s-yh-china** [comment]
大概已经修复了
