### ISSUE TITLE
Leaves Version Fetchers Fails To Obtain Version Info and gives a error 301

### ISSUE THREAD

**Issue by Pancaksee** [LeavesMC/Leaves#153]
### 服务端版本 LeavesMC Version

cb31cda

### 预期的行为 Expected behavior

To show version info

### 观测到的实际行为 Observed/Actual behavior

Gives A Error 301 and fails to obtain version info

### 复现步骤 Steps/models to reproduce

Type /version

### 插件与数据包列表。 Plugin and Datapack List.

None

### 更多详细信息。 The more information.

Here's the logs
https://mclo.gs/w9vW1dm

**Comment by GLDYM** [comment]
Thats Strange…… Maybe u should first check whether ur server could connect to api.github.com correctly.

**Comment by Pancaksee** [comment]
it didnt

**Comment by GLDYM** [comment]
So maybe u have a plugin which blocks other plugins to visit github (to disable the version check and update of plugins) , or the cloud service provider block it (but it is strange beyond China Mainland) .

**Comment by Pancaksee** [comment]
i have no plugins
