### ISSUE TITLE
配置询问

### ISSUE THREAD

**Issue by TUSB5834** [LeavesMC/Leaves#155]
shared-villager-discounts
默认值: false
简介: 是否允许多个玩家玩家共享同一个村民的折扣。如果为是，那么所有玩家都可以享受到打折效果。
minecraft-old.villager-infinite-discounts
默认值: false
简介: 如果为是，那么村民可以被无限次打折，此特性在1.20.2中被移除。

请问这个配置关闭了1.20.4的村民交易平衡性调整吗?或者是其他配置选项
因为我在老手等级刷出来了经验修补

**Comment by minecraft-fff** [comment]
请问怎么开启1.20.4新版本物品，我的quickshop插件发现了一大堆新版本物品，但游戏中并没有这些（铜网之类的）

**Comment by TUSB5834** [comment]
> 请问怎么开启1.20.4新版本项目，我的quickshop插件发现了一大堆新版本项目，但游戏中并没有这些（铜网之类的）

1.20.4好像并没有新物品

**Comment by s-yh-china** [comment]
村民交易平衡性调整如果你不开实验性是没有的，这两个配置都没还原这个
