### ISSUE TITLE
刷沙机不能正常运行

### ISSUE THREAD

**Issue by LucklyJie** [LeavesMC/Leaves#159]
### 服务端版本 LeavesMC Version

e.g.git-Leaves-"847357b"(MC:1.20.1)

### 预期的行为 Expected behavior

沙子传送至末地门另一端

### 观测到的实际行为 Observed/Actual behavior

机器运行 但沙子并不会出现

### 复现步骤 Steps/models to reproduce

参考视频：https://www.bilibili.com/video/BV1nT411Q7i9/?spm_id_from=333.337.search-card.all.click

### 插件与数据包列表。 Plugin and Datapack List.

 BKCommonLib,Bukkit Plugins,DeluxeMenus, Essentials, EssentialsChat, EssentialsSpawn, GSit, LuckPerms, MiniMOTD, My_Worlds, NBTAPI, PlaceholderAPI

**Comment by s-yh-china** [comment]
能给下leaves.yml吗
