### ISSUE TITLE
无法创造假人

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#16]
### 服务端版本 LeavesMC Version

git-Leaves-"94b985d" (MC: 1.19.3)

### 预期的行为 Expected behavior

/bot create bot1 本应创造假人。

### 观测到的实际行为 Observed/Actual behavior

/bot create bot1未能创造假人，并于控制台抛出异常。

### 复现步骤 Steps/models to reproduce

客户端输入后/bot create bot1未能创造假人。

### 插件与数据包列表。 Plugin and Datapack List.

Plugins (18): AllMusic, Boom, Citizens, CoreProtect, dynmap, Essentials, EssentialsChat, EssentialsSpawn, FartherViewDistance, FreedomChat, GSit, LuckPerms, PlaceholderAPI, ProtocolLib, spark, TAB, Vault, WorldEdit

### 更多详细信息。 The more information.

控制台异常片段的日志。
[latest.log](https://github.com/LeavesMC/Leaves/files/10527076/latest.log)

**Comment by s-yh-china** [comment]
我在最新的94b985d版本上发现了问题
我将会尽快修复 在此之前 你可以回退到cda924b版本来使用假人功能

**Comment by s-yh-china** [comment]
4eaa8f3已修复此问题
