### ISSUE TITLE
希望升级库

### ISSUE THREAD

**Issue by YingZa-0919** [LeavesMC/Leaves#163]
### 描述你希望添加的功能。 Describe the feature you'd like.

例如bungeecord-chat-1.20-R.01 升级为 1.20-R2版本
一些插件在高版本1.20.4已经开始对低版本的库有所不兼容了，希望能尽快升级库

**Comment by s-yh-china** [comment]
emmmmmm
主要paper也没升级，真的有必要动吗

**Comment by YingZa-0919** [comment]
主要spigotmc上的很多插件都是按照Spigot为准....Spigot已经更新了 所以会导致某些更新很频繁的插件产生报错 功能失效 而且更新了貌似也不影响老插件的运行...但是影响了新插件的功能失效
因为我已经试过了单独把这个chatR2库手动替换到leaves核心内了还是依然报错，也就是其他没更新的库也影响这些插件的运行

**Comment by s-yh-china** [comment]
R0.2是19号刚更新的啊(?)，等paper下一次同步spigot版本应该就会更新了，倒也不用着急

**Comment by s-yh-china** [comment]
升级了(
