### ISSUE TITLE
为假人添加GCA的配置

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#17]
### 描述你希望添加的功能。 Describe the feature you'd like.

为假人添加GCA的一些配置
1.假人驻留，关闭服务器后储存假人的各类信息并在启动时自动恢复假人。
2.假人背包/末影箱可视化控制
3.假人自动补货，在手上的物品将要耗尽时补充同类物品。
4.假人自动切换将要损坏的工具。
5.假人自动钓鱼

GCA：https://github.com/Gu-ZT/gugle-carpet-addition

**Comment by s-yh-china** [comment]
可以考虑添加 但是优先级会低一些
然后自动补货是已经实现了 但是可能不是很好用?

**Comment by s-yh-china** [comment]
- [ ] 假人驻留，关闭服务器后储存假人的各类信息并在启动时自动恢复假人。
- [ ] 假人背包/末影箱可视化控制
- [ ] 假人自动补货，在手上的物品将要耗尽时补充同类物品。
- [ ] 假人自动切换将要损坏的工具。
- [ ] 假人自动钓鱼

**Comment by s-yh-china** [comment]
所有功能均已完成 等待测试

**Comment by s-yh-china** [comment]
done
