### ISSUE TITLE
无法使用mcdr指令

### ISSUE THREAD

**Issue by haha44444** [LeavesMC/Leaves#172]
### 服务端版本 LeavesMC Version

git-Leaves-"847357b" (MC: 1.20.1)

### 预期的行为 Expected behavior

在游戏内可以正常执行mcdr指令

### 观测到的实际行为 Observed/Actual behavior

在游戏内使用!!前缀的mcdr指令无任何反应

### 复现步骤 Steps/models to reproduce

在游戏内使用!!前缀的mcdr指令

### 插件与数据包列表。 Plugin and Datapack List.

[Server] [22:39:29 INFO]: Server Plugins (19):
[Server] [22:39:29 INFO]: Bukkit Plugins:
[Server] [22:39:29 INFO]:  - CatSeedLogin, CMI, CMILib, CoreProtect, EClean, LiteSignIn, LuckPerms, Orebfuscator, PlaceholderAPI, PlayerDoll
[Server] [22:39:29 INFO]:  PlugManX, ProtocolLib, QuickShop, Residence, SkinsRestorer, Vault, ViaBackwards, ViaVersion, XConomy

[Server] [22:39:53 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[Server] [22:39:53 INFO]: There are no more data packs available

**Comment by s-yh-china** [comment]
?

**Comment by GLDYM** [comment]
首先，你这个Version显然是错的，估计是复制成prev   Version了；
第二，请检查是否有插件篡改了聊天内容/服务器日志（如猫娘插件）；
第三，请检查MCDR的handler是否正确；
第四，如果你正在使用mcsm，请先尝试关闭仿真终端。

---

总之，这事情和Leaves没啥关系，因为我也在用MCDR（

**Comment by haha44444** [comment]
> 首先，你这个Version显然是错的，估计是复制成prev Version了； 第二，请检查是否有插件篡改了聊天内容/服务器日志（如猫娘插件）； 第三，请检查MCDR的handler是否正确； 第四，如果你正在使用mcsm，请先尝试关闭仿真终端。
> 
> 总之，这事情和Leaves没啥关系，因为我也在用MCDR（

错了错了草才发现version复制错了

**Comment by WhitePhosphor** [comment]
？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月05日 22:46 |
| 收件人 | LeavesMC/Leaves ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [LeavesMC/Leaves] 无法使用mcdr指令 (Issue #172) |

首先，你这个Version显然是错的，估计是复制成prev Version了； 第二，请检查是否有插件篡改了聊天内容/服务器日志（如猫娘插件）； 第三，请检查MCDR的handler是否正确； 第四，如果你正在使用mcsm，请先尝试关闭仿真终端。

总之，这事情和Leaves没啥关系，因为我也在用MCDR（

错了错了草才发现version复制错了

**Comment by haha44444** [comment]
好好好没事儿了，主要是有个**客户我给他用leaves他说换了leaves之后才出现这问题的，我就去看，结果**的，我换purpur还是一样，再去一关cmi的聊天格式，好了tmd，抱歉抱歉我的问题

**Comment by Mooling0602** [comment]
我已经编写了专用于去除ANSICode的MCDR handler，这有助于在使用Minecraft Data API插件时能够正确解析服务端响应内容，稍后会开源发布到GitHub

**Comment by Mooling0602** [comment]
（应该是）Leaves专用的服务端处理器：https://github.com/Mooling0602/Del_ANSICode-MCDR-handler
暂未经过测试
