### ISSUE TITLE
Brush ferrum machine not work properly under suffocation-optimization

### ISSUE THREAD

**Issue by HarryH2O** [LeavesMC/Leaves#176]
### 服务端版本 LeavesMC Version

 git-Leaves-"20ccc9c" (MC: 1.20.4)

### 预期的行为 Expected behavior

Like the original, in the Java version of Minecraft, Iron Golem generation is influenced by the following factors:
1 Villager behavior: If the villager has slept behavior in the past 20 minutes, then they are likely to be candidates for the Iron Puppet. Also, if the villagers are in a panic state and there are two other villagers in their 10×10×10 zone who are also in a panic state, it is possible for iron golems to spawn between these villagers. The spawns of the Iron Golem are located at the central point of these villagers and within a 16×13×16 cube space, which is topped by the complete square closest to the sky.
2 Generation probability: The generation of iron Golems is probabilistic. For each attempt to generate an iron Golem, the system will try up to ten times. If you do not succeed during the attempt, you will need to wait for some time before you can try again. On average, a successful Golem spawns about every 35 seconds.
Spawning restrictions: Iron Golems cannot spawn in a complete block under water, nor in steps, fences, or other adjacent blocks, as these structures may hinder normal spawning of iron Golems or cause suffocation or even death.
4 Other conditions: In addition to the behavior of the villagers, there needs to be sufficient work tables (i.e. beds), clocks or other similar structures in the village, and at least 10 villagers have worked on the work tables. All the villagers in the village must be bound to the bed in order to ensure that the iron Golem can be generated correctly

像原版一样,在Java版Minecraft中，铁傀儡的生成机制主要受以下因素影响：
1村民的行为：如果村民在过去的20分钟内有睡眠行为，那么他们就有可能成为铁傀儡的候选者。此外，如果村民处于惊慌状态，并且在他们的10×10×10区域内还有其他两个同样处于惊慌状态的村民，那么铁傀儡就有可能在这些村民之间生成。铁傀儡的生成地点位于这些村民的中心点，并在一个16×13×16的立方体空间内，这个空间的顶部是最接近天空的完整方块。
2生成概率：铁傀儡的生成是有概率性的。每次尝试生成铁傀儡时，系统最多会尝试十次。如果在尝试过程中没有成功，则需要等待一段时间才能再次尝试。平均来说，大约每35秒会有一次成功的铁傀儡生成。
3生成限制：铁傀儡不能生成在水下的一个完整的方块中，也不能生成在台阶、栅栏或其他相邻的方块里，因为这些结构可能会阻碍铁傀儡的正常生成或导致窒息甚至死亡。
4其他条件：除了村民的行为外，还需要村庄中有足够的工作台（即床）、钟或其他类似的结构，以及至少10个村民在工作台上工作过。村庄内的所有村民都必须与床绑定，这样才能确保铁傀儡能够正确地生成

### 观测到的实际行为 Observed/Actual behavior

In Figure 1 below, the Iron Golem is generated on an incomplete block: an open trap door, which is not the feature of the original Java version of Minecraft
Also, the iron puppet in Figure 2 is generated inside the wall, I can't find the wrong part, and this does not happen at all in the original Java version of Minecraft1.20.4
I am not sure if this is a problem with Leaves, but I hope my problem can be resolved effectively, please deal with it as soon as 
possible, thank you

如下图1,铁傀儡生成在了不完整方块:展开的活板门上,这是与原Java版Minecraft特性不符的
并且,图2中铁傀儡生成在了墙体内部,我无法寻找出错误的部分,并且这是在原Java版Minecraft1.20.4中完全不会发生的
我无法确定这是否是Leaves的问题,但我希望我的问题能得到有效解决,请尽快处理,谢谢

![f5d81aeb423e405441872663f2b05e2e](https://github.com/LeavesMC/Leaves/assets/159914910/6120b324-9adc-44f5-a4cc-eb314e5a3149)
_**The above figure is Figure 1 / 上图为图1**_
![cded518a8b425bcb227c983dd019fd6d](https://github.com/LeavesMC/Leaves/assets/159914910/091e7521-3590-4633-b2f7-fab1af41b9dc)
     **|**       _**The following is Figure 2 / 下图为图2**_

### 复现步骤 Steps/models to reproduce

The attached file is a iron of the brush machine, which works flawlessly in Java version of Minecraft1.20.4 without bugs, but it doesn't work on my server

附加文件是这个刷铁机的原理图,它能在Java版Minecraft1.20.4中准确无误的运行不出现bug,但它无法正常在我的服务器中工作
[Unnamed.zip](https://github.com/LeavesMC/Leaves/files/14267572/Unnamed.zip)

### 插件与数据包列表。 Plugin and Datapack List.

**Plugins List**
AllMusic, BlockLocker, CMI, CMILib, ConsoleSpamFix, CoreProtect, eBackup, ExcellentEnchants, floodgate, Geyser-Spigot JiaoPeixu, LaggRemover, LevelledMobs, LoneLibs, LuckPerms, Marriage, Multiverse-Core, NexEngine, ProtocolLib, RealisticSeasons,Residence, ServerBooster, *StreamCamera, ViaBackwards, ViaRewind, ViaVersion, WorldEdit
**Datapacks List**
[vanilla (built-in)],
[file/BlazeandCaves Advancements Pack 1.16.6.zip (world)]
[file/bukkit (world)], [file/god_datapack v1.0.zip (world)]

### 更多详细信息。 The more information.

Iron golem on the fence, I add carpet,
On the bottom half of the brick, I spread leaves,
It's in the walls, it's in the trap doors
I can't do anything else with it

铁傀儡生成在栅栏上，我加地毯，
生成在下半砖上，我铺树叶，
生成在墙里，生成在活板门上
我无法再对其进行任何改造

**Comment by GLDYM** [comment]
Please help comfirm this bug in Paper or other upstream server first to locate the bug.

---

请先在Paper等上游服务端中尝试复现此Bug，以确定这究竟是上游的Bug还是Leaves的。（为了定位Bug来修复

**Comment by LittleChest** [comment]
将完整结构转为投影文件并附在这里

**Comment by HarryH2O** [comment]
完整结构投影文件在文章中有出现过

**Comment by GLDYM** [comment]
已确认，请等待修复。

**Comment by HarryH2O** [comment]
在paper1.20.4构建#423无插件中此机器可正常使用

**Comment by HarryH2O** [comment]
问题已解决,将leaves.yml文件中的enable-suffocation-optimization设置为false后即可恢复正常
生成生物会检查生成地方是否会导致窒息受伤,铁傀儡的生产实间正好对上检查间隔,关掉窒息检查后铁傀儡就不会生成在奇怪的地方了,对此我希望对其功能优化,我希望在服务端后续版本中能修改窒息检测的时间,使其与其错开,从而不影响使用窒息检测功能

**Comment by s-yh-china** [comment]
正在修复，先不用关

**Comment by silvery0113** [comment]
请确认你的刷铁机结构完整且正确

**Comment by s-yh-china** [comment]
刷铁机本身结构异常

**Comment by HarryH2O** [comment]
蚌埠住了,我按照指示维修还是这样
