### ISSUE TITLE
在LINEAR格式下使用/res tp 崩溃

### ISSUE THREAD

**Issue by w2w2e2wq** [LeavesMC/Leaves#178]
### 服务端版本 LeavesMC Version

git-Leaves-"39bd808" (MC: 1.20.4)

### 预期的行为 Expected behavior

使用/res tp 领地名 传送至领地

### 观测到的实际行为 Observed/Actual behavior

服务器在严重卡顿后崩溃

### 复现步骤 Steps/models to reproduce

1.在末地输入/res tp 领地名传送至主世界的领地
2.服务器崩溃

### 插件与数据包列表。 Plugin and Datapack List.

Paper Plugins:
 - HuskHomes
Bukkit Plugins:
 - AuthMe, BedrockPlayerSupport, Chunky, ClearLag, ClientCrasher, CMI, CMILib, ConsoleSpamFix, CoreProtect, eco
 EcoEnchants, FastAsyncWorldEdit, floodgate, Geyser-Spigot, InteractiveChat, KLEnchant, LaggRemover, libreforge, LuckPerms, MiniMOTD
 Multiverse-Core, NekoMaid, PlaceholderAPI, PlayerChat, PluginPortal, PlugManX, ProtocolLib, Residence, ResidenceForm, SkinsRestorer
 spark, Uniporter, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion

### 更多详细信息。 The more information.

[2024-02-14-3.log](https://github.com/LeavesMC/Leaves/files/14274293/2024-02-14-3.log)

**Comment by GLDYM** [comment]
完全无法复现，日志看起来只是单纯的卡顿。请提供服务器的硬件参数与启动服务端时使用的JVM参数。

**Comment by w2w2e2wq** [comment]
JVM参数
-Xms8192M -Xmx10G --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
配置信息:
系统 Windows Server 2019 Datacenter （amd64） 版本“10.0.17763”，并且有 5 个 CPU 线程可用。
CPU:Intel（R） Xeon（R） Gold 6138 CPU @ 2.00GHz。
 Java21.0.2（Zulu21.32+17-CA 来自 Azul Systems， Inc.）。

**Comment by s-yh-china** [comment]
尝试降低压缩等级吧，别的我也没办法

**Comment by w2w2e2wq** [comment]
> 尝试降低压缩等级吧，别的我也没办法

已经是1了
