### ISSUE TITLE
铁砧掉落异常

### ISSUE THREAD

**Issue by drfe3** [LeavesMC/Leaves#179]
### 服务端版本 LeavesMC Version

This server is running Leaves version git-Leaves-"c8ddbee" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: c8ddbee) You are running the latest version

### 预期的行为 Expected behavior

铁砧放置到y=1上后开始掉落，下方是y=-1的铁砧，铁砧应当掉落在y=0

### 观测到的实际行为 Observed/Actual behavior

铁砧没有掉落在y=0而是变成了掉落物

### 复现步骤 Steps/models to reproduce

在y=-1放置一个铁砧，然后在y=1放置一个铁砧,保证铁砧可以掉落到第一个放置的铁砧上方,然后铁砧就会变成凋落物。第二个放置的铁砧可以是任何重力方块，都会出现此问题。

### 插件与数据包列表。 Plugin and Datapack List.

纯原版leaves未加任何插件

### 更多详细信息。 The more information.

这个问题导致了我们服务器的铁砧连杆世吞损坏 ;w; 请尽快修复
https://bugs.mojang.com/browse/MC-242206
这个问题我测试过已经被spigot1.20.4修复了

**Comment by qqq316** [comment]
据我的测试结果，任何在y=1处放置的重力方块，掉落到y=-1的透明方块（包括上半砖、脚手架等）上时都会掉落成物品。
更详细的链接：https://bugs.mojang.com/browse/MC-238959
该bug在21w41a产生，在1.18 pre release 6修复，但仍旧会造成1.20.4服务器的表现异常。

**Comment by s-yh-china** [comment]
`Paper 干的`
我去给Paper修了然后提到上游吧

**Comment by qqq316** [comment]
https://github.com/PaperMC/Paper/issues/9123 有人提了

**Comment by VapeLite** [comment]
感谢修复!
