### ISSUE TITLE
为假人添加看向指定方块的指令

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#18]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望添加look指令来使假人看向特定的浮点数坐标来精确控制视线。

### 其他 Other

通过rotate指令操控一些容错率很小的视线方向实在是太困难了……

**Comment by s-yh-china** [comment]
指定的方块吗? /bot action xxx look 12.4 11.1 53.4这样的?

**Comment by GLDYM** [comment]
> 指定的方块吗? /bot action xxx look 12.4 11.1 53.4这样的?

是的。

**Comment by s-yh-china** [comment]
这比我想象的要困难一些 我被迫重构了整个假人的指令系统

**Comment by s-yh-china** [comment]
done
