### ISSUE TITLE
Hello, can you please tell me which patch is responsible for returning chunk loaders?

### ISSUE THREAD

**Issue by ImNotSoftik** [LeavesMC/Leaves#180]
### 描述你希望添加的功能。 Describe the feature you'd like.

Hello, can you please tell me which patch is responsible for returning chunk loaders?

**Comment by GLDYM** [comment]
I can't understand which is "returning chunk loaders", please give more information. And generally the file names of patches indicate the functions they do.

**Comment by Bluemangoo** [comment]
You might be finding this:

![image](https://github.com/LeavesMC/Leaves/assets/63218454/11553f26-0534-4b45-9974-f3b9fa0ff5de)
