### ISSUE TITLE
服务端GUI无法显示数据

### ISSUE THREAD

**Issue by FR-N** [LeavesMC/Leaves#188]
### 服务端版本 LeavesMC Version

This server is running Leaves version git-Leaves-"ec5a1fc" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: ec5a1fc)

### 预期的行为 Expected behavior

能在服务端GIU中看到服务器的内存和一些其他的统计数据

### 观测到的实际行为 Observed/Actual behavior

但是什么都没有啊喂

### 复现步骤 Steps/models to reproduce

把no GUI叉出去
启动!

### 插件与数据包列表。 Plugin and Datapack List.

没有任何插件和数据包都会这样

### 更多详细信息。 The more information.

这本来应该是paper-1.20.4-408造成的问题
只不过上游的那位我反馈了以后，他说无法复现我也就只能来这了
https://github.com/PaperMC/Paper/issues/10220
这是那个被关闭的问题
这个不太重要，可以往后排排，不过服务端GUI毕竟是服务端的组成部分，他坏掉了确实挺奇怪的
希望万能的leaves和v姐能解决掉paper解决不了的问题
https://mclo.gs/8IehoqI

**Comment by Dreeam-qwq** [comment]
无法复现。使用https://github.com/LeavesMC/Leaves/commit/ec5a1fc5dad895f1025b7811aee46e4b5f7153ab
![image](https://github.com/LeavesMC/Leaves/assets/61569423/dc695d88-593b-4ebd-a1d5-1a7fc8a0e134)

**Comment by FR-N** [comment]
![image](https://github.com/LeavesMC/Leaves/assets/92735765/1f17f855-aefd-4564-87c3-15a3670a2fd4)
ok 现在是正常的

**Comment by s-yh-china** [comment]
done
