### ISSUE TITLE
第一次运行提示错误

### ISSUE THREAD

**Issue by silvery0113** [LeavesMC/Leaves#198]
### 服务端版本 LeavesMC Version

git-Leaves-"a4a3a92" (MC: 1.20.4)

### 预期的行为 Expected behavior

应提示阅读Leaves文档

### 观测到的实际行为 Observed/Actual behavior

 [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
 [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
*************************************************************************************
[Server thread/INFO]: This is the first time you're starting this server.
[Server thread/INFO]: It's recommended you read our 'Getting Started' documentation for guidance.
[Server thread/INFO]: View this and more helpful information here: https://docs.papermc.io/paper/next-steps
*************************************************************************************

### 复现步骤 Steps/models to reproduce

第一次运行服务端即可

### 插件与数据包列表。 Plugin and Datapack List.

无

**Comment by Bluemangoo** [comment]
我们好像没有相应的落地页。 @LittleChest

**Comment by LittleChest** [comment]
> 我们好像没有相应的落地页。 @LittleChest
> 
> * Link issue [[Missing] Next Steps Documentation#3](https://github.com/LeavesMC/Documentation/issues/3)

没错，因此需要等待文档更新

**Comment by silvery0113** [comment]
Fixed in  [PR＃202](https://github.com/LeavesMC/Leaves/pull/202)
