### ISSUE TITLE
Wither roses that spawn when the player or dummy dies will replace the original block 玩家或假人死后生成的凋零玫瑰会取代原来的方块

### ISSUE THREAD

**Issue by Fortern** [LeavesMC/Leaves#2]
### 服务端版本 LeavesMC Version

git-Leaves-"71f6b7e" (MC: 1.19.1)

### 预期的行为 Expected behavior

玩家或假人死后生成的凋零玫瑰不应该取代非空气方块。
Wither roses that spawn after the player or fake player dies should not replace non-air block.

### 观测到的实际行为 Observed/Actual behavior

假人死在水中生成的凋零玫瑰将水取代，这是不合理的。
Wither roses spawned by fake players dying in water replace water, which is unreasonable.

### 复现步骤 Steps/models to reproduce

生成一个假人，使其死在水中，一旦生成凋零玫瑰，它会将水取代。
Spawn a fake player and make it dead in water. Once a wither rose is spawned, it replaces water.

### 插件与数据包列表。 Plugin and Datapack List.

--

**Comment by s-yh-china** [comment]
这不是一个服务端功能 请检查你的插件列表并联系插件作者
This is not a server-side feature. Please check your plugin list and contact the plugin author
