### ISSUE TITLE
假人attack后台报错

### ISSUE THREAD

**Issue by zmdoyouknow** [LeavesMC/Leaves#20]
### 服务端版本 LeavesMC Version

git-Leaves-"bb29eb0" (MC: 1.19.3)

### 预期的行为 Expected behavior

假人attack breack正常

### 观测到的实际行为 Observed/Actual behavior

后台报错，无法执行

### 复现步骤 Steps/models to reproduce

/bot action xxxx break
/bot action xxxx attack

最后面加不加延迟都报错

### 插件与数据包列表。 Plugin and Datapack List.

see lastest.log

### 更多详细信息。 The more information.

[latest.log](https://github.com/LeavesMC/Leaves/files/10557629/latest.log)

**Comment by GLDYM** [comment]
break,use,use_to,use_on,look指令同样无法使用，报错相似

**Comment by s-yh-china** [comment]
如果将参数填满呢 比如/bot action xxx attack 20 -1

**Comment by GLDYM** [comment]
> 如果将参数填满呢 比如/bot action xxx attack 20 -1
同样报错
[latest.log](https://github.com/LeavesMC/Leaves/files/10557719/latest.log)

**Comment by s-yh-china** [comment]
最新的版本应该已经修复了此bug (我又忘关联issue了)

**Comment by s-yh-china** [comment]
如果此bug已修复 能否回复一下或关闭issue谢谢
