### ISSUE TITLE
最新的viaversion提示不支持

### ISSUE THREAD

**Issue by A-Kevin1217** [LeavesMC/Leaves#207]
### 服务端版本 LeavesMC Version

git-Leaves-"0f16c0c" (MC: 1.20.4)

### 预期的行为 Expected behavior

能够支持viaversion的更新，并正常使用

### 观测到的实际行为 Observed/Actual behavior

更新后不能正常使用

### 复现步骤 Steps/models to reproduce

就是单纯的更新

### 插件与数据包列表。 Plugin and Datapack List.

ViaVersion-4.9.3.jar

**Comment by GLDYM** [comment]
** So where is ur log? If u do not provide log file, the only thing I can do is to ask GOD why u cannot use viaversion.**

---

**所以你的日志哪里去了？不提供日志，我能做的就只有给你算一卦。**

**Comment by Bluemangoo** [comment]
我记得不接受via相关反馈来着。

**Comment by LittleChest** [comment]
[请向 ViaVersion 提交错误反馈](https://github.com/ViaVersion/ViaVersion/issues/new?assignees=&labels=Unconfirmed&projects=&template=bug_report.yml)
