### ISSUE TITLE
复制实体

### ISSUE THREAD

**Issue by LittleChest** [LeavesMC/Leaves#219]
### 描述你希望添加的功能。 Describe the feature you'd like.

这是一个Minecraft旧版本漏洞

### 其他 Other

https://www.bilibili.com/video/BV1aZ421W7t3

**Comment by s-yh-china** [comment]
我看到了，需要寻找高版本失效原因

**Comment by LittleChest** [comment]
> 我看到了，需要寻找高版本失效原因

评论区 我没看懂）

**Comment by s-yh-china** [comment]
明白了，即将加入
