### ISSUE TITLE
1.19+的生物生成上限系统无法正常表现

### ISSUE THREAD

**Issue by s-yh-china** [LeavesMC/Leaves#22]
### 服务端版本 LeavesMC Version

git-Leaves-"11924c6" (MC: 1.19.3)

### 预期的行为 Expected behavior

在1.19+的版本中，生物生成上限被平均分配到了每个玩家，但是总上限依然存在。
当paper.yml中的per-player-mob-spawns为true时，应表现为原版行为。
当paper.yml中的per-player-mob-spawns为false时，应表现为旧版行为。

### 观测到的实际行为 Observed/Actual behavior

分两种情况
1. per-player-mob-spawns为true时，生物生成上限被平均分配，但总上限不存在导致伪和平失效。
2. per-player-mob-spawns为false时，生物生成上限表现为1.19-的情况。

### 复现步骤 Steps/models to reproduce

None

### 插件与数据包列表。 Plugin and Datapack List.

None

**Comment by s-yh-china** [comment]
没好

**Comment by FrtHone** [comment]
经测试，上游项目 Paper 在添加
https://github.com/LeavesMC/Leaves/blob/ecb001ceb03e17185f78e6bc5ef39542426c56bc/patches/server/0018-Optimize-mob-spawning.patch#L152
后地狱门加载的敌对生物会正常计入上限。
合理怀疑是此项目的异步生物生成机制导致非玩家加载的生物不计入上限的问题。

**Comment by s-yh-china** [comment]
> 经测试，上游项目 Paper 在仅修改
> 
> https://github.com/LeavesMC/Leaves/blob/ecb001ceb03e17185f78e6bc5ef39542426c56bc/patches/server/0018-Optimize-mob-spawning.patch#L152
> 
> 
> 后地狱门加载的敌对生物会正常计入上限。
> 合理怀疑是此项目的异步生物生成机制导致非玩家加载的生物不计入上限的问题。

让我看看

**Comment by WratithCr** [comment]
阿巴阿巴……所以导致监守者伪和平失效的逝什么，有什么解决的方法吗（）

**Comment by WratithCr** [comment]
而且async mob spawning不是默认false嘛（）

**Comment by s-yh-china** [comment]
> 而且async mob spawning不是默认false嘛（）

更换为最新版本试试
~~async mob spawning就算为false也会造成一些影响，我无法彻底关闭这个功能~~
