### ISSUE TITLE
增加InventoryPreview（即容器预览）功能的支持

### ISSUE THREAD

**Issue by Dogtreat** [LeavesMC/Leaves#220]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望能够增加tweakeroo模组中InventoryPreview（即容器预览）功能在客户端能够正常使用的支持，并使此选项在文档中可以选择开关

### 其他 Other

（emm，首当其冲的就是做村民繁殖的时候看不见村民背包里还有多少食物！很烦，所以我要提交这个Issue）

**Comment by s-yh-china** [comment]
不是有pca吗?
至于1.20.6 客户端mod都还没更新呢 我也没办法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月30日(周四) 下午5:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 增加InventoryPreview（即容器预览）功能的支持 (Issue #220)




 
描述你希望添加的功能。 Describe the feature you'd like.
 
希望能够增加tweakeroo模组中InventoryPreview（即容器预览）功能在客户端能够正常使用的支持，并使此选项在文档中可以选择开关
 
其他 Other
 
（emm，首当其冲的就是做村民繁殖的时候看不见村民背包里还有多少食物！很烦，所以我要提交这个Issue）
