### ISSUE TITLE
Jade protocol crashes clients on older version, suggestion is to restrict it to only players with the right protocol version to retrieve the data.

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [LeavesMC/Leaves#225]
### 服务端版本 LeavesMC Version

git-Leaves-"6951bdc"

### 预期的行为 Expected behavior

older clients (such as 1.20.1) should receive the NBT data from Jade, or it shouldn't show anything to avoid crashes

### 观测到的实际行为 Observed/Actual behavior

older clients were logged out because of invalid NBT data or crashes

![image](https://github.com/LeavesMC/Leaves/assets/73286927/44aff3a4-9043-4516-b11e-6d77ef7ec4cf)

### 复现步骤 Steps/models to reproduce

Get ViaVersion and ViaBackwards on your server

Log into the server with Jade

Hover to an entity, or a block entity that supports detailed server-side reporting by Jade. The client will be logged out from the server, or even crash.

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (13):
Bukkit Plugins:
- CustomVersionSeedCommand, DummySB, ExtendedViewDistance, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib, RHLeafDecay, servertick, SimpleHelp, spark
TAB, ViaBackwards, ViaVersion

Those plugins shouldn't interfere with Jade.

### 更多详细信息。 The more information.

A possible fix is to first get the client's real protocol version via an API such as ViaVersion or internally (if we could even get it!?) and compare it with the server's protocol version (Server members should use updated software!). If the check doesn't pass then Jade NBT data should be blocked from being sent to the client.

I already submitted an issue which is related to this one in the past: https://github.com/LeavesMC/Leaves/issues/73

**Comment by GLDYM** [comment]
This crashed is caused by via, not jade. Please use the latest version of via. Old version of via deal the translation between 1.20.1 and 1.20.4 poorly.

**Comment by QuanTrieuPCYT** [comment]
> This crashed is caused by via, not jade. Please use the latest version of via. Old version of via deal the translation between 1.20.1 and 1.20.4 poorly.

I'm already using the latest one on GitHub. This has been existing for months on my end now.

**Comment by s-yh-china** [comment]
you may need to pay attention to #74
we are unlikely to provide additional support for it is just a plugin.
a more feasible solution is to have Jade send version to the server, so that we can provide services based on different version numbers, but in reality, it does not do so.

**Comment by QuanTrieuPCYT** [comment]
> you may need to pay attention to #74 we are unlikely to provide additional support for it is just a plugin. a more feasible solution is to have Jade send version to the server, so that we can provide services based on different version numbers, but in reality, it does not do so.

Alright, thanks for the help!
