### ISSUE TITLE
增加配置选项以恢复1.18.2以前下界要塞中下界砖刷怪游走的行为

### ISSUE THREAD

**Issue by ZnianXgang** [LeavesMC/Leaves#227]
### 描述你希望添加的功能。 Describe the feature you'd like.

增加配置选项，以恢复1.18.2以前下界要塞中下界砖刷怪游走的行为。
详见Fallen_Breath的博客：https://blog.fallenbreath.me/zh-CN/2024/fortress-nether-bricks-pack-spawning-issue-1182/

**Comment by GLDYM** [comment]
请先等待 https://bugs.mojang.com/browse/MC-271630 做出是否修复的决定。

**Comment by ZnianXgang** [comment]
暂时只能等待了，我先关闭这个issue吧
顺便一提，漏洞报告被关了，解决结果变成Awaiting Response，需要进一步补充必要信息

**Comment by ZnianXgang** [comment]
Resolution: Won't Fix

**Comment by s-yh-china** [comment]
好好好mojang

**Comment by LittleChest** [comment]
破坏怪物农场，爱来自Mojang。

**Comment by Bluemangoo** [comment]
wontfix, 爱来自mojang。

**Comment by MC-XiaoHei** [comment]
爱来自mojang

**Comment by MC-XiaoHei** [comment]
或许可以先加上修复？

**Comment by s-yh-china** [comment]
别急 已经在睡觉了Zzzzz

**Comment by MC-XiaoHei** [comment]
@ZnianXgang 麻烦使用最新版Leaves#33（尚未构建完成，需要稍等）进行测试
测试前需要开启`leaves.yml`中`modify.minecraft-old.fix-fortress-mob-spawn`

**Comment by ZnianXgang** [comment]
> @ZnianXgang 麻烦使用最新版Leaves#33（尚未构建完成，需要稍等）进行测试 测试前需要开启`leaves.yml`中`modify.minecraft-old.fix-fortress-mob-spawn`

用Youmiel提交于附件中的存档测试，开启配置后测试出的效率与其在1.18.1测得的效率基本一致

**Comment by MC-XiaoHei** [comment]
> > @ZnianXgang 麻烦使用最新版Leaves#33（尚未构建完成，需要稍等）进行测试 测试前需要开启`leaves.yml`中`modify.minecraft-old.fix-fortress-mob-spawn`
> 
> 用Youmiel在MC-271630中提交的附件存档进行测试，开启配置后测试出的效率与其在1.18.1测得的效率基本一致

也就是说基本上可以认为是修复了对吗？

**Comment by MC-XiaoHei** [comment]
文档那边会后面补上
