### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by xiao-k233** [LeavesMC/Leaves#231]
upstream paper now has published 1.21

**Comment by GLDYM** [comment]
**Paper is still experimental, not stable release. There are so many bugs in Paper now, so please wait.**

---

### For Chinese Users
**不是你们这群人一天天的都不学习吗，这 1.21 才出来没几天催个什么啊？Paper 都还一堆 Bug 在那催来催去，真当开发者都是机器人不需要吃饭睡觉上课考试是吧？**

**Comment by Bluemangoo** [comment]
喵了个咪的。中考考完了吗。

paper还没出稳定版急什么呢。paper还很多patch没合上呢。

~~北辰怎么直接开火了。~~

**Comment by xiao-k233** [comment]
我错了哥，我就问问，那么大恶意干嘛
