### ISSUE TITLE
更新1.21

### ISSUE THREAD

**Issue by xmk2333** [LeavesMC/Leaves#232]
### 描述你希望添加的功能。 Describe the feature you'd like.

更新1.21

### 其他 Other

更新1.21

**Comment by GLDYM** [comment]
**Paper is nog experimenteel. Er zitten veel wormen in. Wachten alstublieft.**
 
**Paper is still experimental, not stable release. There are so many bugs in Paper now, and many patch not build, so please wait.**

---

### For Chinese Users
**我刚骂完一个又来一个是吧？**
**不是你们这群人一天天的都不学习工作吗，这 1.21 才出来没几天催个什么啊？Paper 都还一堆 Bug 在那催来催去，真当开发者都是机器人不需要吃饭睡觉上课考试工作是吧？**

**Comment by Bluemangoo** [comment]
笑烂了。不看上一个issue吗。

**Comment by Bluemangoo** [comment]
北辰你怎么三语言回复了。

**Comment by xmk2333** [comment]
不好意思抱歉抱歉确实没看到，辛苦辛苦

**Comment by LittleChest** [comment]
喜欢
