### ISSUE TITLE
detector rail causes crash

### ISSUE THREAD

**Issue by MShetro** [LeavesMC/Leaves#234]
### 服务端版本 LeavesMC Version

git-Leaves-"e7c14b8" (MC: 1.20.4)

### 预期的行为 Expected behavior

the server should not have crashed

### 观测到的实际行为 Observed/Actual behavior

the server is causing a crash 

### 复现步骤 Steps/models to reproduce

make a cce suppressor and put the detector rail close to the comparator and then step on it

### 插件与数据包列表。 Plugin and Datapack List.

server without plugins and datapacks.

**Comment by s-yh-china** [comment]
make sure update-suppression-crash-fix is true, and try again

**Comment by GLDYM** [comment]
Maybe Saves and latest.log in needed here.
