### ISSUE TITLE
The suppressor can dupe items

### ISSUE THREAD

**Issue by MShetro** [LeavesMC/Leaves#235]
### 服务端版本 LeavesMC Version

git-Leaves-"e7c14b8" (MC: 1.20.4)

### 预期的行为 Expected behavior

The item will not be duplicated

### 观测到的实际行为 Observed/Actual behavior

The item is being duplicated

### 复现步骤 Steps/models to reproduce

make a cce suppressor and put the frame on the comparator and then put the object in the frame
![Screenshot_2024-06-19-16-38-16-449_net kdt pojavlaunch](https://github.com/LeavesMC/Leaves/assets/140889203/0212d382-0660-4939-9227-2e658d91a705)

### 插件与数据包列表。 Plugin and Datapack List.

there are no plugins or datapacks on the server

**Comment by s-yh-china** [comment]
same as vanilla
