### ISSUE TITLE
1.21测试版的端，潜影盒堆叠有问题

### ISSUE THREAD

**Issue by Cobyqwq** [LeavesMC/Leaves#248]
### 服务端版本 LeavesMC Version

1.21-2252-d5c06b4 (MC: 1.21)

### 预期的行为 Expected behavior

正常放入箱子

### 观测到的实际行为 Observed/Actual behavior

堆叠是正常，但是打开箱子选中堆叠的盒子按shift+f盒子直接消失

### 复现步骤 Steps/models to reproduce

打开箱子选中堆叠的盒子按shift+f盒子

### 插件与数据包列表。 Plugin and Datapack List.

无任何插件测试

**Comment by s-yh-china** [comment]
没有客户端mod?

**Comment by Cobyqwq** [comment]
> 没有客户端mod？

原版1.21

**Comment by s-yh-china** [comment]
那你可以试试装上tweakeroo然后打开这个功能，能不能暂时解决这个问题

**Comment by Cobyqwq** [comment]
> 那你可以试试装上tweakeroo然后打开这个功能，能不能暂时解决这个问题

还是一样
服务端配置是   stackable-shulker-boxes: '64'
没问题吧

**Comment by s-yh-china** [comment]
嗯? tweakeroo打开潜影盒堆叠也不行吗

**Comment by Cobyqwq** [comment]
> 嗯? tweakeroo打开潜影盒堆叠也不行吗

嗯

**Comment by Cobyqwq** [comment]
> 嗯? tweakeroo打开潜影盒堆叠也不行吗


Uploading 2024-07-06_21-29-13.mp4…

**Comment by lightouo** [comment]
补个视频，将已堆叠的盒子从背包放入容器时盒子数量会置1

https://github.com/LeavesMC/Leaves/assets/53961803/dc93ec4e-c715-4ac1-91d2-24b060ad5d9f

**Comment by Cobyqwq** [comment]
目前盒子倒是不会直接丢失了，但是在箱子里显示有问题，点击才会显示堆叠，不点击只显示1个
![785d3d37d489ef33026ba1a588dffbc3](https://github.com/LeavesMC/Leaves/assets/51470068/f5581bd0-a57f-4298-89c6-e7d35457fe07)

**Comment by Cobyqwq** [comment]
> 这个问题把tweakeroo的堆叠打开应该就好了 感觉需要客户端配合 纯服务端我还在看(

好的，辛苦

**Comment by s-yh-china** [comment]
我观察了一下，服务端发的包已经是正确的了，但是客户端不显示emmmm
没啥办法，我决定把这个issue先关了(

**Comment by lightouo** [comment]
作者大大，在测试的时候**内容物相同**的潜影盒也**会**被堆叠，虽然这个特性/bug是对玩家有利的，但应该是不正常的吧(
![image](https://github.com/LeavesMC/Leaves/assets/53961803/0e212f07-ed8f-46aa-a7cc-ff73d14cb94a)
