### ISSUE TITLE
默认配置下玩家使用传送门进入维度可以获取维度内假人的坐标

### ISSUE THREAD

**Issue by z7087** [LeavesMC/Leaves#25]
### 服务端版本 LeavesMC Version

git-Leaves-"2abf47e" (MC: 1.19.3)

### 预期的行为 Expected behavior

假人数据不发送到客户端

### 观测到的实际行为 Observed/Actual behavior

![image](https://user-images.githubusercontent.com/75190047/218698628-fbd00499-3415-4bd7-8ade-70aab8c7ea73.png)

### 复现步骤 Steps/models to reproduce

召唤一个假人，然后使用在假人渲染距离外的传送门进入维度，使用装有clientcommands模组的客户端输入/cfind @a，打印出假人的名字和坐标

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://user-images.githubusercontent.com/75190047/218698589-b637fc48-c883-4480-9780-59b9b125f04c.png)

**Comment by s-yh-china** [comment]
事实上这是刻意的 为了方便查看假人位置
这样吧 我会加入一个配置项来控制这个行为

**Comment by s-yh-china** [comment]
> > 事实上这是刻意的 为了方便查看假人位置 这样吧 我会加入一个配置项来控制这个行为
> 
> 假人的数据在不使用模组的客户端应该是不可见的，可以把这个功能移动到/bot list中

谁不装小地图啊(X)
