### ISSUE TITLE
Jade Protocol Error

### ISSUE THREAD

**Issue by GideonWhite1029** [LeavesMC/Leaves#250]
### 服务端版本 LeavesMC Version

Leaves version 1.21-4-master@76eb988 (2024-07-05T09:24:08Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

Unhindered access to the server without any errors

### 观测到的实际行为 Observed/Actual behavior

With Jade Protocol enabled, it does not allow access to the server and issues an error:

![image](https://github.com/LeavesMC/Leaves/assets/71203055/f964cb77-8e7a-4f56-88b6-8e9d56ce37e0)

### 复现步骤 Steps/models to reproduce

1) Set the `jade-protocol` parameter to `true` in `leaves.yml`
2) Log in to the server with the Jade mod

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/LeavesMC/Leaves/assets/71203055/f0b27a38-107e-4c21-81fe-41a65b551541)

### 更多详细信息。 The more information.

The Jade Mod version: `v15.1.0+fabric`

**Comment by s-yh-china** [comment]
thanks and fixed

**Comment by GideonWhite1029** [comment]
![image](https://github.com/LeavesMC/Leaves/assets/71203055/6ed87094-7c81-4dac-9c22-548cc94602d7)
![image](https://github.com/LeavesMC/Leaves/assets/71203055/58bde7d6-425f-41a4-bf51-6bdddaa26fc4)

Now the details of many items (chests, bonfires, hoppers) and mobs (chicken, armadillo) are not displayed
