### ISSUE TITLE
工作台合成时会出现丢出物品的情况

### ISSUE THREAD

**Issue by cnluminous** [LeavesMC/Leaves#253]
### 服务端版本 LeavesMC Version

1.21-7-master@5aa1100 (2024-07-07T16:25:33Z)

### 预期的行为 Expected behavior

正常合成物品进入背包中，而非丢出物品

### 观测到的实际行为 Observed/Actual behavior

合成物品会出现丢出物品的情况，如木板、木棍、梯子等

### 复现步骤 Steps/models to reproduce

https://github.com/LeavesMC/Leaves/assets/47070284/8787df8c-4d43-4c4e-b0d0-94b6c7e0ecad

### 插件与数据包列表。 Plugin and Datapack List.

plugins:无

datapack:[vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

**Comment by cnluminous** [comment]
客户端无mod，为原版客户端

**Comment by MC-XiaoHei** [comment]
已经验证。

**Comment by MC-XiaoHei** [comment]
经过测试，
和村民交易的时候，shift click也会出问题
具体情况就是交易换到的物品，原来背包里有a个格子，交易完之后背包里有b个格子，那么交易得到物品就会少3（b-a）个
直接就被吞，没有了
test by kumei

**Comment by MC-XiaoHei** [comment]
修好了，但是可堆叠潜影盒炸了。后面再修吧
