### ISSUE TITLE
1.21版本：掉落物通过地狱门不会生成新的地狱门

### ISSUE THREAD

**Issue by Twor** [LeavesMC/Leaves#254]
### 服务端版本 LeavesMC Version

Leaves version 1.21-8-master@eb7eadd

### 预期的行为 Expected behavior

让掉落物通过地狱门时生成新的地狱门，和原版一样

### 观测到的实际行为 Observed/Actual behavior

掉落通过地狱门不会生成新的地狱门

### 复现步骤 Steps/models to reproduce

掉落通过地狱门不会生成新的地狱门

### 插件与数据包列表。 Plugin and Datapack List.

无

**Comment by Flock-YT** [comment]
这个似乎是上游的Paper干的

**Comment by s-yh-china** [comment]
为什么我测试的时候不能复现 奇怪

**Comment by MC-XiaoHei** [comment]
如果有可复现麻烦提供下视频 谢谢
