### ISSUE TITLE
关于潜影盒堆叠错误的问题

### ISSUE THREAD

**Issue by Flock-YT** [LeavesMC/Leaves#257]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21-13-master@270eaaa (2024-07-13T04:00:43Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-7-5aa1100 (MC: 1.21)

### 预期的行为 Expected behavior

潜影盒为空时可以被堆叠  , 但是如果潜影盒中有物品时应该不能被堆叠

### 观测到的实际行为 Observed/Actual behavior

当潜影盒中的物品完全相同时依然可以堆叠

### 复现步骤 Steps/models to reproduce

![image](https://github.com/user-attachments/assets/08861d51-00d4-408d-a2f6-821ae461f21a)

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/user-attachments/assets/ca0f5df2-afe0-4cbc-8f58-ecdcde30ca2b)
![image](https://github.com/user-attachments/assets/7e4eb403-26a7-456d-8978-239d323453e3)

**Comment by MC-XiaoHei** [comment]
有没有开启潜影盒堆叠那个配置？

**Comment by Flock-YT** [comment]
有开启堆叠,我就是来反馈这个堆叠有问题的, 盒子中的物品如果完全一样就可以被堆叠.
![image](https://github.com/user-attachments/assets/395ec3e9-33af-4ebb-b257-a885cbeb69c4)

**Comment by Bluemangoo** [comment]
- Duplicated of #248

姐姐！

**Comment by Flock-YT** [comment]
> * Duplicated of [1.21测试版的端，潜影盒堆叠有问题 #248](https://github.com/LeavesMC/Leaves/issues/248)
> 
> 姐姐！

我也看到这个了,但是因为他是在issue已经close后才发出来的,所以我就单独开了个新的.

**Comment by Flock-YT** [comment]
问题似乎依然存在,虽然在箱子内不会显示但是实际上依然可以堆叠,拿起来就会显示堆叠数量.
![image](https://github.com/user-attachments/assets/394b7d46-1324-40df-8256-b5582308d1af)
![image](https://github.com/user-attachments/assets/67259f10-e952-4014-8a33-70b8954ac81a)
![image](https://github.com/user-attachments/assets/1adfd5bc-e49d-4778-92c6-07c6894950f9)
版本信息:
```
This server is running Leaves version 1.21-19-master@fd5e8be (2024-07-22T06:41:37Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-13-270eaaa (MC: 1.21)

```

**Comment by s-yh-china** [comment]
这个没啥办法 感觉是只能是加客户端mod了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月22日(周一) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 关于潜影盒堆叠错误的问题 (Issue #257)




 
问题似乎依然存在,虽然在箱子内不会显示但是实际上依然可以堆叠,拿起来就会显示堆叠数量.
 image.png (view on web)
 image.png (view on web)
 image.png (view on web)
 版本信息:
 This server is running Leaves version ***@***.*** (2024-07-22T06:41:37Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-13-270eaaa (MC: 1.21)

**Comment by Flock-YT** [comment]
客户端有安装Tweakerooo 不过是[Sakura](https://github.com/sakura-ryoko/tweakeroo)编译的版本,因为官方版本没有更新到1.21,在开启堆叠的情况下,依旧会出现这个问题,并且原版纯净端什么都不装也会出现这个问题.
![image](https://github.com/user-attachments/assets/8db64d3b-a01d-4a31-bdc4-f05abe89a3b5)

**Comment by s-yh-china** [comment]
> 客户端有安装Tweakerooo 不过是[Sakura](https://github.com/sakura-ryoko/tweakeroo)编译的版本,因为官方版本没有更新到1.21,在开启堆叠的情况下,依旧会出现这个问题,并且原版纯净端什么都不装也会出现这个问题. ![image](https://private-user-images.githubusercontent.com/109157284/350894884-8db64d3b-a01d-4a31-bdc4-f05abe89a3b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDA2NzcsIm5iZiI6MTcyMTY0MDM3NywicGF0aCI6Ii8xMDkxNTcyODQvMzUwODk0ODg0LThkYjY0ZDNiLWEwMWQtNGEzMS1iZGM0LWYwNWFiZTg5YTNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwOTI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmI0ZDZmN2MxYWIxOGJlZmFhZWZkOWJlN2VkZTQ1NWMwNDAwODUxMDFjY2M5NzllNzJkODEyOTI3MGU2ZmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3GB_WERmc8cfp43mUyvJv7pzfXWsFarGlXwaqCUQNrE)

啊?我这边是正常的啊

**Comment by Flock-YT** [comment]
刚刚测试了一下,疑似弄反了,现在的情况是空盒子不能堆叠,盒子里面有相同物品的可以堆叠了.

**Comment by s-yh-china** [comment]
哦草 对不起

**Comment by s-yh-china** [comment]
这次绝对修好了，让我先关了

**Comment by Flock-YT** [comment]
经过测试,目前潜影盒问题已经被完全修复,在箱子内的堆叠数量显示也正常了,感谢!
