### ISSUE TITLE
屠龙炮无法使用

### ISSUE THREAD

**Issue by kingc2022** [LeavesMC/Leaves#259]
### 描述你希望添加的功能。 Describe the feature you'd like.

可以使用屠龙炮。

### 其他 Other

由于 PaperMC 修复了这一特性，希望 Leaves 回滚这次更改。
[修复特性的 PR](https://github.com/PaperMC/Paper/pull/9611)

**Comment by MC-XiaoHei** [comment]
这个实现起来不难，但是可能只会在1.21进行修改，换而言之，旧版本（1.20.4,1.20.6）可能无法获得此修复

**Comment by Bluemangoo** [comment]
你要现在修吗。你不修我来。

**Comment by MC-XiaoHei** [comment]
> 你要现在修吗。你不修我来。

你来吧

**Comment by s-yh-china** [comment]
你来 我先睡觉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月19日(周五) 下午2:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 屠龙炮无法使用 (Issue #259)




 
你要现在修吗。你不修我来。

**Comment by Bluemangoo** [comment]
旧版本需要自己打patch。把文件复制进去丢给action就行了。

**Comment by Bluemangoo** [comment]
@kingc2022 试下pr那个能不能用。在action里面。
