### ISSUE TITLE
假人驻留未能正常工作

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#26]
### 服务端版本 LeavesMC Version

git-Leaves-"7161b8d"

### 预期的行为 Expected behavior

重启服务器后假人理应在原位置。

### 观测到的实际行为 Observed/Actual behavior

重启服务器后服务器崩溃，再重启后假人消失。

### 复现步骤 Steps/models to reproduce

1.在配置文件中开启假人驻留的设置后开启服务器
2.一个玩家进入服务器，并召唤一个假人
3.关闭服务器后再次启动服务器
4.服务器崩溃并输出崩溃报告
5.再次启动服务器，能正常启动，而假人消失

### 插件与数据包列表。 Plugin and Datapack List.

Plugins: Essentials, EssentialsChat, EssentialsSpawn
No datapacks.

### 更多详细信息。 The more information.

[crash-2023-03-10_21.48.15-server.txt](https://github.com/LeavesMC/Leaves/files/10942718/crash-2023-03-10_21.48.15-server.txt)

**Comment by s-yh-china** [comment]
检查了一下 看起来是我意外的混用了nms和bukkit的纬度名导致的

**Comment by s-yh-china** [comment]
待验证

**Comment by GLDYM** [comment]
现在似乎可以正常工作了
