### ISSUE TITLE
[Vote] Remove most optimizations from Leaves

### ISSUE THREAD

**Issue by s-yh-china** [LeavesMC/Leaves#262]
In the early stages of 'leaves', we added certain optimizations. As of today, these optimizations may benefit the server-side, but they have significantly slowed down our development process.
Now, I propose to remove most of the optimizations in 'leaves', leaving only necessary, significant and non-intrusive ones. If removed, the optimized part might become an independent 'Leaves fork'.
This is a vote, not an announcement, you can voice your opinion through emoticons or leave a comment below.

Chinese version:
在早期的leaves中，我们曾加入了一定的优化。时至今日，这些优化可能对服务端有益处，但这大大拖慢了我们开发的进程。
在现在，我提出移除leaves中的大部分优化，只留下一些必要的，效果显著的，且不影响原版的。如果移除，优化的部分可能会成为一个单独的 Leaves fork 而存在。
这是一个投票，而不是一个公告，你可以使用表情符号发表你的意见，或者在下方留言。

**Comment by lilingfengdev** [comment]
This is a great decision.

Most users of Leaves don't care about performance, they are looking for stock features and module support, ditching the performance optimisation patches will allow Leaves to focus on features and module support.

(and Leaf) 😄

**Comment by Lumine1909** [comment]
FOCUS ON FEATURES!

**Comment by Lu-Mine** [comment]
非常支持。这大大减小了新服务端配置负担。
Much in favor of this! This greatly reduces the burden of configuring a new server.

_“开箱即用”正是 Leaves 核心所追求的。
Out of the box = exactly what Leaves is all about, isn't it?_

**Comment by CerealAxis** [comment]
Good

**Comment by Lumine1909** [comment]
> 非常支持。这大大减小了新服务端配置负担。 Much in favor of this! This greatly reduces the burden of configuring a new server.
> 
> _“开箱即用”正是 Leaves 核心所追求的。 Out of the box = exactly what Leaves is all about, isn't it?_

good user id (

**Comment by theLIKImk** [comment]
支持
.....怎么说呢，其实由于原版服务端是单核服务器，不管再怎么优化上线都是那样了（CPU-Z单核心670分的运行MC的情况都不是很理想）。
要更多优化只能期待......多线程服务端吧。

**Comment by Lu-Mine** [comment]
> 支持 .....怎么说呢，其实由于原版服务端是单核服务器，不管再怎么优化上线都是那样了（CPU-Z单核心670分的运行MC的情况都不是很理想）。 要更多优化只能期待......多线程服务端吧。

期待(Expect) Lumina.

**Comment by xiao-k233** [comment]
从Leaf里偷一些效果最显著的patch来？
例如AVX支持？

**Comment by s-yh-china** [comment]
> 从Leaf里偷一些效果最显著的patch来？ 例如AVX支持？

~~读书人的事，能叫偷吗~~

**Comment by Bluemangoo** [comment]
> 支持 .....怎么说呢，其实由于原版服务端是单核服务器，不管再怎么优化上线都是那样了（CPU-Z单核心670分的运行MC的情况都不是很理想）。 要更多优化只能期待......多线程服务端吧。

有没有优化差别相当大。

**Comment by LittleChest** [comment]
> 从Leaf里偷一些效果最显著的patch来？ 例如AVX支持？

我们的开发重点不在优化，而且这仍然会拖慢开发速度。

**Comment by Bluemangoo** [comment]
> 从Leaf里偷一些效果最显著的patch来？ 例如AVX支持？

今天的 update paper 应该让你来。

**Comment by xiao-k233** [comment]
别骂了别骂了



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 19, 2024 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LeavesMC/Leaves] [Vote] Remove most optimizations from Leaves(Issue #262)




  
从Leaf里偷一些效果最显著的patch来？ 例如AVX支持？
  
今天的 update paper 应该让你来。

**Comment by xiao-k233** [comment]
但是生电确是最吃优化的



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 19, 2024 22:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LeavesMC/Leaves] [Vote] Remove most optimizations from Leaves(Issue #262)




  
从Leaf里偷一些效果最显著的patch来？ 例如AVX支持？
  
我们的开发重点不在优化，而且这仍然会拖慢开发速度。

**Comment by LrbsX** [comment]
那扔掉不显著的优化会跟原先paper的性能差的大么🤔

**Comment by MC-XiaoHei** [comment]
> 那扔掉不显著的优化会跟原先paper的性能差的大么🤔

这要看你怎么定义 差的大

实际上在我看来leaves的性能从来都不是一个很好的卖点（诋毁

**Comment by s-yh-china** [comment]
> 那扔掉不显著的优化会跟原先paper的性能差的大么🤔

怎么都是基于paper 我觉得应该不会?

**Comment by MC-XiaoHei** [comment]
> > 那扔掉不显著的优化会跟原先paper的性能差的大么🤔
> 
> 怎么都是基于paper 我觉得应该不会?

 我感觉leaves有一些功能具有未知的破坏性能的作用（

毕竟现在看起来leaves确实性能比paper差

**Comment by Bluemangoo** [comment]
我们把一些大幅优化（破坏）的patch还原了。当然性能会下降。

**Comment by s-yh-china** [comment]
很明显大家都不反对，我们即将执行(笑)

**Comment by xiao-k233** [comment]
我反对[doge]把一些最好的补丁拿过来，能打就打，不能打算了，等别人维护好了再合

**Comment by LittleChest** [comment]
> 我反对[doge]把一些最好的补丁拿过来，能打就打，不能打算了，等别人维护好了再合

你自己fork一个 想合什么合什么

**Comment by Mooling0602** [comment]
> 优化的部分可能会成为一个单独的 Leaves fork 而存在
只是“可能”，也就是说有概率后面这些优化都有概率在新版本消失，因此我反对，另外关闭 issue 的速度不要太快了吧）
至于说 Folia 那种类型的服务端，我个人而言暂不会考虑，因为多线程的服务端要兼容现有的插件生态或许还需要较长的时间。

**Comment by s-yh-china** [comment]
> > 优化的部分可能会成为一个单独的 Leaves fork 而存在
> 
> 只是“可能”，也就是说有概率后面这些优化都有概率在新版本消失，因此我反对，另外关闭 issue 的速度不要太快了吧） 至于说 Folia 那种类型的服务端，我个人而言暂不会考虑，因为多线程的服务端要兼容现有的插件生态或许还需要较长的时间。

因为确实没人提出反对(

**Comment by Mooling0602** [comment]
> > > 优化的部分可能会成为一个单独的 Leaves fork 而存在
> > 
> > 
> > 只是“可能”，也就是说有概率后面这些优化都有概率在新版本消失，因此我反对，另外关闭 issue 的速度不要太快了吧） 至于说 Folia 那种类型的服务端，我个人而言暂不会考虑，因为多线程的服务端要兼容现有的插件生态或许还需要较长的时间。
> 
> 因为确实没人提出反对(

异议！

**Comment by s-yh-china** [comment]
那我们再开几天(

**Comment by MC-XiaoHei** [comment]
> 我反对[doge]把一些最好的补丁拿过来，能打就打，不能打算了，等别人维护好了再合

那你来写。

**Comment by MC-XiaoHei** [comment]
> Reference in n

上面有emoji投票

**Comment by mc506lw** [comment]
So cool！It was a great decision ahead of time！

**Comment by MC-XiaoHei** [comment]
> So cool！It was a great decision ahead of time！

also see https://github.com/LeavesMC/Lumina/discussions/16 plz XD

**Comment by yxc0915** [comment]
对于我来说，只要能够满足生电需求就行（）ps:我用leaves开个小型生电服tps都只有10几，给我整不会了（CPU是13900）🌚🌚🌚

**Comment by LittleChest** [comment]
> 对于我来说，只要能够满足生电需求就行（）ps:我用leaves开个小型生电服tps都只有10几，给我整不会了（CPU是13900）🌚🌚🌚

尝试使用11/12代英特尔CPU，13代英特尔CPU有质量问题

**Comment by Bluemangoo** [comment]
> > 对于我来说，只要能够满足生电需求就行（）ps:我用leaves开个小型生电服tps都只有10几，给我整不会了（CPU是13900）🌚🌚🌚
> 
> 尝试使用11/12代英特尔CPU，13代英特尔CPU有质量问题

最新intel回复包赔。

**Comment by RAURORA2** [comment]
让我想到了一个端https://github.com/Winds-Studio/Leaf，就像是优化集合的分支

**Comment by MC-XiaoHei** [comment]
> 让我想到了一个端 https://github.com/Winds-Studio/Leaf 它就像是paper优化集合的分支

leaf开发者和我们很熟（x

**Comment by qyl27** [comment]
LGTM, I would vanilla features rather than optimizations.

**Comment by s-yh-china** [comment]
我们注意到，并没有那么多用户支持保留优化，因此我们即将开始进行此issue
