### ISSUE TITLE
[Feature]Will we consider supporting 1.18.2 in the future？ | 未来是否会支持1.18.2？

### ISSUE THREAD

**Issue by Shanshui2024** [LeavesMC/Leaves#267]
### 描述你希望添加的功能。 Describe the feature you'd like.

我挺希望Leaves支持1.18.2的，因为鄙人的服务器就是1.18.2，然后还想装个I See You，结果这东西需要Leaves支持（
I really hope that Leaves can support 1.18.2, because my server is 1.18.2, and when I want to install 'I See You', which requires Leaves' support（

**Comment by Bluemangoo** [comment]
加钱考虑一下😋

**Comment by s-yh-china** [comment]
我们正在考虑对版本提供付费的长期支持，但这只在计划中，如果有需要的人有一定数量的话。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月21日(周日) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [LeavesMC/Leaves] [Feature]Will we consider supporting 1.18.2 in the future？ | 未来是否会支持1.18.2？ (Issue #267)




 
加钱考虑一下😋
