### ISSUE TITLE
也许我们应该修改默认生电配置来支持伪和平

### ISSUE THREAD

**Issue by sunshinezxq** [LeavesMC/Leaves#268]
### 服务端版本 LeavesMC Version

Leaves version 1.21-8-master@eb7eadd

### 预期的行为 Expected behavior

在占满生物上限后生物不再刷新

### 观测到的实际行为 Observed/Actual behavior

生物上限占满后依然刷新

### 复现步骤 Steps/models to reproduce

使用默认配置，用坚守者，凋灵，僵尸村民等占满刷怪上限（玩家x70),发现依然生成怪物

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (0):
There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### 更多详细信息。 The more information.

修改位于config文件夹下的paper-world-defaults.yml的count-all-mobs-for-spawning为true
per-player-mob-spawns为false

**Comment by Bluemangoo** [comment]
你能不能不要新开一个issue啊。

**Comment by Bluemangoo** [comment]
- Duplicated of #265
