### ISSUE TITLE
假人定时移除

### ISSUE THREAD

**Issue by Bluemangoo** [LeavesMC/Leaves#273]
### 描述你希望添加的功能。 Describe the feature you'd like.

如题

### 其他 Other

我会做的。

**Comment by Lumine1909** [comment]
这个功能可以下放到插件吧 现有的api足够了（

**Comment by Bluemangoo** [comment]
我指的是 `/bot remove [hour [min [second]]]`

**Comment by MC-XiaoHei** [comment]
> 我指的是 `/bot remove <bot> [hour [min [second]]]`

应该可以覆盖命令（？
不过你要做也行

**Comment by Bluemangoo** [comment]
不可以覆盖子命令，只能覆盖整个bot命令。

**Comment by MC-XiaoHei** [comment]
> 不可以覆盖子命令，只能覆盖整个bot命令。

只需要判断下args数量，少于2就直接执行原本的（x

**Comment by MC-XiaoHei** [comment]
不过确实可以塞进服务端

**Comment by Bluemangoo** [comment]
还有其它命令的。这是个很小的方便改动。
