### ISSUE TITLE
Extremely low mob spawn rate 

### ISSUE THREAD

**Issue by DINNKA** [LeavesMC/Leaves#28]
### 服务端版本 LeavesMC Version

Leaves-1.19.4 74e4680

### 预期的行为 Expected behavior

Better server performance 

### 观测到的实际行为 Observed/Actual behavior

0 mob spawn

### 复现步骤 Steps/models to reproduce

.

### 插件与数据包列表。 Plugin and Datapack List.

.

### 更多详细信息。 The more information.

I switched from Purpur to Leaves and enabled some qol settings in the default config. Idk why but mob spawn rate is almost gone on the server.

**Comment by s-yh-china** [comment]
can provide your leaves.yml file?

**Comment by GLDYM** [comment]
似乎在长时间运行服务器后生物生成会逐渐变慢，最终变为0生成，重启服务器后恢复正常。
但是我手头没有空余服务器，很难测试这个问题能否于paper复现（
  performance:
    remove:
      get-nearby-players-streams: true
      tick-guard-lambda: true
      inventory-contains-iterators: true
      range-check-streams-and-iterators: true
    optimize-chunk-ticking: true
    enable-suffocation-optimization: true
    reduce-entity-fluid-lookup: true
    cache-climb-check: true
    strip-raytracing-for-entity: true
    improve-fluid-direction-caching: true
    inactive-goal-selector-disable: false
    check-spooky-season-once-an-hour: true
    fix:
      fix-paper-6045: true
    reduce-chuck-load-and-lookup: true
    skip-clone-loot-parameters: true
    biome-temperatures-use-aging-cache: true
    entity-target-find-optimization: true
    async-mob-spawning: true
    dont-send-useless-entity-packets: true
    async-entity-tracker: false
    optimize-entity-coordinate-key: true
    skip-poi-find-in-vehicle: true
    use-more-thread-unsafe-random: true
    reduce-entity-allocations: true
    async-pathfinding: false
    simpler-vanilla-shapeless-recipes: true
  modify:
    bedrock-break-list: false
    fix-update-suppression-crash: true
    use-vanilla-random: true
    instant-block-updater-reintroduced: false
    return-nether-portal-fix: false
    flatten-triangular-distribution: true
    player-can-edit-sign: true
    budding-amethyst-can-push-by-piston: false
    fakeplayer:
      open-fakeplayer-inventory: true
      prefix: ''
      suffix: ''
      enable: true
      unable-fakeplayer-names: []
      limit: 10
      always-send-data: true
      resident-fakeplayer: true
    mc-technical-survival-mode: true
    redstone-shears-wrench: true
    player-operation-limiter: false
    renewable-elytra: -1.0
    snowball-and-egg-can-knockback-player: true
    shears-in-dispenser-can-zero-amount: false
    spectator-dont-get-advancement: false
    stackable-shulker-boxes: 'false'
    stick-change-armorstand-arm-status: true

**Comment by rePubl1sh** [comment]
bing republish

**Comment by s-yh-china** [comment]
> 似乎在长时间运行服务器后生物生成会逐渐变慢，最终变为0生成，重启服务器后恢复正常。 但是我手头没有空余服务器，很难测试这个问题能否于paper复现（ performance: remove: get-nearby-players-streams: true tick-guard-lambda: true inventory-contains-iterators: true range-check-streams-and-iterators: true optimize-chunk-ticking: true enable-suffocation-optimization: true reduce-entity-fluid-lookup: true cache-climb-check: true strip-raytracing-for-entity: true improve-fluid-direction-caching: true inactive-goal-selector-disable: false check-spooky-season-once-an-hour: true fix: fix-paper-6045: true reduce-chuck-load-and-lookup: true skip-clone-loot-parameters: true biome-temperatures-use-aging-cache: true entity-target-find-optimization: true async-mob-spawning: true dont-send-useless-entity-packets: true async-entity-tracker: false optimize-entity-coordinate-key: true skip-poi-find-in-vehicle: true use-more-thread-unsafe-random: true reduce-entity-allocations: true async-pathfinding: false simpler-vanilla-shapeless-recipes: true modify: bedrock-break-list: false fix-update-suppression-crash: true use-vanilla-random: true instant-block-updater-reintroduced: false return-nether-portal-fix: false flatten-triangular-distribution: true player-can-edit-sign: true budding-amethyst-can-push-by-piston: false fakeplayer: open-fakeplayer-inventory: true prefix: '' suffix: '' enable: true unable-fakeplayer-names: [] limit: 10 always-send-data: true resident-fakeplayer: true mc-technical-survival-mode: true redstone-shears-wrench: true player-operation-limiter: false renewable-elytra: -1.0 snowball-and-egg-can-knockback-player: true shears-in-dispenser-can-zero-amount: false spectator-dont-get-advancement: false stackable-shulker-boxes: 'false' stick-change-armorstand-arm-status: true

不太清楚问题到底出在哪里 我自己的服务器无法复现这个问题 
可能我应该暂时删除异步生物生成

**Comment by s-yh-china** [comment]
may fix
