### ISSUE TITLE
[Enchancement] 剪刀旋转合成器

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#281]
### 描述你希望添加的功能。 Describe the feature you'd like.

开启 redstone-shears-wrench 后，剪刀可以用于旋转合成器。

### 其他 Other

不同于其他红石元件的 facing blockstate，合成器使用 orientation blockstate，因为其具有两个方向。

**Comment by Lumine1909** [comment]
这个是不是也可以下放到插件（
