### ISSUE TITLE
leaves也可以有坚韧玫瑰

### ISSUE THREAD

**Issue by sunshinezxq** [LeavesMC/Leaves#282]
### 描述你希望添加的功能。 Describe the feature you'd like.

增加一个配置来允许凋灵玫瑰种植在稀奇古怪的地方(地狱砖等)

### 其他 Other

(再也不用开更新抑制了)

**Comment by Lumine1909** [comment]
这个可以用很简单的插件实现 监听PlayerInteractEvent事件处理即可
没有必要放到服务端

**Comment by MC-XiaoHei** [comment]
> 这个可以用很简单的插件实现 监听PlayerInteractEvent事件处理即可
> 没有必要放到服务端

没法不触发更新吧。

**Comment by Lumine1909** [comment]
测试:

放置前
![image](https://github.com/user-attachments/assets/02b963de-a3f7-4631-9312-7be0cab1e0a6)

放置后
![image](https://github.com/user-attachments/assets/827280c5-3035-4fb1-ba51-7c9444da7a02)


核心代码: 
```java
    @EventHandler
    public void onInteract(PlayerInteractEvent e) {
        if (e.getAction() == Action.RIGHT_CLICK_BLOCK
                && e.getBlockFace() == BlockFace.UP
                && e.getItem().getType() == Material.WITHER_ROSE) {
            e.getClickedBlock().getLocation().add(0, 1, 0).getBlock().setType(Material.WITHER_ROSE, false);
        }
    }
```

就算bkapi没有提供也可以用nms，要相信插件的能力qwq（确信

**Comment by s-yh-china** [comment]
应用重力和更新是两个东西(敲敲

**Comment by Lumine1909** [comment]
> 应用重力和更新是两个东西(敲敲

可以给个测试更新的方法吗？

**Comment by Lumine1909** [comment]
![image](https://github.com/user-attachments/assets/0f2971cf-2f99-4f49-acc7-97cf38da48a1)

放一起.jpg

**Comment by MC-XiaoHei** [comment]
交给插件吧
