### ISSUE TITLE
(局部)关闭光照更新

### ISSUE THREAD

**Issue by LittleChest** [LeavesMC/Leaves#283]
### 描述你希望添加的功能。 Describe the feature you'd like.

通过配置文件或命令（局部）关闭光照更新 或提供一个配置关闭某个世界/全部光照更新

**Comment by Bluemangoo** [comment]
不太vanilla。

**Comment by LittleChest** [comment]
> 不太vanilla。

生电的一部分（

**Comment by Bluemangoo** [comment]
生电靠光照抑制器的。看着像偷懒。

**Comment by MC-XiaoHei** [comment]
> ### 描述你希望添加的功能。 Describe the feature you'd like.
> 
> 通过配置文件或命令（局部）关闭光照更新 或提供一个配置关闭某个世界/全部光照更新
> 
> ### 其他 Other
> 
> _No response_

意义是啥（

**Comment by MC-XiaoHei** [comment]
光照抑制和没有光照更新不是一个东西吧

**Comment by LittleChest** [comment]
> 光照抑制和没有光照更新不是一个东西吧

可以优化一部分不需要光照的服务器性能（？

**Comment by Bluemangoo** [comment]
我不支持。

**Comment by LittleChest** [comment]
> 我不支持。

好
