### ISSUE TITLE
希望更新配置说明文档Hope to update the configuration documentation

### ISSUE THREAD

**Issue by wangbohan090709081** [LeavesMC/Leaves#287]
### 描述你希望添加的功能。 Describe the feature you'd like.

CN
你好 leaves开发者 我是一名腐竹
这是leaves的说明文档 他是来自清朝的吗，那么老旧，上次更新还是在3月份，一些移除的功能没有说明，一些增加的功能也没有说明
例如
附魔堆叠 贴钻不昂贵累的
![Screenshot_2024-08-02-15-14-00-269_com microsoft emmx](https://github.com/user-attachments/assets/a214ab51-f995-41cd-9dec-d3de1b120f02)
上图显示的是文档的截图，还是今年三月份的

EN
hi, leaves developers I'm a server owner
It's the help documentations It's come from Qing Dynsty? That's too old ,the latest update it's on March this year 
Some removed and some added not tell us
for example
enchament stacking Mending&infinite on the bow
are removed ，it's on the march this year
that's the screenshot
Thank you
Pardon me the Bad English

### 其他 Other

Don't put the Qing Dynsty documents on the website

**Comment by s-yh-china** [comment]
确实是清朝文档 @LittleChest

**Comment by GLDYM** [comment]
srds，这个配置文件文档是脚本，所以你看到的更新时间是源代码的更新时间（）
实际上上次更新文档的时间是7月7号（）

**Comment by MC-XiaoHei** [comment]
需要at白磷了，

**Comment by LittleChest** [comment]
> 确实是清朝文档 @LittleChest

巧了 我也是这么认为的

**Comment by LittleChest** [comment]
> 这是leaves的说明文档 他是来自清朝的吗，那么老旧，一些移除的功能没有说明，一些增加的功能也没有说明 例如 附魔堆叠 贴钻不昂贵累的

这是Documentation存储库的问题 与Leaves无关 请前往对应存储库提交issue

> 上次更新还是在3月份

这是一个错误 抱歉

**Comment by WhitePhosphor** [comment]
在想我的事😋？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月02日 16:59 |
| 收件人 | LeavesMC/Leaves ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [LeavesMC/Leaves] 希望更新配置说明文档Hope to update the configuration documentation (Issue #287) |

这是leaves的说明文档 他是来自清朝的吗，那么老旧，一些移除的功能没有说明，一些增加的功能也没有说明 例如 附魔堆叠 贴钻不昂贵累的

这是Documentation存储库的问题 与Leaves无关 请前往对应存储库提交issue

上次更新还是在3月份

这是一个错误 抱歉
