### ISSUE TITLE
假人无法攻击同一格内的盔甲架并且触发横扫

### ISSUE THREAD

**Issue by Bluemangoo** [LeavesMC/Leaves#288]
### 服务端版本 LeavesMC Version

1.21-37

### 预期的行为 Expected behavior

如题

### 观测到的实际行为 Observed/Actual behavior

如题

### 复现步骤 Steps/models to reproduce

找一个堆肥桶把假人头朝下和盔甲架一起装进去并且给一把横扫III的剑，找几个工具生物放在边上，使用attack命令，发现没有触发横扫

### 插件与数据包列表。 Plugin and Datapack List.

none

### 更多详细信息。 The more information.

姐姐！

**Comment by s-yh-china** [comment]
fakenews
