### ISSUE TITLE
自带的Yggdrasil API无法通过验证，使用MultiYggdrasil和YggdrasilOfficialProxy均可通过验证

### ISSUE THREAD

**Issue by Daodanfd5** [LeavesMC/Leaves#290]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21-39-master@a7b7a1a (2024-08-03T04:53:19Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-37-ec274f5 (MC: 1.21)

### 预期的行为 Expected behavior

预期身份验证应当均可使用，可以同时容纳来自官方和第三方Yggdrasil API的玩家并正确区分uuid。

### 观测到的实际行为 Observed/Actual behavior

然而目前只能使用官方账号登录，不论是否配置第三方Yggdrasil API均如此使用同一客户端的同一token的会话会显示（用户名已打码，仅含数字与小写英文字母）
[20:01:00 INFO]: Disconnecting 1*****d (/127.0.0.1:9491): 身份验证服务器目前处于宕机状态。请稍后再试，抱歉！
[20:01:00 ERROR]: Couldn't verify username because servers are unavailable
[20:01:00 INFO]: 1*****d (/127.0.0.1:9491) lost connection: 身份验证服务器目前处于宕机状态。请稍后再试，抱歉！

在使用https://github.com/YuxuanZuo/MultiYggdrasil 时可以进入服务器并验证成功，uuid等均无问题。

### 复现步骤 Steps/models to reproduce

在leaves.yml中配置如下第三方Yggdrasil API Server
```yaml
extra-yggdrasil-service:
      enable: true
      login-protect: true
      urls:
      - https://skin.mcyou.cn/api/yggdrasil
```
通过在启动命令中额外附加如下jvm参数(并复原leaves.yml的配置)
```
-javaagent:MultiYggdrasil-0.3.0-all.jar=https://skin.mcyou.cn/api/yggdrasil
-Dmultiyggdrasil.mojangYggdrasilService=enabled
-Dmultiyggdrasil.priorityVerifyingCustomName
-Dmultiyggdrasil.noNamespaceSuffix
-Dauthlibinjector.profileKey=enabled
```
配置了MultiYggdrasil后，来自两个Yggdrasil API服务器的验证均正常工作

### 插件与数据包列表。 Plugin and Datapack List.

Bukkit Plugins:
BlueMap, Chunky, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, Geyser-Spigot, LuckPerms, mcMMO, MiniMOTD TabTPS, Vault, ViaBackwards, ViaVersion, WorldEdit

已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]

### 更多详细信息。 The more information.

Blessing Skin版本：6.0.2
皮肤站插件Yggdrasil API版本：5.2.1

**Comment by Daodanfd5** [comment]
补充信息：在1.20.6上的leaves将login protect设为false后，使用littleskin.cn亦无法连接，同样显示验证失败
服务器配置了http proxy，https proxy和socks proxy，不知是否与此有关，proxy均可正常连接，在multiyggdrasil的启动参数中配置的proxy已被隐藏（实际是启用了，但是没有放在issue中）

**Comment by s-yh-china** [comment]
不太好测试...
我找时间看看的

**Comment by Daodanfd5** [comment]
好的，还是希望尽量修复，不过现在替代性的暂行解决方案YggdrasilOfficialProxy看起来实现不如leaves内置的这个优雅（笑

内置的可以多加一点点配置项吗（笑
比如优先使用哪一个验证服务器，获取皮肤后缀来源等等

**Comment by MC-XiaoHei** [comment]
感觉可以提出来，leaves提供对应api，然后用插件实现，更灵活一些
