### ISSUE TITLE
假人刷物品BUG

### ISSUE THREAD

**Issue by Flock-YT** [LeavesMC/Leaves#294]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21-40-master@cd53d4c (2024-08-04T13:37:57Z) (Implementing API version 1.21-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21-34-e6ca163 (MC: 1.21)

### 预期的行为 Expected behavior

把物品放入假人背包后将假人击杀应当只掉落和原来一样数量的物品.

### 观测到的实际行为 Observed/Actual behavior

把物品放入假人背包后将假人击杀即可掉落双倍物品,如果是使用/bot remove指令的话就不会出现此BUG.

### 复现步骤 Steps/models to reproduce

召唤一个假人,往背包里放入物品,杀掉假人,即可复现.

### 插件与数据包列表。 Plugin and Datapack List.

无插件纯净端测试.

**Comment by Flock-YT** [comment]
初步推测是在修复 #291 的时候逻辑有问题,导致了击杀假人的时候执行了两次物品掉落,在此版本之前并无此BUG.

**Comment by s-yh-china** [comment]
唉，我知道了，wait a minute

**Comment by LittleChest** [comment]
严重问题请优先使用 [Report a vulnerability](https://github.com/LeavesMC/Leaves/security/advisories/new)，谢谢喵

**Comment by Flock-YT** [comment]
> 严重问题请优先使用 [Report a vulnerability](https://github.com/LeavesMC/Leaves/security/advisories/new)，谢谢喵

OK,下次我注意

**Comment by Lumine1909** [comment]
@Lumine1909 不测试导致的（指指点点
