### ISSUE TITLE
使用假人api创建的假人当realname和name不一致时重启服务器假人name会变为realname

### ISSUE THREAD

**Issue by Zhongzi8972** [LeavesMC/Leaves#298]
### 服务端版本 LeavesMC Version

1.20.6-2233-0d6766e (MC: 1.20.6)

### 预期的行为 Expected behavior

使用
`createBot(@NotNull String name, @NotNull String realName, @Nullable String[] skin, @Nullable String skinName, @NotNull Location location);`
创建name与realname不同的假人后重启服务器，恢复数据的假人应保持原来的name和realname

### 观测到的实际行为 Observed/Actual behavior

重启后假人的name和realname全部变为原来的realname，原name不再生效

### 复现步骤 Steps/models to reproduce

1.调整配置文件resident-fakeplayer为true
2.使用以下api生成任意name与realname不同的假人后stop再重新开服
`createBot(@NotNull String name, @NotNull String realName, @Nullable String[] skin, @Nullable String skinName, @NotNull Location location);`
3.可以观察到假人上线后名字变为原realname，之前设置的name丢失

### 插件与数据包列表。 Plugin and Datapack List.

无

**Comment by s-yh-china** [comment]
感谢汇报~

**Comment by Zhongzi8972** [comment]
> 感谢汇报~

辛苦了(｡･ω･｡)ﾉ♡
