### ISSUE TITLE
是否可以加个选项能移除袭击冷却

### ISSUE THREAD

**Issue by Chaostarts** [LeavesMC/Leaves#299]
### 描述你希望添加的功能。 Describe the feature you'd like.

新版更新的袭击机制有点恶心 使得印钞机效率大大降低
是否可以添加一个选项把袭击改回旧版的袭击 像这个模组https://crystal0404.github.io/cca-doc/docs/Rule
![image](https://github.com/user-attachments/assets/a975887f-4c28-49e1-a6d6-fb9993abff85)

**Comment by GLDYM** [comment]
数据包就可以了。

https://modrinth.com/datapack/revertraidchanges-normal

https://modrinth.com/datapack/revertraidchanges-extra-badomen

**Comment by Chaostarts** [comment]
> 数据包就可以了。
> 
> https://modrinth.com/datapack/revertraidchanges-normal
> 
> https://modrinth.com/datapack/revertraidchanges-extra-badomen

很好的解决了我的问题，但是我觉得leaves作为一个为生电而生的服务端 可能有必要加入这个功能

**Comment by s-yh-china** [comment]
可以 但是不会很快
