### ISSUE TITLE
Added a config item for spawning wither roses when the player dies 为玩家死后有概率生成凋零玫瑰添加配置项

### ISSUE THREAD

**Issue by Fortern** [LeavesMC/Leaves#3]
### 描述你希望添加的功能。 Describe the feature you'd like.

Added a config item for spawning wither roses when the player dies.
为玩家死后有概率生成凋零玫瑰添加配置项。

**Comment by s-yh-china** [comment]
这不是一个服务端功能 请检查你的插件列表并联系插件作者
This is not a server-side feature. Please check your plugin list and contact the plugin author

**Comment by Fortern** [comment]
原来这是一个插件？？？
