### ISSUE TITLE
EssentialsX的home和warp传送到地狱或末地的时候会传送到主世界相应坐标处

### ISSUE THREAD

**Issue by z2bguoguo** [LeavesMC/Leaves#300]
### 服务端版本 LeavesMC Version

1.21-37-ec274f5

### 预期的行为 Expected behavior

EssentialsX使用home和warp传送到地狱或末地的时候会传送到地狱和末地的相应坐标处

### 观测到的实际行为 Observed/Actual behavior

EssentialsX的home和warp传送到地狱或末地的时候会传送到主世界相应坐标处

### 复现步骤 Steps/models to reproduce

EssentialsX 创建home然后传送到home

### 插件与数据包列表。 Plugin and Datapack List.

CoreProtect, DriveBackupV2, Essentials, ImageFrame, LuckPerms, Sleep, voicechat
[vanilla (built-in)], [file/bukkit (world)], [file/2032-world-height.zip (world)], [paper (built-in)]

**Comment by s-yh-china** [comment]
这和服务端有什么关系呢

**Comment by z2bguoguo** [comment]
> 这和服务端有什么关系呢 访问ess报问题

这个问题是在使用了Leaves做服务端后出现的

**Comment by GLDYM** [comment]
Waiting for test.
