### ISSUE TITLE
check-frozen-ticks-before-landing-block

### ISSUE THREAD

**Issue by 223225zzzkkk** [LeavesMC/Leaves#302]
“是否在尝试生成冰的时候优先检查游戏刻而不是先检查方块是否为空气。”
能解释一下这个配置项会改变什么吗？

**Comment by s-yh-china** [comment]
开启后，给与实体冻结状态减速时，会优先检查实体是否处于冰冻状态，而非检查实体脚下的方块是否为空气
这个issue应该被提交到文档站
