### ISSUE TITLE
是否可以添加 禁止fill,set和全局关闭block update的命令

### ISSUE THREAD

**Issue by Monoryxiaole** [LeavesMC/Leaves#303]
### 描述你希望添加的功能。 Describe the feature you'd like.

通过指令分别关闭fill set产生的方块更新
通过指令可关闭全局方块更新

### 其他 Other

关闭更新可以方便的粘贴投影的红石机器，以防止机器损坏

**Comment by Bluemangoo** [comment]
请到 [Document](https://github.com/LeavesMC/Documentation) 仓库提 issue。thanks.

**Comment by Monoryxiaole** [comment]
> 请到 [Document](https://github.com/LeavesMC/Documentation) 仓库提 issue。thanks.

提交了 tk
