### ISSUE TITLE
更新1.21.1

### ISSUE THREAD

**Issue by ning-g-mo** [LeavesMC/Leaves#304]
### 描述你希望添加的功能。 Describe the feature you'd like.

更新1.21.1
![Screenshot_2024-08-10-22-54-12-720_com microsoft emmx](https://github.com/user-attachments/assets/37e9def3-e024-409d-a496-020a6e1ed94e)

**Comment by serverbread-DEV** [comment]
1.21.1并没有什么实质上的更改 ~~（连协议版本都没变）~~，没必要那么急。

**Comment by FR-N** [comment]
没有必要，这个版本连via都不用就可以兼容

**Comment by Bluemangoo** [comment]
根本就没改什么东西，加了两个语言，修了声音抑制器。别着急，反正也没什么用。

**Comment by ning-g-mo** [comment]
《修复了可用于使服务器崩溃的关键漏洞》

**Comment by GLDYM** [comment]
> 《修复了可用于使服务器崩溃的关键漏洞》

这个关键漏洞指的就是更新抑制器；另一个漏洞没有公开，理论上使用白名单就能防住。

**Comment by s-yh-china** [comment]
别急

**Comment by s-yh-china** [comment]
别急

**Comment by LittleChest** [comment]
> > 《修复了可用于使服务器崩溃的关键漏洞》
> 
> 这个关键漏洞指的就是更新抑制器；另一个漏洞没有公开，理论上使用白名单就能防住。

另一个漏洞已经被 Liquid Bounce 公开了 不过无需担心 Paper（我们的上游）早就修复了
