### ISSUE TITLE
关于刷沙机问题

### ISSUE THREAD

**Issue by XiaoHua013** [LeavesMC/Leaves#305]
### 描述你希望添加的功能。 Describe the feature you'd like.

1.我看前辈提的issue说是可以制作刷沙机，但是经过服务器玩家实验发现沙子掉进传送门进去后都没沙子，好像实体进不去一样
2.我想问问官方有没有推荐的刷沙机，我们制作的都失败了

**Comment by XiaoHua013** [comment]
mc版本1.20.4

**Comment by LittleChest** [comment]
> mc版本1.20.4

我们不接受来自旧版本的问题报告 你可以前往 Discord 频道获取有效支持

**Comment by Bluemangoo** [comment]
你可以关注我们即将推出的lts计划，详见discussion。

**Comment by s-yh-china** [comment]
经测试，并不存在此问题，我晕晕了
