### ISSUE TITLE
能否将坚守者加入刷怪上限

### ISSUE THREAD

**Issue by Chaostarts** [LeavesMC/Leaves#306]
### 描述你希望添加的功能。 Describe the feature you'd like.

我们服务器有玩家想使用坚守者搞伪和平
能否将坚守者加入刷怪上限
paper端修复了这一特性

**Comment by s-yh-china** [comment]
我没听懂你在说什么.jpg

**Comment by MC-XiaoHei** [comment]
> 我没听懂你在说什么.jpg

监守者伪和平

**Comment by s-yh-china** [comment]
> > 我没听懂你在说什么.jpg
> 
> 监守者伪和平

也没坏啊

**Comment by Bluemangoo** [comment]
Duplicated of #265

**Comment by Bluemangoo** [comment]
开issue不看旧issue，我要闹了。
