### ISSUE TITLE
方块放置更新问题

### ISSUE THREAD

**Issue by mcjunshi** [LeavesMC/Leaves#31]
### 服务端版本 LeavesMC Version

git-Leaves-"98129c8" (MC: 1.19.2)

### 预期的行为 Expected behavior

放置床时产生更新，附近有红石信号时放置漏斗不产生更新

### 观测到的实际行为 Observed/Actual behavior

床尾放置未产生更新，附近有红石信号时放置漏斗仍产生更新
![2023-05-06_12 44 28](https://user-images.githubusercontent.com/132731965/236600332-9e8c6cef-b162-4f12-94af-8af99e068fc5.png)
![2023-05-06_12 46 38](https://user-images.githubusercontent.com/132731965/236600389-933a9eb1-cac1-464a-a59f-08aa2d7495b2.png)

### 复现步骤 Steps/models to reproduce

-

### 插件与数据包列表。 Plugin and Datapack List.

-

**Comment by GLDYM** [comment]
请尝试更新至最新版本，床的bug在新版本中无法复现，上锁漏斗待证实。

**Comment by s-yh-china** [comment]
需要在上游服务端(paper)上测试

**Comment by s-yh-china** [comment]
to PaperMC/Paper#9205

**Comment by s-yh-china** [comment]
> Waiting for test.

不用试了 没修好

**Comment by s-yh-china** [comment]
经过测试 这个问题是从craftbukkit就存在的
why?

**Comment by WhitePhosphor** [comment]
似乎paper团队把这个认为是原版的bug而不是特性所以顺手给修了......?

**Comment by s-yh-china** [comment]
> 似乎paper团队把这个认为是原版的bug而不是特性所以顺手给修了......?

这个问题和bukkit的方块更新机制有关系 倒也不是paper的锅

**Comment by s-yh-china** [comment]
此问题和craftbukkit的流体系统有关

**Comment by MC-XiaoHei** [comment]
bug有修复方案了，等Fortern
