### ISSUE TITLE
地毯机在开启时自我充能 （生电机器）

### ISSUE THREAD

**Issue by 1317347816** [LeavesMC/Leaves#311]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21-42-master@248cb93 (2024-08-06T09:40:44Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

正常运行，地毯机在开启时不会自我充能，具体请看视频（ https://caiyun.139.com/m/i?1R5BUbwkKFwWO  提取码:1TvX）

### 观测到的实际行为 Observed/Actual behavior

在使用侦测器活塞高频结构复制地毯时活塞处于一直激活状态（视频已经上传至网盘 https://caiyun.139.com/m/i?1R5BUbwkKFwWO  提取码:1TvX）

### 复现步骤 Steps/models to reproduce

已经上传网盘https://caiyun.139.com/m/i?1R5BUbwkKFwWO  提取码:1TvX

### 插件与数据包列表。 Plugin and Datapack List.

插件如下AdvancedBan, AngelChest, BedrockPlayerSupport, BetterRTP, CMI, CMIEInjector, CMILib, CoreProtect, FastAsyncWorldEdit, floodgate,Geyser-Spigot, JoinCommands, LootConomy, LuckPerms, Matrix, MiniMOTD, MultiLogin, Multiverse-Core, NBTAPI, NexEngine,nightcore, PlaceholderAPI, PlayerPoints, PlayerTitle, PlotSquared, ProtocolLib, Residence, TAB, Vault, ViaBackwards,ViaRewind, ViaVersion, VoidGen, WorldGuard

无任何数据包

### 更多详细信息。 The more information.

链接: https://caiyun.139.com/m/i?1R5BUbwkKFwWO  提取码:1TvX  复制内容打开中国移动云盘手机APP，操作更方便哦

**Comment by Grayer0113** [comment]
首先请尝试更新服务器版本。

**Comment by LittleChest** [comment]
将文件拖动至文本编辑窗口可直接上传文件 请停止使用各种奇怪的网盘

**Comment by 1317347816** [comment]
已经解决，受群内管理员启发，用无任何插件的同版本的leaves核心开服运行正常，排查是因为FastAsyncWorldEdit插件
