### ISSUE TITLE
末地黑曜石平台上的方块被传送破坏时不掉落

### ISSUE THREAD

**Issue by 2bno-1** [LeavesMC/Leaves#313]
### 服务端版本 LeavesMC Version

1.21-35-a8897bd (MC: 1.21)

### 预期的行为 Expected behavior

依照1.21新特性，实体穿过末地传送门时，黑曜石平台上方块应该按照被破坏并掉落（如原木掉落自身，末影箱掉落8块黑曜石，潜影盒完整掉落等）
[末地平台 - 中文 Minecraft Wik](https://zh.minecraft.wiki/w/%E6%9C%AB%E5%9C%B0%E5%B9%B3%E5%8F%B0#%E6%9C%AB%E5%9C%B0%E4%BC%A0%E9%80%81%E9%97%A8%E7%94%9F%E6%88%90)

### 观测到的实际行为 Observed/Actual behavior

如1.21以前一样，实体穿过末地传送门时，平台上方块被破坏且不掉落

### 复现步骤 Steps/models to reproduce

在黑曜石平台上放置各种方块，回到主世界，穿过传送门，发现平台上无任何掉落物
***
![初始状态](https://github.com/user-attachments/assets/97991b12-b370-48ce-93ec-0b7ca84fdf4b "初始状态")
***
![穿过传送门后](https://github.com/user-attachments/assets/d487bcd5-db19-4c9a-b66e-bd5e9cf0073e "穿过传送门后")

### 插件与数据包列表。 Plugin and Datapack List.

无插件，无数据包

**Comment by serverbread-DEV** [comment]
我成功地在build 51中复现了这一结果，需要去测试上游

**Comment by serverbread-DEV** [comment]
> 我成功地在build 51中复现了这一结果，需要去测试上游。

我在Paper build 13中也成功复现了这一结果。

这貌似不是Leaves的问题，应该将此bug报告给Paper

**Comment by s-yh-china** [comment]
确定为是早期PortalCreateEvent设计缺陷和mojang一时兴起改这部分内容导致的
破坏性修复会导致事件部分功能失效，解决方案确定为leaves暂时提供破坏性修复和开关
link PaperMC/Paper#11142

**Comment by s-yh-china** [comment]
提供了 `fix.spigot-EndPlatform-destroy` 来临时的破坏性修复了这个问题
如果需要，请开启此功能
