### ISSUE TITLE
为假人操控指令做些优化

### ISSUE THREAD

**Issue by sunshinezxq** [LeavesMC/Leaves#315]
### 描述你希望添加的功能。 Describe the feature you'd like.

将假人的use , use_to ,use_on修改成use 与 mount(就是换成carpet的)
或者是为use增加喝药的动作参数（我的天哪，到底怎么喝药啊)

**Comment by s-yh-china** [comment]
.......

**Comment by serverbread-DEV** [comment]
我认为这个更改没有必要

**Comment by WhitePhosphor** [comment]
。？How
