### ISSUE TITLE
1.20.6最新构建潜影盒堆叠不能使用

### ISSUE THREAD

**Issue by KaridaLee** [LeavesMC/Leaves#320]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.20.6-215-master@e234432 (2024-06-13T15:18:47Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

在服务器可以使用堆叠潜影盒，并可以放置、存放和成为掉落物

### 观测到的实际行为 Observed/Actual behavior

客户端安装tweakeroo-fabric-1.20.6-0.20.0并开启潜影盒合并相关选项，在背包取出一组潜影盒立刻被服务器清除，虽然可以在背包里看到他们，但是他们不能被放置、存放和丢出

### 复现步骤 Steps/models to reproduce

仅修改默认文件的stackable-shulker-boxes值为64，创造模式取出一组潜影盒，他们不能被放置和存放

### 插件与数据包列表。 Plugin and Datapack List.

无插件、[vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### 更多详细信息。 The more information.

已经在往日的issues中寻找1.20.6的相同问题，并没有提交过的issues

**Comment by GLDYM** [comment]
不受支持的版本。1.21修了。

**Comment by KaridaLee** [comment]
> 不受支持的版本。1.21修了。

好的，不好意思打扰了
