### ISSUE TITLE
能否将目前的服务器只分发单个资源包的方式修改为可以分发多个资源包

### ISSUE THREAD

**Issue by Virgil692** [LeavesMC/Leaves#327]
### 描述你希望添加的功能。 Describe the feature you'd like.

一个个人的对于服务器资源包分发方式的灵感：

目前服务器只能分发一个资源包，这对于需要分发多个资源包才能正常游戏的服务器来说极其难崩，我就是想能不能让服务器同时记录多个资源包的下载地址，在客户端加入服务器时就可以直接批量下载这些资源包

实际意义：如果这个问题解决了的话，这对于服务器直接加载玩法数据包将会是一个里程碑进程🤔

希望V姐能考虑一下，我会提供赞助支持🙏

**Comment by GLDYM** [comment]
？？？合并材质包啊

https://weld.smithed.dev/

**Comment by s-yh-china** [comment]
客户端本身就不支持吧 服务端怎么支持呢

**Comment by alazeprt** [comment]
将多个资源包合并后分发（确信

**Comment by Virgil692** [comment]
> ？？？合并材质包啊
> 
> https://weld.smithed.dev/

合并资源包已经让我体验到极度痛苦了（确信

现在我五个资源包合并就已经导致了一部分资源包纹理出问题了

**Comment by Virgil692** [comment]
> 将多个资源包合并后分发（确信

难度极大（确信💦

**Comment by MC-XiaoHei** [comment]
> > ？？？合并材质包啊
> > https://weld.smithed.dev/
> 
> 合并资源包已经让我体验到极度痛苦了（确信
> 
> 现在我五个资源包合并就已经导致了一部分资源包纹理出问题了

那服务端怎么处理呢。。
手工都费劲的话 自动怎么可能会完美,irrc

**Comment by GLDYM** [comment]
> > ？？？合并材质包啊
> > https://weld.smithed.dev/
> 
> 合并资源包已经让我体验到极度痛苦了（确信
> 
> 现在我五个资源包合并就已经导致了一部分资源包纹理出问题了

用我发的这个网站合并，它会自动合 json 。当然如果遇到覆盖的情况还是需要手动处理的。
