### ISSUE TITLE
假人在玩家上线后自动被顶掉对玩家执行ess插件命令出现报错

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#33]
### 服务端版本 LeavesMC Version

git-Leaves-"74e4680" (MC: 1.19.4)

### 预期的行为 Expected behavior

使用/bot创建的假人在真实玩家上线后被顶掉
用essentialsx的tp指令传送到该玩家能完成

### 观测到的实际行为 Observed/Actual behavior

使用/bot创建的假人在真实玩家上线后被顶掉:
> /bot create hehexi hehexi
hehexi joined the game
hehexi 死了.
...
hehexi leaved the game
hehexi joined the game

用essentialsx的tp指令传送到该玩家时在聊天栏出现报错:
> /tp hehe
正在传送到hehexi
错误:Cannot invoke "org.bukkit.entity.Player.getLocation()" because the return value of "org.bukkit.Server.getPlayerExact(String)" is null

### 复现步骤 Steps/models to reproduce

1.在服务器内召唤一个与玩家名字相同的假人：/bot create hehexi hehexi
2.同名玩家（hehexi）上线顶掉这个假人
3.执行ess插件的tp指令尝试传送到该玩家 （发生上述报错）：/essentials:tp hehexi
（此处使用平板操作，故无法拖放图片，望谅解）

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (27):
Bukkit Plugins:
*AdvancedReplay, AntiCheatReplay, Chunky, CoreProtect, DeluxeMenus, Essentials, floodgate, Floodgate-Skript, Geyser-Spigot, GeyserHacks, GeyserSkinManager, GeyserUpdater, LuckPerms, PlaceholderAPI, PlugManX, ProtocolLib, Skript, *skript-placeholders, skript-reflect, spark, Themis, TrChat, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### 更多详细信息。 The more information.

执行命令时仅聊天栏报错，后台无报错

**Comment by s-yh-china** [comment]
fix
