### ISSUE TITLE
假人饮用药水

### ISSUE THREAD

**Issue by ricecakey06** [LeavesMC/Leaves#332]
### 描述你希望添加的功能。 Describe the feature you'd like.

如题，希望能加入新的action来允许假人像carpet一样自动喝药
现有的三个use动作均不能让假人自动饮用药水

**Comment by SunshineZX1949** [comment]
之前提过了，具体看https://github.com/LeavesMC/Leaves/pull/325
317issue提的也是喝药水，但号主销号了

**Comment by SunshineZX1949** [comment]
把issue关了吧

**Comment by s-yh-china** [comment]
别急 等我重写()

**Comment by Bluemangoo** [comment]
姐姐你自己开个重写的tracking issue吧。

**Comment by SunshineZX1949** [comment]
怎么没看到僵尸病毒（
