### ISSUE TITLE
保存假人

### ISSUE THREAD

**Issue by yinengbei** [LeavesMC/Leaves#338]
### 描述你希望添加的功能。 Describe the feature you'd like.

可以让保存的假人不退出游戏吗？
![image](https://github.com/user-attachments/assets/bab1f53b-33b8-413b-b288-030f5d71ecc9)

**Comment by s-yh-china** [comment]
设计上就是这样的，并不会做此功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月14日(周六) 下午2:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 保存假人 (Issue #338)




 
描述你希望添加的功能。 Describe the feature you'd like.
 
可以让保存的假人不退出游戏吗？
 image.png (view on web)
 
其他 Other
 
No response

**Comment by MC-XiaoHei** [comment]
保存并不退出会导致可以刷东西
