### ISSUE TITLE
矿车在破基岩机器结构内被异常抛出

### ISSUE THREAD

**Issue by Monoryxiaole** [LeavesMC/Leaves#344]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-62-master@bff6bbd (2024-09-22T19:02:47Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.1-47-8be1ec2 (MC: 1.21.1)

### 预期的行为 Expected behavior

![1](https://github.com/user-attachments/assets/a26904c7-2085-45a2-9419-80462d952c8f)
![image](https://github.com/user-attachments/assets/3bd97386-f5e2-4e6b-9d33-d148491368a0)
推出后 矿车保持不动

### 观测到的实际行为 Observed/Actual behavior

![image](https://github.com/user-attachments/assets/38e5cc80-b115-4ca3-8cea-c2eec3764f7c)

### 复现步骤 Steps/models to reproduce

![image](https://github.com/user-attachments/assets/e2243764-8071-4780-94a2-f6a81388c9b5)
![image](https://github.com/user-attachments/assets/4d8de298-1dea-4718-b7e1-f89b35eefe77)
搭建如上结构 然后在铁轨上防止任意矿车 挤压矿车贴合栅栏门（栅栏门需要关闭）
![image](https://github.com/user-attachments/assets/964dcd7d-0afa-4194-9e6a-5ade035172d7)
替换为末地烛
![image](https://github.com/user-attachments/assets/0a702de4-b991-4f2d-ba1b-77965fe1def1)
收回活塞 再放置红石块使活塞伸出
![image](https://github.com/user-attachments/assets/30fe44e2-91a9-41d2-85fc-44e0a868f6ef)
拆除末地烛
![image](https://github.com/user-attachments/assets/832bb7a2-cf40-494f-9bfe-0f5b0fd3fd1a)
推入活塞 即可完成结构搭建
最后按上文实际观测的行为激活活塞即可复现

该结构原为
https://wwrl.lanzn.com/iSegg296hdfi
投影底部的破基岩结构

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/user-attachments/assets/494d2576-2617-44f3-931f-602ef8194482)

![image](https://github.com/user-attachments/assets/a1ba61f4-3432-4856-a084-e8bcdc36fd46)

**Comment by Bluemangoo** [comment]
issue很清晰，值得以后其它提issue的人学习。

**Comment by zhuiqiuat** [comment]
我也遇到了同样的问题

**Comment by TT-Candy** [comment]
已确定该问题是由于paper端对矿车的碰撞优化导致的，在paper的一众分支端和安装了moonrise的客户端中均可复现，我已经提交了一个issue到paper的仓库。https://github.com/PaperMC/Paper/issues/12066
在leaves端中该issue所示的情况已被修复，但另一种矿车近乎完全卡在方块内的情况（我所提交的issue中有展示视频）仍未能修复。

**Comment by s-yh-china** [comment]
另外一种情况是否会对机器造成普遍影响，如果存在，或paper长时间未反应/标记为不修复，可以另开issue或reopen。

**Comment by TT-Candy** [comment]
已确定将矿车完全卡在方块内的一类基岩机完全无法使用/炸膛，本issue提到的这种机器我未能找到相关资料因此无法测试。
paper那边我刚刚才提交，可能要等待一段时间才能有所回应。

**Comment by TT-Candy** [comment]
paper那边表示丢给moonrise，等moonrise修完再传回paper。我提交的issue被关闭了并标记为not planned。
其他维护者告诉我等他们修就行了，如果不放心可以在moonrise发一个issue。
有需要的话我可以在leaves发一个新的issue，很抱歉我目前没法帮助测试leaves端的情况，因为我没在玩这个端的服，也不知道怎么开服，我现在只能测试原版和luminol的情况。

**Comment by Fortern** [comment]
上游已修复
https://github.com/PaperMC/Paper/issues/9807
