### ISSUE TITLE
假人可以凭空放置方块

### ISSUE THREAD

**Issue by Monoryxiaole** [LeavesMC/Leaves#345]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-62-master@bff6bbd (2024-09-22T19:02:47Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.1-47-8be1ec2 (MC: 1.21.1)

### 预期的行为 Expected behavior

/bot action bot_a123 use_on 1
![image](https://github.com/user-attachments/assets/1ce5d472-f09c-4e9e-97c5-42d8350695e7)
应当不会放置方块

### 观测到的实际行为 Observed/Actual behavior

![image](https://github.com/user-attachments/assets/742c0266-4a26-4e2a-a287-da27875209b7)

### 复现步骤 Steps/models to reproduce

/bot create xxxx
bot 看向空气
/bot action bot_a123 use_on 1

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/user-attachments/assets/3351c1a2-f727-46c8-9f15-0a7ca2614f46)

**Comment by s-yh-china** [comment]
已修复，等待测试
