### ISSUE TITLE
支持slime world格式

### ISSUE THREAD

**Issue by 8MiYile** [LeavesMC/Leaves#346]
### 描述你希望添加的功能。 Describe the feature you'd like.

就是内置slime world的
自动javaagent slime world manager

### 其他 Other

https://github.com/InfernalSuite/AdvancedSlimePaper

**Comment by s-yh-china** [comment]
这个格式有什么显而易见的优点吗?

**Comment by MC-XiaoHei** [comment]
我简单了解了下这个格式。
它更适合hypixel这类小游戏服务器，并且文档尚不完善，我并不认为我们有必要实现这个格式。
如果你了解它有什么显著的，生电友好的特性，请告诉我

**Comment by 8MiYile** [comment]
是对于多维度空岛生电的办法，每个玩家在不同的主世界
空岛插件是superiorskyblock2

**Comment by s-yh-china** [comment]
暂无计划
