### ISSUE TITLE
/bot 无命令补全

### ISSUE THREAD

**Issue by yinengbei** [LeavesMC/Leaves#348]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-61-master@23c47a3 (2024-09-18T13:07:43Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are 3 version(s) behind Download the new version at: https://leavesmc.org/downloads/leaves Previous version: 1.21.1-54-39440b4 (MC: 1.21.1)

### 预期的行为 Expected behavior

无OP权限的玩家输入/bot命令时有命令补全

### 观测到的实际行为 Observed/Actual behavior

无OP权限的玩家输入/bot命令时无命令补全

### 复现步骤 Steps/models to reproduce

https://vip.123pan.cn/1825124405/8900076

### 插件与数据包列表。 Plugin and Datapack List.

![1](https://github.com/user-attachments/assets/5943d547-756d-430a-b9e3-d542220d0bf9)
![{93674FE9-8B04-4273-AD9F-6CB1607A13C9}](https://github.com/user-attachments/assets/524cb4df-a60f-44bf-a60e-5216e672e872)

**Comment by Bluemangoo** [comment]
用什么给的玩家执行权限。

**Comment by Bluemangoo** [comment]
我怀疑是command whitelist干的。

**Comment by Bluemangoo** [comment]
尝试下无插件（只保留luckyperms；不是disable）的情况下是否仍然存在这个问题

**Comment by Lumine1909** [comment]
可能是Paper的CommandUtil干的 晚点我看看吧

**Comment by s-yh-china** [comment]
理论已修复，待测试
