### ISSUE TITLE
去除paper的patch0977

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#35]
### 描述你希望添加的功能。 Describe the feature you'd like.

希望在leaves中去除paper commit 4f9575ee加入的patch
这个patch使得最新的更新抑制器无法使用

**Comment by serverbread** [comment]
patch是0977

**Comment by s-yh-china** [comment]
当然 但是你其实可以报一个bug

**Comment by s-yh-china** [comment]
done
