### ISSUE TITLE
/bot action <BotName> look <X> <Y> <Z> 会让后台疯狂打印错误日志

### ISSUE THREAD

**Issue by yinengbei** [LeavesMC/Leaves#353]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-66-master@95e6661 (2024-10-03T18:15:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

执行命令时后台无任何报错

### 观测到的实际行为 Observed/Actual behavior

执行命令时后台疯狂报错

### 复现步骤 Steps/models to reproduce

https://vip.123pan.cn/1825124405/8967540

### 插件与数据包列表。 Plugin and Datapack List.

![{F18675BD-56E0-4820-B162-7D05010E19A0}](https://github.com/user-attachments/assets/d8047435-51d5-490f-9d84-9364721f5669)

**Comment by MC-XiaoHei** [comment]
算是个bug，但你应该知道这玩意应该填写数字吧（）

**Comment by MC-XiaoHei** [comment]
确实，算一个能被攻击的漏洞了，下一个版本就修

**Comment by Lumine1909** [comment]
急速修复（
