### ISSUE TITLE
容器内堆叠的盒子不正确显示其数量

### ISSUE THREAD

**Issue by SunshineZX1949** [LeavesMC/Leaves#356]
### 服务端版本 LeavesMC Version

Leaves version 1.21.1-67-master@6c5cc79

### 预期的行为 Expected behavior

容器内堆叠的盒子会正确显示盒子数量（如8）

### 观测到的实际行为 Observed/Actual behavior

无数字显示，仅显示此处有盒子

### 复现步骤 Steps/models to reproduce

准备工作:
![image](https://github.com/user-attachments/assets/4f089435-afc8-4d10-9ea5-13f6ea4bd51e)
操作流程：
1
![image](https://github.com/user-attachments/assets/a40b08b6-8c24-41d9-a1c5-3e958152b13f)
2
![image](https://github.com/user-attachments/assets/7a947da8-b2c8-4691-bb3e-0196e4eab76b)
3.
![image](https://github.com/user-attachments/assets/5f778556-4f90-4c3c-9606-c353c3e8dabc)
4
![image](https://github.com/user-attachments/assets/072ce901-1c3a-4e9f-9ae9-7c8890e5cd82)

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (0):
[vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[13:10:19 信息]: There are no more data packs available

**Comment by s-yh-china** [comment]
暂无解决方案，只能通过安装客户端mod解决问题，因为这里显示是客户端控制的

**Comment by Lumine1909** [comment]
不如发给客户端一个假的改max stack amount的包（
似乎可以插件实现（

**Comment by s-yh-china** [comment]
你说的有道理，看起来是一种解决方案

**Comment by SunshineZX1949** [comment]
什么鬼，之前能用现在不行了（（（（

**Comment by Lumine1909** [comment]
> 你说的有道理，看起来是一种解决方案

什么时候翻新一下bytebuf api ()
现在没有 writeItemList 只能用nms手动写qwq

**Comment by SunshineZX1949** [comment]
唯一一个不仅是bug还积压了1个月的issue

**Comment by Lumine1909** [comment]
> 唯一一个不仅是bug还积压了1个月的issue

我知道你很急但你先别急
如果你真的很急可以自己pr修了 思路和代码都已经有了
https://github.com/Lumine1909/LeavesAddons/commit/b4ae47d4e5b8f1b54321430feecca38baeda7faa

**Comment by MC-XiaoHei** [comment]
修好了，而且一并修好了无mod容器内堆叠盒子的功能
