### ISSUE TITLE
/bot action 对假人无法控制动作

### ISSUE THREAD

**Issue by odyy345-u** [LeavesMC/Leaves#359]
### 服务端版本 LeavesMC Version

1.21.1-68-master@b33c46c

### 预期的行为 Expected behavior

使用/bot action 命令能正确控制假人动作

### 观测到的实际行为 Observed/Actual behavior

对假人使用/bot action botname use|use_offhand|use_on|stop 无效

### 复现步骤 Steps/models to reproduce

召唤一个假人，扔点方块
使用/bot action botname use 10（别的动作也行）
假人没有反应
![2024-10-13_16 40 58](https://github.com/user-attachments/assets/8ebe4bd0-7407-4c54-b3a8-5f60bb8ce085)

### 插件与数据包列表。 Plugin and Datapack List.

> datapack list
[Server] [16:42:05 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[Server] [16:42:05 INFO]: There are no more data packs available
> plugins
[Server] [16:42:09 INFO]: Server Plugins (0):
> version
[Server] [16:42:12 INFO]: This server is running Leaves version 1.21.1-68-master@b33c46c (2024-10-12T05:25:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[Server] You are running the latest version
[Server] Previous version: 1.21.1-64-2e311f0 (MC: 1.21.1)

**Comment by s-yh-china** [comment]
额，看看action开没开，然后你假人名字确定是对的吗

**Comment by odyy345-u** [comment]
名字确定是对的，hsds是早些时候截的图，另外想问问action在哪开？

**Comment by odyy345-u** [comment]
leaves.yml里的action开了，图是之前截的，假人名字确实对

**Comment by s-yh-china** [comment]
你这个操作应该是use_on，也可以是方向没摆好，奇怪，无法复现

**Comment by odyy345-u** [comment]
我重新验证一下看看

**Comment by odyy345-u** [comment]
![1728810734172](https://github.com/user-attachments/assets/fbf870f2-b6aa-48fd-b2c2-be00c2ffd2aa)
重新召唤假人操作了一遍，use类的都没法工作，action stop会报Invalid index

**Comment by MC-XiaoHei** [comment]
> action stop会报Invalid index
这是因为你需要action stop all(文档还没跟上)

**Comment by Lumine1909** [comment]
你可以提供一个最小的复现实例吗？我也无法复现

**Comment by s-yh-china** [comment]
无法复现，先关了
