### ISSUE TITLE
Leaves在1.21.1中漏斗的一些问题

### ISSUE THREAD

**Issue by KokomiServer** [LeavesMC/Leaves#360]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-67-master@6c5cc79 (2024-10-05T06:29:58Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

在漏斗前方为有效容器、下方为有效漏斗时，漏斗中的物品会被下方漏斗吸取。

### 观测到的实际行为 Observed/Actual behavior

在漏斗前方为有效容器、下方为有效漏斗时，漏斗会优先向它面前的容器传递物品。

### 复现步骤 Steps/models to reproduce

在漏斗前方为有效容器、下方为有效漏斗时，漏斗会优先向它面前的容器传递物品。而在原版中，此时该物品会被下方漏斗吸取。在此前，我们使用spigot端(1.20.4)时，其行为与原版保持一致；而将其更换Leaves核心1.21.1后出现上述问题。

### 插件与数据包列表。 Plugin and Datapack List.

>plugins
Bukkit Plugins:
[16:36:16 INFO]:  - AuthMe, BlockLocker, ColorfulMap, CoreProtect, *FlyWithFood, ImageFrame, PlugMan, SimpleTpa, SkinsRestorer, ViaBackwards
[16:36:16 INFO]:  ViaRewind, ViaVersion

> datapack list
[16:37:01 INFO]: 已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]

**Comment by KokomiServer** [comment]
啊忘了说了，leaves.yml中，vanilla-hopper选项不论是false还是true都不影响它出现问题。

**Comment by s-yh-china** [comment]
感觉是paper的锅，先测一下

**Comment by Fortern** [comment]
经测试，Leaves与Vanilla表现一致，并非bug。
![图片](https://github.com/user-attachments/assets/920afd9d-37fd-4f4c-bfc0-ff14ec8ed729)

对于这个结构：
1. 如果先放置A，后放置B，则会出现 @KujouMolean 观察到的现象——手动往A漏斗放一个物品，该物品传输到上面的箱子。
2. 如果先放置B，后放置A，则该物品传输到下面的箱子。
3. 如果往C漏斗放置物品，总会传输到下面的箱子。

**Comment by GLDYM** [comment]
罚你重修漏斗原理。

**Comment by KokomiServer** [comment]
是门禁的“分类”出现了问题，最开始还以为是端的问题？刚才把东西掏出来看了看，是标签(组件)数量不一致(???这不更莫名其妙了吗?)。玩家身上的物品表在更新后是8组件，容器中的却是7组件(新获取的也是7组件)。见图。
![image](https://github.com/user-attachments/assets/e3f99acc-402a-4a3c-8b3a-6f437f5e7b7f)
![image](https://github.com/user-attachments/assets/13642308-6e67-49fb-8861-7a47a49932a2)
