### ISSUE TITLE
假人创建了之后指向不对

### ISSUE THREAD

**Issue by cqw-acq** [LeavesMC/Leaves#362]
### 服务端版本 LeavesMC Version

git-Leaves-"847357b" (MC: 1.20.1)

### 预期的行为 Expected behavior

/bot create 的时候可以正常指向

### 观测到的实际行为 Observed/Actual behavior

/bot create 的时候始终指向一个方向

### 复现步骤 Steps/models to reproduce

/bot create

### 插件与数据包列表。 Plugin and Datapack List.

Bukkit Plugins:
AuthMe, AuthMeTitles, CoreProtect, Essentials, EssentialsChat, EssentialsXMPP, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LuckPerms，MiniMOTD, NBTAPI, PlaceholderAPI, ProtocolLib, Ranking, spark, TrChat, Vault, WayPointMaster
There are 2 data pack(s) enabled: 
[vanilla (built-in)], [file/bukkit (world)]

### 更多详细信息。 The more information.

[录屏2024-10-24 15.59.38-1.mov.zip](https://github.com/user-attachments/files/17503613/2024-10-24.15.59.38-1.mov.zip)
抱歉，视频有点大，达成了zip包

**Comment by MC-XiaoHei** [comment]
LeavesMC 不处理旧版本服务福端的问题，请使用最新版本的服务端
