### ISSUE TITLE
Jade协议导致无法进入服务器

### ISSUE THREAD

**Issue by huanli233** [LeavesMC/Leaves#368]
### 服务端版本 LeavesMC Version

Leaves version 1.21.1-75-master@423df96 (2024-10-28T17:17:31Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

玩家正常进入服务器

### 观测到的实际行为 Observed/Actual behavior

无法加入服务器：
```
Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'
```

### 复现步骤 Steps/models to reproduce

在`leaves.yml`中启用`jade-protocol`并启动服务端，使用安装了`Jade`的客户端进入服务器

### 插件与数据包列表。 Plugin and Datapack List.

<img width="736" alt="Snipaste_2024-11-02_21-28-20" src="https://github.com/user-attachments/assets/2ca09f6c-c350-4978-ac4b-9b3e7b263d3d">

### 更多详细信息。 The more information.

Jade 版本：`15.8.2+fabric`

**Comment by s-yh-china** [comment]
jade估计又改协议了，烦
