### ISSUE TITLE
假人在被盔甲架限制喝药的情况下仍然能喝药

### ISSUE THREAD

**Issue by SunshineZX1949** [LeavesMC/Leaves#369]
### 服务端版本 LeavesMC Version

75构建（手机难以运行服务端

### 预期的行为 Expected behavior

当假人对准盔甲架后喝药无法执行喝药这一动作

### 观测到的实际行为 Observed/Actual behavior

当假人对准盔甲架后喝药执行了喝药这一动作（就像是这个盔甲架并不存在一样）

### 复现步骤 Steps/models to reproduce

/bot creat hsds
让假人对准盔甲架
在假人副手或主手放上药品
/bot action hsds use
太坏了，假人还在喝药

### 插件与数据包列表。 Plugin and Datapack List.

什么都没

**Comment by MC-XiaoHei** [comment]
其实这个才是预期行为（）
leaves就是这么设计的
我不确定v姐怎么看
@s-yh-china

**Comment by SunshineZX1949** [comment]
我是个玩家，手机不好开服务端测试，故此无法得到版本号，但确实是75构建

**Comment by SunshineZX1949** [comment]
> 其实这个才是预期行为（） leaves就是这么设计的 我不确定v姐怎么看

难受的是在袭击塔中假人如果副手放药那么假人就会一直喝直到喝完
后面机器补充药的时候会因为假人副手药被喝完而无法补充
袭击断啦

**Comment by MC-XiaoHei** [comment]
这个问题确实有点，hmmmm
不过 carpet似乎也是这样吧（？）

**Comment by SunshineZX1949** [comment]
> 这个问题确实有点，嗯mm 不过 carpet 似乎也是这样吧（？）

是的了，carpet也这样，那我还是关了issue吧，顺便问一下，70构建好心人集成在leaves里的袭击恢复怎么启用呢？

**Comment by MC-XiaoHei** [comment]
> 70构建好心人集成在leaves里的袭击恢复怎么启用呢？

`modify.minecraft-old.allow-bad-omen-trigger-raid` and `modify.minecraft-old.give-bad-omen-when-kill-patrol-leader`

**Comment by s-yh-china** [comment]
你可以尝试使用use_to(

**Comment by MC-XiaoHei** [comment]
> 你可以尝试使用use_to(

他是要喝药水啊（）
