### ISSUE TITLE
假人保存功能（resident-fakeplayer）错误致服务器闪退

### ISSUE THREAD

**Issue by wwbtbgm** [LeavesMC/Leaves#375]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-79-master@21c276f (2024-11-15T15:39:36Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.1-75-423df96 (MC: 1.21.1)

### 预期的行为 Expected behavior

使用假人保存功能时服务器不闪退

### 观测到的实际行为 Observed/Actual behavior

使用假人保存功能时服务器闪退

### 复现步骤 Steps/models to reproduce

[crash-2024-11-16_01.37.23-server.txt](https://github.com/user-attachments/files/17779174/crash-2024-11-16_01.37.23-server.txt)
https://mclo.gs/bp2Ne2l

### 插件与数据包列表。 Plugin and Datapack List.

Plugins:
 Paper Plugins:BKCommonLib, ISeeYou
 Bukkit Plugins:BlueMap, Chunky, CMILib, CoreProtect, CreeperGuard, eBackup, floodgate, Geyser-Spigot, LuckPerms, Orebfuscator
 ProtocolLib, Residence, SkinsRestorer, TAB, Themis, ViaBackwards, ViaRewind, ViaVersion
datapack：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]

### 更多详细信息。 The more information.

一开始服务器是有假人且开启假人保存功能的，但是重启后闪退。关闭假人保存功能后正常开启。后面又测试打开假人功能且上一次启动后未加入假人时的情况，结果闪退，生成上文报错文件。问了gpt说是假人数据出现了问题，我想知道假人数据是否有专门的文件夹，如果没有，是不是在玩家数据文件夹里，如果在玩家数据文件夹里希望出一个方便假人管理的专门文件夹。感谢大佬过目。

**Comment by Lumine1909** [comment]
检查一下主世界文件夹中的fakeplayerdata 发一下里面的内容qwq

我怀疑是save而不是load导致的（

**Comment by wwbtbgm** [comment]
> 检查一下主世界文件夹中的fakeplayerdata 发一下里面的内容qwq
> 
> 我怀疑是save而不是load导致的（
[fakeplayerdata.zip](https://github.com/user-attachments/files/17780977/fakeplayerdata.zip)
啊这，翻的时候没仔细，现在才知道在这里，感谢大佬明示。
在删除这个假人文件夹后我就开启了假人保存功能并重启服务器，正常。但是我再添加假人后重启又会闪退。以下是本次崩溃报告
[crash-2024-11-16_04.32.26-server.txt](https://github.com/user-attachments/files/17781051/crash-2024-11-16_04.32.26-server.txt)
https://mclo.gs/Yq1Qq4R
感谢大佬解答：）

**Comment by Lumine1909** [comment]
> [fakeplayerdata.zip](https://github.com/user-attachments/files/17780977/fakeplayerdata.zip) 啊这，翻的时候没仔细，现在才知道在这里，感谢大佬明示。 在删除这个假人文件夹后我就开启了假人保存功能并重启服务器，正常。但是我再添加假人后重启又会闪退。以下是本次崩溃报告 [crash-2024-11-16_04.32.26-server.txt](https://github.com/user-attachments/files/17781051/crash-2024-11-16_04.32.26-server.txt) https://mclo.gs/Yq1Qq4R 感谢大佬解答：）

还有一个 fakeplayer.dat
麻烦上传一下 我刚翻代码才看到的（

**Comment by wwbtbgm** [comment]
[fakeplayer.zip](https://github.com/user-attachments/files/17781149/fakeplayer.zip)
感谢

**Comment by MC-XiaoHei** [comment]
@wwbtbgm 能否发一下保存的时候的log？也就是正常启动，召唤假人并关闭服务器的log

**Comment by wwbtbgm** [comment]
@MC-XiaoHei
https://mclo.gs/8QJgubf
[2024-11-16-17.zip](https://github.com/user-attachments/files/17783745/2024-11-16-17.zip)
感谢大佬

**Comment by MC-XiaoHei** [comment]
> @Lumine1909 @MC-XiaoHei 感谢大佬们修复
> 经我测试更新到81-ec5a806版本就可以正常使用假人保存功能了，以下是创建假人时和重启服务器后的日志
> [logs.zip](https://github.com/user-attachments/files/17783785/logs.zip)
> https://mclo.gs/DFjtwuO
> https://mclo.gs/8eN1pRs

虽然但是 其实不是我们俩修的（
是@s-yh-china 修的（

**Comment by hseermc** [comment]
好家伙，这不就是我反馈的那个么……我今天又弄出来一次刚准备reopen就看见这个了 :)
