### ISSUE TITLE
假人無法被粉雪殺死

### ISSUE THREAD

**Issue by jackary123** [LeavesMC/Leaves#376]
### 服务端版本 LeavesMC Version

This server is running Leaves version git-Leaves-"847357b" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 847357b)

### 预期的行为 Expected behavior

bot kill by powder snow

### 观测到的实际行为 Observed/Actual behavior

bot didn't kill by powder snow

### 复现步骤 Steps/models to reproduce

![image](https://github.com/user-attachments/assets/54460015-ba54-4821-8116-708366d73efd)

### 插件与数据包列表。 Plugin and Datapack List.

Plugins : 
AntiCreeper, AutoPluginLoader, DiscordSRV, FastAsyncWorldEdit, GSit, Images, LuckPerms, OpenInv, PlaceholderAPI, PlayerParticles
PlayerStats, PowerRanks, Ranking, ServerBackup, SkinsRestorer, TabTPS, UltimateInventory, ViaVersion

There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]

**Comment by MC-XiaoHei** [comment]
LeavesMC does not provide support for older versions, please upgrade to the latest version whenever possible

**Comment by MC-XiaoHei** [comment]
We only support the latest MC version
