### ISSUE TITLE
进入服务端被踢

### ISSUE THREAD

**Issue by FandMC** [LeavesMC/Leaves#377]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.3-DEV-dev/1.21.3@b6b3aaa (2024-11-26T17:53:57Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT) You are running a development version form CI Previous version: 1.21.1-81-ec5a806 (MC: 1.21.1)

### 预期的行为 Expected behavior

成功进入游戏

### 观测到的实际行为 Observed/Actual behavior

进入游戏秒被踢

### 复现步骤 Steps/models to reproduce

进入游戏即可
我已在[https://github.com/LeavesMC/Leaves/issues/314](314)下面写出了对应的协议，需要添加
ClientboundRecipeBookAdd,
ServerboundClientTickEnd,
ClientboundSetHeldSlot,
ServerboundBundleItemSelected
并且
Previous version: 1.21.1-81-ec5a806 (MC: 1.21.1)
应该为1.21.3
这里是修改后的org.leavesmc.leaves.bytebuf.packet.PacketType文件
[FandIMG](https://img.fandmc.cn/img/PacketType.java)

### 插件与数据包列表。 Plugin and Datapack List.

无

### 更多详细信息。 The more information.

我已在[314](https://github.com/LeavesMC/Leaves/issues/314)下面写出了对应的协议，需要添加
ClientboundRecipeBookAdd,
ServerboundClientTickEnd,
ClientboundSetHeldSlot,
ServerboundBundleItemSelected
并且
Previous version: 1.21.1-81-ec5a806 (MC: 1.21.1)
应该为1.21.3

**Comment by s-yh-china** [comment]
很感谢您提出的问题
但请，不要汇报DEV分支的问题，这根本就没有发布，以及您是看不懂Previous version是什么意思吗
