### ISSUE TITLE
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant org.leavesmc.leaves.bytebuf.packet.PacketType.ServerboundClientTickEnd

### ISSUE THREAD

**Issue by yeying-xingchen** [LeavesMC/Leaves#380]
### 服务端版本 LeavesMC Version

无法进入服务器，无法使用控制台

### 预期的行为 Expected behavior

正常进入服务器

### 观测到的实际行为 Observed/Actual behavior

报错Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.IllegalArgumentException: No enum constant org.leavesmc.leaves.bytebuf.packet.PacketType.ServerboundClientTickEnd

### 复现步骤 Steps/models to reproduce

进入服务器

### 插件与数据包列表。 Plugin and Datapack List.

无法进入服务器，无法使用控制台

**Comment by FandMC** [comment]
自行构建的1.21.3?1.21.3才更新了你这个枚举， 除了这个还需要其他4个才能正常游戏
https://github.com/LeavesMC/Leaves/issues/377

**Comment by Bluemangoo** [comment]
是哪里来的jar呢。

**Comment by GLDYM** [comment]
1.21.3版本目前还不能使用。

**Comment by yeying-xingchen** [comment]
> 1.21.3版本目前还不能使用。

大概需要多久？

**Comment by MC-XiaoHei** [comment]
> 大概需要多久？

NO ETA

**Comment by yeying-xingchen** [comment]
> > 大概需要多久？
> 
> NO ETA

我可以通过打钱加速这个进度吗？

**Comment by MC-XiaoHei** [comment]
我帮你问问吧。

**Comment by YuanYuanOwO** [comment]
偏个题
项目爱发电链接那里可以考虑更新

**Comment by Bluemangoo** [comment]
其实.4也快出来了，我们可能会跳过.3的。很着急吗。

**Comment by yeying-xingchen** [comment]
> 其实.4也快出来了，我们可能会跳过.3的。很着急吗。

是的，我服玩家现在要玩

**Comment by MC-XiaoHei** [comment]
> 是的，我服玩家现在要玩 他们要直播

考虑接一个代理端加via？

**Comment by yeying-xingchen** [comment]
> > 是的，我服玩家现在要玩 他们要直播
> 
> 考虑接一个代理端加via？

我有代理，已经更新1.21.3，无法回退，自己开发的插件在1.21.3且依赖收纳袋

**Comment by yeying-xingchen** [comment]
> 偏个题
> 项目爱发电链接那里可以考虑更新

抱歉，请给予链接

**Comment by MC-XiaoHei** [comment]
官网是有正确的链接的 https://afdian.com/a/s-yh-china

**Comment by Lumine1909** [comment]
> > > 是的，我服玩家现在要玩 他们要直播
> > 
> > 
> > 考虑接一个代理端加via？
> 
> 我有代理，已经更新1.21.3，无法回退，自己开发的插件在1.21.3且依赖收纳袋

你现在需要Leaves的什么功能呢？无法回退是什么原因呢？
旧版本可以开实验数据包来实现收纳袋（

**Comment by MC-XiaoHei** [comment]
如果真的没办法可以暂时切换到Paper，然后等这边升级再切回来
以及存档是可以在客户端那边回退的

**Comment by yeying-xingchen** [comment]
> > > > 是的，我服玩家现在要玩 他们要直播
> > > 
> > > 
> > > 考虑接一个代理端加via？
> > 
> > 我有代理，已经更新1.21.3，无法回退，自己开发的插件在1.21.3且依赖收纳袋
> 
> 你现在需要Leaves的什么功能呢？无法回退是什么原因呢？
> 旧版本可以开实验数据包来实现收纳袋（

支持全部种类的刷线机，TNT复制

**Comment by yeying-xingchen** [comment]
> 如果真的没办法可以暂时切换到Paper，然后等这边升级再切回来
> 以及存档是可以在客户端那边回退的

因为刷线机和TNT复制无法在paper使用，我必须使用leaves

**Comment by MC-XiaoHei** [comment]
> 支持全部种类的刷线机，TNT复制

paper的unsupported config里面是有这些的，可以打开看看

**Comment by yeying-xingchen** [comment]
> 
> > 支持全部种类的刷线机，TNT复制
> 
> paper的unsupported config里面是有这些的，可以打开看看

打开了，依然无法使用（选择leaves之前就试过）

**Comment by s-yh-china** [comment]
首先，你们又一次把issue当**即时聊天软件**用然后给我的邮箱发了20封邮件
因为人手不足，开发版本缓慢，主要体现在没有测试人员
目前Leaves已经有大量的功能了，我没有那么多时间去一个个测试功能是否正常，我也没有时间去追逐每个快照的代码更改
我有很多事要做，比如写论文打游戏睡觉，Leaves只是我的一个项目。
我会尽快完成目前的迁移使1.21.3可以进行测试，但我不会在这上面花费我所有的时间
