### ISSUE TITLE
[1.21.3]颜色没有正确显示

### ISSUE THREAD

**Issue by YuanYuanOwO** [LeavesMC/Leaves#383]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.3-82-master@1e8e9a9 (2024-12-02T05:12:16Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

颜色代码正常显示

### 观测到的实际行为 Observed/Actual behavior

![d0dd2605-9503-484e-9e78-ae7bdad2ab13](https://github.com/user-attachments/assets/8310350e-eea3-4c1c-b12d-c598738a1c4c)

### 复现步骤 Steps/models to reproduce

输入`/plugins`
或安装一个带有颜色代码的插件（？）
比如 QuickShop-Hikari HeadDatabase MyPet等等

### 插件与数据包列表。 Plugin and Datapack List.

```
[23:42:17 INFO]: Server Plugins (7):
[23:42:17 INFO]: Bukkit Plugins:
[23:42:17 INFO]:  - FastMinecart, HeadDatabase, PlaceholderAPI, ProtocolLib, QuickShop-Hikari, Vault, XConomy
```

### 更多详细信息。 The more information.

猜测可能是跟这个issue有关
https://github.com/Winds-Studio/Leaf/issues/175

**Comment by HaHaWTH** [comment]
PaperMC/Paper#11637

**Comment by s-yh-china** [comment]
通过临时升级ansi，我认为我们已经修复了这个问题

**Comment by YuanYuanOwO** [comment]
简单测试了一下，颜色已正常显示，辛苦各位开发者

**Comment by MC-XiaoHei** [comment]
paper好像也修了
