### ISSUE TITLE
Shadow Items?

### ISSUE THREAD

**Issue by alexei4884** [LeavesMC/Leaves#387]
### 描述你希望添加的功能。 Describe the feature you'd like.

[Item Shadowing](https://www.youtube.com/watch?v=bJgVL1DGFUU)

### 其他 Other

Hi, so, I honestly don't know if this is already in Leaves because I can't find any information in the documentation about [shadow items](https://www.youtube.com/watch?v=bJgVL1DGFUU). Is it even possible to do this?

**Comment by GLDYM** [comment]
No. This bug happens because two ItemStacks have the same id when crash-depression happens, but now the game will force change it, so it is not possible now.

**Comment by alexei4884** [comment]
thanks for the clarification <3
