### ISSUE TITLE
需要适配MC新版本1.20

### ISSUE THREAD

**Issue by CleMooling** [LeavesMC/Leaves#40]
### 描述你希望添加的功能。 Describe the feature you'd like.

如题，游戏更新了，请及时适配新版本

**Comment by GLDYM** [comment]
此外1.20-pre2Mojang出手修复了新的更新抑制器，如果有需求的话我建议暂缓更新

**Comment by s-yh-china** [comment]
> 此外1.20-pre2Mojang出手修复了新的更新抑制器，如果有需求的话我建议暂缓更新

会和1133一起作为新可配置功能加入
