### ISSUE TITLE
配置prefix时假人无法生成

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#41]
### 服务端版本 LeavesMC Version

git-Leaves-"1fbd584" (MC: 1.20) 

### 预期的行为 Expected behavior

输入/bot create hsds应该生成一个假人名为：-hsds

### 观测到的实际行为 Observed/Actual behavior

输入指令后没有任何反应，在启动服务器时所有之前生成的假人也不生成

### 复现步骤 Steps/models to reproduce

在leaves.yml里配置settings.modifyfakeplayer.prefix 为'-'时所有假人都无法生成

### 插件与数据包列表。 Plugin and Datapack List.

Bukkit Plugins:
AddonPatcher, *AdvancedReplay, BlockLocker, Chunky, CoreProtect, DeluxeMenus, Essentials, floodgate, FreedomChat, Geyser-Spigot
GeyserHacks, GeyserSkinManager, GeyserUpdater, LuckPerms, MiraiMC, PlaceholderAPI, PlugManX, ProtocolLib, skJson, Skript
*skript-placeholders, skript-reflect, skript-yaml, spark, Vault, ViaBackwards, ViaVersion, WorldEdit

已启用四个数据包：[vanilla（内置）], [bundle（功能）], [file/bukkit（世界）, [file/XKlazy.zip（世界）]

### 更多详细信息。 The more information.

settings.modifyfakeplayer.resident-fakeplayer: true
部分插件：Deluxemenus，FreedomChat，GeyserSkinManager，skript-yaml，WorldEdit显示为红色状态，无法加载

**Comment by GLDYM** [comment]
因为'-'并不是一个能用于玩家名的合法字符。合法字符只有大小写字母，数字，下划线。

**Comment by serverbread** [comment]
哦好的
close
