### ISSUE TITLE
部分插件失效

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#42]
### 服务端版本 LeavesMC Version

git-Leaves-"1fbd584" (MC: 1.20)

### 预期的行为 Expected behavior

所有插件都正常加载，功能正常，使用指令/pl为全绿状态

### 观测到的实际行为 Observed/Actual behavior

部分插件是红色状态，无法加载：Deluxemenus，FreedomChat，GeyserSkinManager，skript-yaml，WorldEdit，Trchat显示为红色状态，无法正常使用

### 复现步骤 Steps/models to reproduce

更新leaves到最新pre-release版本1fbd584

### 插件与数据包列表。 Plugin and Datapack List.

Bukkit Plugins:
AddonPatcher, *AdvancedReplay, BlockLocker, Chunky, CoreProtect, DeluxeMenus, Essentials, floodgate, FreedomChat, Geyser-Spigot
GeyserHacks, GeyserSkinManager, GeyserUpdater, LuckPerms, MiraiMC, PlaceholderAPI, PlugManX, ProtocolLib, skJson, Skript
*skript-placeholders, skript-reflect, skript-yaml, spark, Vault, ViaBackwards, ViaVersion, WorldEdit

已启用四个数据包：[vanilla（内置）], [bundle（功能）], [file/bukkit（世界）, [file/XKlazy.zip（世界）]

### 更多详细信息。 The more information.

目前插件列表已卸载Trchat

**Comment by GLDYM** [comment]
请先尝试将所有插件更新至最新版以支持1.20，此外这其中有些插件尚未支持1.20

**Comment by CleMooling** [comment]
问一下更新的1.20在哪里下载，Release找不到
