### ISSUE TITLE
玩家有时处于幽灵状态

### ISSUE THREAD

**Issue by xmk2333** [LeavesMC/Leaves#44]
### 服务端版本 LeavesMC Version

最新

### 预期的行为 Expected behavior

玩家正常进服，正常游玩

### 观测到的实际行为 Observed/Actual behavior

有时候有的玩家进服会显示聊天在客户端选项中被禁用，然后玩家处于幽灵状态，插件的tab不会补全该玩家，该玩家无法移动，该原版的tp可以显示该玩家但是传送后显示未找到实体，是玩着玩着突然这样，不知道是不是服务端的问题，问了其他的腐竹也会这样

### 复现步骤 Steps/models to reproduce

进服偶然会这样

### 插件与数据包列表。 Plugin and Datapack List.

![image](https://github.com/LeavesMC/Leaves/assets/61087334/949a65c8-5f0a-43e7-a0bd-9584cd11a6be)

### 更多详细信息。 The more information.

![image](https://github.com/LeavesMC/Leaves/assets/61087334/c2087933-9504-43bd-8cc1-b4b75bc126fe)

**Comment by xmk2333** [comment]
![image](https://github.com/LeavesMC/Leaves/assets/61087334/7d6da2f9-59cc-4643-a33c-018359ca6102)
![image](https://github.com/LeavesMC/Leaves/assets/61087334/5b3ffea7-708a-43cd-9ac0-1413a98b78b1)

**Comment by GLDYM** [comment]
请先于上游Paper中测试。

**Comment by xmk2333** [comment]
好的

**Comment by s-yh-china** [comment]
什么叫最新......
你需要写明你使用的版本

**Comment by xmk2333** [comment]
[Leaves-7d2b967](https://github.com/LeavesMC/Leaves/releases/tag/1.20-7d2b967) 1.20最新构建

**Comment by xmk2333** [comment]
因为玩家都在玩生电hhh

**Comment by xmk2333** [comment]
主要是这个概率特别小，测试估计需要一天甚至几天才能看到一个这样的

**Comment by GLDYM** [comment]
我怀疑是有插件不兼容，导致玩家实体没有正常生成。一般这个问题与涉及到玩家传送的插件有关，我建议你先尝试更新所有插件至最新版。

**Comment by xmk2333** [comment]
涉及到玩家传送的只有ess

**Comment by xmk2333** [comment]
spigot目前一切正常

**Comment by xmk2333** [comment]
好的
