### ISSUE TITLE
Add a option to disabled out-of-order kick

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#46]
### 描述你希望添加的功能。 Describe the feature you'd like.

由于Velocity对于聊天信息处理的问题，当通过Velocity连接到下游服务器、使用Litematica粘贴原理图时，会被下游服务器踢出，原因为“接收到了乱序的聊天数据”。
或许可以通过服务端上的修改，禁用这个踢出原因来解决这个问题。

### 其他 Other

Velocity的Issue（尚未解决）：[https://github.com/PaperMC/Velocity/issues/909](https://github.com/PaperMC/Velocity/issues/909)
用于解决该问题的Fabric Mod：[https://github.com/charassss/tin3o](https://github.com/charassss/tin3o)

**Comment by s-yh-china** [comment]
done
