### ISSUE TITLE
使minihub正确显示Server MSPT

### ISSUE THREAD

**Issue by Canary233** [LeavesMC/Leaves#47]
### 描述你希望添加的功能。 Describe the feature you'd like.

在未安装carpet的服务器中,minihub会估算mspt,通常为50左右.
在fabric+carpet中,其显示准确值.
能否添加一个protocol使其能获取leaves的实际mspt?

**Comment by s-yh-china** [comment]
实际上minihud从carpet获取的tps信息是从玩家菜单的页脚获取的，除非你在本地再多安装一个mod，否则很难实现单独的协议

**Comment by GLDYM** [comment]
可以使用[TAB](https://github.com/NEZNAMY/TAB)、[PlaceholderAPI](https://github.com/PlaceholderAPI/PlaceholderAPI)之类的插件来获取服务器的mspt。

**Comment by s-yh-china** [comment]
此功能会破坏部分插件功能 暂时搁置

**Comment by s-yh-china** [comment]
done with https://github.com/LeavesMC/Bladeren
