### ISSUE TITLE
关于假人的一些想法

### ISSUE THREAD

**Issue by ghost** [LeavesMC/Leaves#5]
1加入可直接查看/操作假人背包功能（如穿上装备拿取物品等）
2.假人自动补货功能（参考玩家使用Tweakeroo的自动补货效果）
3.为假人添加自动销毁配置项（可选/必须在创建假人时设置一个自动销毁时间，防止长时间挂了不必要的假人）
4.为假人可生成怪物添加配置项（减少服务器占用和避免占用服务器总刷怪上限影响机器效率）
5.假人可以使用经验修补附魔

**Comment by s-yh-china** [comment]
请规范格式并去除自说自话的内容
第六条不是服务端功能 不予考虑
