### ISSUE TITLE
加个修改世界高度上限？

### ISSUE THREAD

**Issue by WratithCr** [LeavesMC/Leaves#50]
### 描述你希望添加的功能。 Describe the feature you'd like.

听说世界高度理论上限扩展到2000+了，咱能不能也尝试突破一下319禁咒（=w=）

**Comment by s-yh-china** [comment]
但是这个不是数据包就能改吗

**Comment by WratithCr** [comment]
那个好像只能在创建世界的时候塞数据包（悲）

**Comment by CleMooling** [comment]
> 但是这个不是数据包就能改吗

不清楚对基岩版玩家的适配情况doge

**Comment by s-yh-china** [comment]
懒得做(

**Comment by WhitePhosphor** [comment]
屑屑屑

**Comment by s-yh-china** [comment]
因为这是一个可使用数据包解决的问题 我完全没必要花费精力在这上面

**Comment by WhitePhosphor** [comment]
有道理
虽然说方便懒狗但是工程量确实很大

**Comment by Lumine1909** [comment]
刨坟见谅qwq
打issue打错了看到的这个 如果你还需要这个功能的话 试试[这个](https://github.com/Lumine1909/CustomWorldHeight)
