### ISSUE TITLE
末地虚空不删除重力方块

### ISSUE THREAD

**Issue by WratithCr** [LeavesMC/Leaves#51]
### 服务端版本 LeavesMC Version

1.20.1

### 预期的行为 Expected behavior

重力方块落入虚空到一定高度自动变掉落物实体然后被删除

### 观测到的实际行为 Observed/Actual behavior

掉落物实体会在一定高度删除，下落中重力方块将一直下落并且占用实体计算导致卡服

### 复现步骤 Steps/models to reproduce

直接在末地主岛边缘放沙子然后灵魂出窍观察，在-200也能看到下落中的沙子（悲）

### 插件与数据包列表。 Plugin and Datapack List.

 Server Plugins (5):
Bukkit Plugins:
BeaconWaypoints, CoreProtect, Essentials, *GroupManager, SkinsRestorer

There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
 There are no more data packs available

**Comment by s-yh-china** [comment]
fix
