### ISSUE TITLE
教程中的选项在配置文件里找不到

### ISSUE THREAD

**Issue by DCE-114514** [LeavesMC/Leaves#52]
player can edit sign这个选项在leaves.yml中并没有找到

**Comment by GLDYM** [comment]
首先，这个Issue不符合规范；
其次，在1.20版本中，Mojang向原版中加入了玩家编辑告示牌的功能，因此这个配置不再被需要了。
Changelog: https://minecraft.fandom.com/zh/wiki/Java%E7%89%881.20#%E6%96%B9%E5%9D%97_2

**Comment by s-yh-china** [comment]
其实我想知道教程是什么 我不记得有过这种东西

**Comment by DCE-114514** [comment]
> 其实我想知道教程是什么 我不记得有过这种东西

我的表达不准确，准确来说是在wiki https://docs.leavesmc.top/zh/leaves/configuration

**Comment by s-yh-china** [comment]
但是这个配置在文档里也删了啊(

**Comment by DCE-114514** [comment]
> 但是这个配置在文档里也删了啊(

我一小时前看还在啊😰

**Comment by DCE-114514** [comment]
![Screenshot_2023-07-02-17-50-15-178_com.miui.gallery-edit.jpg](https://github.com/LeavesMC/Leaves/assets/132117183/d75d29dd-c5ce-47e8-a5b4-9999332e0bba)

**Comment by s-yh-china** [comment]
英文文档好久没更新了XD

**Comment by DCE-114514** [comment]
> 英文文档好久没更新了XD

那该看哪个

**Comment by s-yh-china** [comment]
文档更新频率很低 建议加群或者discord(

**Comment by DCE-114514** [comment]
> 文档更新频率很低 建议加群或者discord(

好的，谢谢
