### ISSUE TITLE
可以试着把leaves移植到1.17.1吗？

### ISSUE THREAD

**Issue by WhitePhosphor** [LeavesMC/Leaves#55]
### 描述你希望添加的功能。 Describe the feature you'd like.

如题，整个1.17.1版本的leaves

### 其他 Other

不严谨的来说还是有很多生电玩家执着于1.17.1版本的（bushi
所以是否有可能出个1.17.1版的leaves
如果可以的话替所有的1.17.1遗民感谢力

**Comment by WhitePhosphor** [comment]
如果有test了踢我一脚

**Comment by serverbread** [comment]
我想你可以自己构建（
应该是把paper换成1.17的就行

**Comment by WhitePhosphor** [comment]
晚上试试
但是低版本缺的API这一块谁给我补啊（bushi
我java很菜的

**Comment by acleverfreebird** [comment]
好了能发给我吗

**Comment by WhitePhosphor** [comment]
可以的
等下吃完饭我就去clone一下仓库

**Comment by s-yh-china** [comment]
事实上这会导致无数的冲突 不是很好办

**Comment by WhitePhosphor** [comment]
惊恐
是因为低版本没有高版本的代码特性还是因为要从根本上重写

**Comment by s-yh-china** [comment]
> 惊恐 是因为低版本没有高版本的代码特性还是因为要从根本上重写

都有 麻将每个版本都会改不少东西 paper也是

**Comment by WhitePhosphor** [comment]
![image](https://github.com/LeavesMC/Leaves/assets/92671117/1870263a-7db0-40d8-9ffa-a4d02111c13b)
喜报

**Comment by WhitePhosphor** [comment]
完全胜利
只能等什么好心人重写了

**Comment by LittleChest** [comment]
这几乎是不可能的 没人会去维护旧版 ~~除非小米6~~

**Comment by s-yh-china** [comment]
有人做了 等完成后合并

**Comment by WhitePhosphor** [comment]
叶门🙏
感谢开源

**Comment by WhitePhosphor** [comment]
是不是得close了（
都这么久了

**Comment by s-yh-china** [comment]
现在没人做了 关了好了(
