### ISSUE TITLE
为正/外混合登录加入UUID保护

### ISSUE THREAD

**Issue by LsrlYrsc** [LeavesMC/Leaves#56]
### 描述你希望添加的功能。 Describe the feature you'd like.

如题
我在启用外置登录之后，测试了同ID正版以及皮肤站的登录
结果是两个账号在登录同一个服务器的时候都可以登录，而且拥有相同的权限，这有点危险
所以，我希望Leaves可以内置一个UUID检测
机制：记录第一次玩家进入时的UUID，在第二次有相同玩家的ID但是不同UUID的情况下，不允许其进入服务器
这里有一个项目地址：[uuidcheck](https://github.com/PonderFox0643/uuidcheck) 
我希望如果继承后可以选择使用MySQL和SQLite这两种数据库存储格式
如果不接受此类Issue，请拜托能不能将其删除，而不是Close，谢谢（如果可以这么做的话）

**Comment by s-yh-china** [comment]
done
