### ISSUE TITLE
右键告示牌打开依附容器 

### ISSUE THREAD

**Issue by LittleChest** [LeavesMC/Leaves#57]
### 描述你希望添加的功能。 Describe the feature you'd like.

右键告示牌打开依附容器
虽然说1.20把直接右键改成了编辑告示牌 但可以交换功能：
潜行+右键=编辑
右键=打开容器
不然有点反直觉

### 其他 Other

可参考 https://github.com/IpacEL/container-passthrough

**Comment by s-yh-china** [comment]
done
