### ISSUE TITLE
想加个红石优化

### ISSUE THREAD

**Issue by Shizuri23** [LeavesMC/Leaves#58]
### 描述你希望添加的功能。 Describe the feature you'd like.

红石优化
https://github.com/SpaceWalkerRS/alternate-current

应该对部分原版红石机制有一点点影响，但很小

### 其他 Other

之前用的是Mirai服务端，里面就塞了这个玩意
https://github.com/Dreeam-qwq/Mirai

**Comment by WhitePhosphor** [comment]
虽然但是
paper配置文件里面已经有了
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年07月17日 12:44 |
| 收件人 | LeavesMC/Leaves ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LeavesMC/Leaves] 想加个红石优化 (Issue #58) |

描述你希望添加的功能。 Describe the feature you'd like.

红石优化
https://github.com/SpaceWalkerRS/alternate-current

应该对部分原版红石机制有一点点影响，但很小

其他 Other

之前用的是Mirai服务端，里面就塞了这个玩意
https://github.com/Dreeam-qwq/Mirai
