### ISSUE TITLE
开启飞行不加载区块模式后在设定高度之上无法使用烟花火箭

### ISSUE THREAD

**Issue by WhitePhosphor** [LeavesMC/Leaves#59]
### 服务端版本 LeavesMC Version

git-leaves-“dd71482”

### 预期的行为 Expected behavior

step1.在设置内调整elytra- aeronautics中的no-chunk-load为true，同时设置height为320（这是我的设置，实际测试中500也有相同情况）
step2.飞行至y>320
step3.应当可以正常使用烟花火箭飞行

### 观测到的实际行为 Observed/Actual behavior

step1.同上
step2.同上
step3.玩家无法使用烟花火箭加速飞行，并且在设定高度上下飞行时有可能卡在中间

### 复现步骤 Steps/models to reproduce

呃
发不了视频
群验证过一下我发qq群里

### 插件与数据包列表。 Plugin and Datapack List.

plugins
AnimatedScoreboard
Brewery
Coreprotect
Luckperms
Nexengine
PlaceholderAPI
PluginPortal
SkinRestorer
spark
TrChat
TrMenu
Via Backwards
Via Version
Worldedit

### 更多详细信息。 The more information.

有概率使玩家卡在设定高度上不去下不来

**Comment by s-yh-china** [comment]
没有收到你的加群请求
给下qq号我拉你吧

**Comment by WhitePhosphor** [comment]
3249935976
以及我会去更新最新版本试试

**Comment by WhitePhosphor** [comment]
欧了没事了
