### ISSUE TITLE
附魔相关开关

### ISSUE THREAD

**Issue by MC-XiaoHei** [LeavesMC/Leaves#67]
### 描述你希望添加的功能。 Describe the feature you'd like.

建议在配置中增加以下开关：
- [x] 取消“过于昂贵”，并可配置此时需要的等级数
- [ ] 允许冲突附魔（e.g. 无限与经验修补 ）
- [ ] 允许与装备不匹配的附魔（e.g. 帽子上的锋利）

**Comment by s-yh-china** [comment]
后两个功能完全可以使用插件实现
不制作
