### ISSUE TITLE
LeavesMC 官网

### ISSUE THREAD

**Issue by z0z0r4** [LeavesMC/Leaves#69]
可以试着给 https://github.com/PaperMC/website 换皮

关于介绍，README 里面几乎没有 desc，粗略编了一点

与其这些，可以有个 download 网页了

似乎是有 leavesmc.top 的，完全可以搭个官网

![image](https://github.com/LeavesMC/Leaves/assets/78744121/011fb863-0243-4939-b5fa-93cb9c112068)

**Comment by s-yh-china** [comment]
其实有个 https://docs.leavesmc.top

**Comment by z0z0r4** [comment]
搭吗？如果搭的话我来改一份，想有个 download 起码

可否在 org 开个 repo？

**Comment by s-yh-china** [comment]
> 

有 https://repo.leavesmc.top

**Comment by z0z0r4** [comment]
> > 
> 
> 有 https://repo.leavesmc.top

说的是 leavesmc/website

**Comment by s-yh-china** [comment]
> > > 
> > 
> > 
> > 有 https://repo.leavesmc.top
> 
> 说的是 leavesmc/website
> 
> 似乎可以挂到 https://leavesmc.top 上

en

**Comment by LittleChest** [comment]
> 可以试着给 https://github.com/PaperMC/website 换皮
> 
> 关于介绍，README 里面几乎没有 desc，粗略编了一点
> 
> 与其这些，可以有个 download 网页了
> 
> 似乎是有 leavesmc.top 的，完全可以搭个官网
> 
> ![image](https://user-images.githubusercontent.com/78744121/255569379-011fb863-0243-4939-b5fa-93cb9c112068.png)

https://github.com/LeavesMC/website/pull/2
我试着改了点 你可以先提交到我的分支（？）
目前PaperMC API不能很好的转到GitHub API 所以下载还是个问题

**Comment by z0z0r4** [comment]
> > 可以试着给 [PaperMC/website](https://github.com/PaperMC/website) 换皮
> > 关于介绍，README 里面几乎没有 desc，粗略编了一点
> > 与其这些，可以有个 download 网页了
> > 似乎是有 leavesmc.top 的，完全可以搭个官网
> > ![image](https://user-images.githubusercontent.com/78744121/255569379-011fb863-0243-4939-b5fa-93cb9c112068.png)
> 
> [LeavesMC/website#2](https://github.com/LeavesMC/website/pull/2) 我试着改了点 你可以先提交到我的分支（？） 目前PaperMC API不能很好的转到GitHub API 所以下载还是个问题

我对web不熟悉，只能套皮不会写

但如果缺 API 我可以建个后端

**Comment by LittleChest** [comment]
PaperMC API也是开源的 XD
~~万物基于[Vercel](https://vercel.com)~~

z0z0r4 ***@***.***> 于 2023年7月26日周三 09:47写道：

**Comment by LittleChest** [comment]
PaperMC API也是开源的 XD
~~万物基于[Vercel](https://vercel.com)~~

**Comment by z0z0r4** [comment]
> PaperMC API也是开源的 XD
> ~~万物基于[Vercel](https://vercel.com)~~

emmm，确实是开源的，但我看不懂 Java 所以没翻它咋运作的

那我撤

**Comment by s-yh-china** [comment]
但是vercel不能运行java项目XD

**Comment by z0z0r4** [comment]
恼，要后端吗，要我就建个去

从 GitHub 拿 release 反正...

**Comment by LittleChest** [comment]
> 恼，要后端吗，要我就建个去
> 
> 从 GitHub 拿 release 反正...

但是把一个API硬改到另一个API很麻烦 或许可以参考下Purpur的？

**Comment by LittleChest** [comment]
> > > 恼，要后端吗，要我就建个去
> > > 从 GitHub 拿 release 反正...
> > 
> > 
> > 但是把一个API硬改到另一个API很麻烦 或许可以参考下Purpur的？
> 
> 欸？复刻，前端又不改

准备用GitHub API 但是Leaves目前已经有多个项目了 最好还是搭个LeavesMC API

**Comment by z0z0r4** [comment]
多个项目？不是只有个服务端吗？

**Comment by LittleChest** [comment]
> 多个项目？不是只有个服务端吗？

https://github.com/LeavesMC/Leavesclip
https://github.com/LeavesMC/Bladeren

**Comment by LittleChest** [comment]
[LeavesMC/Website](https://github.com/LeavesMC/Website) 完成
