### ISSUE TITLE
Need

### ISSUE THREAD

**Issue by huangran12138** [LeavesMC/Leaves#7]
### 描述你希望添加的功能。 Describe the feature you'd like.

Can you create a fakeplayer plugin for paper

### 其他 Other

Can you create a fakeplayer plugin for paper

**Comment by s-yh-china** [comment]
it may be implement, but not now  
why not use leaves directly

**Comment by huangran12138** [comment]
Thank you. You are right , I am using it now!!!Looking forward to your work!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月25日 15:46
收件人: ***@***.***>
抄送: Welcome ***@***.***>; ***@***.***>
主题: Re: [LeavesMC/Leaves] Need (Issue #7)


it may be implement, but not now
why not use leaves directly

―
