### ISSUE TITLE
假人remove时会保留背包

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#76]
### 描述你希望添加的功能。 Describe the feature you'd like.

leaves现在remove假人的逻辑是kill掉假人，但是我希望能让假人在remove时不被kill，下次召唤时会带着原先的物品，这样方便用假人送快递

### 其他 Other

希望添加配置项控制是否允许召唤与服内玩家同名的假人时，假人有着与那名玩家相同的物品栏

**Comment by s-yh-china** [comment]
如果你想实现此功能 我更推荐你找人写个插件XD

**Comment by serverbread** [comment]
> 如果你想实现此功能 我更推荐你找人写个插件XD

我已经自行通过编写插件实现该功能，开发者可自行选择是否继续开发
