### ISSUE TITLE
请提供屏蔽服务器控制台日志颜色输出的功能或方法！

### ISSUE THREAD

**Issue by CleMooling** [LeavesMC/Leaves#83]
### 服务端版本 LeavesMC Version

all

### 预期的行为 Expected behavior

none

### 观测到的实际行为 Observed/Actual behavior

无法移除服务器日志输出的字体颜色

### 复现步骤 Steps/models to reproduce

如上

### 插件与数据包列表。 Plugin and Datapack List.

no need

### 更多详细信息。 The more information.

如标题，本人使用GitHub开源项目MCDReforged控制与管理服务器，以及增加运行在服务端外的插件功能。
在使用这个项目时，如果关闭高级控制台，则会出现某些无法解决的功能异常，因此本人选择启用MCSManager（一个面板管理程序，同样在GitHub开源）的仿真终端功能（即高级控制台）。
然而，在高级控制台状态下，服务端不可避免的会在某些日志响应输出上渲染字体颜色，而这会导致mcdr无法正常解析日志格式，进而导致部分插件报错。mcsm的字体颜色渲染和mcdr的日志颜色输出屏蔽功能均已开启，然而服务端仍然会在部分语句上渲染字体颜色，且本人无法解决，故提出此issue，希望得到开发者和其他用户们的帮助。
此处的字体颜色渲染影响mcdr的插件正常使用↓
执行的指令：data get entity <player_name> Pos
返回结果：<player_name> has the following entity data: [-131.77821d, 80.0d, 416.0972d]
渲染部分：[-131.77821d, 80.0d, 416.0972d]（玩家坐标处）
影响：mcdr的插件无法正常解析坐标数值。
/
/

**Comment by CleMooling** [comment]
事态紧急（相关功能缺失正在影响服务器正常玩法运营），希望能尽快得到解决

**Comment by s-yh-china** [comment]
首先确定你mcdr的模式是否正确
然后这应该是mcdr和mcsm的冲突问题 应该去找他们吧
我自己在使用的时候mcdr高级控制台并未出错

**Comment by XIAYM-gh** [comment]
如果你实在找不到屏蔽颜色的方法，你可以尝试在你的MCDR插件代码里手动剔除一遍ANSI Code
方法请自行必应 how to strip ansi in python

**Comment by LittleChest** [comment]
请参阅[MCSManager & MCDR使用文档](https://docs.mcsmanager.com/#/zh-cn/tutorial/mcdr)

**Comment by CleMooling** [comment]
> 

这个方法应该可行，但是我只是一个普通用户不是开发者，也缺少相应的技术能力。
还是感谢你的帮助，我会继续自行尝试，但是希望服务端本身能够支持去除这些颜色代码，这会方便很多

**Comment by GLDYM** [comment]
bbzl，槽点太多了不知道从何说起：
1. MCSM的上色是前端行为，所以和MCSM半毛钱关系都没有
2. MCDR自己的上色行为肯定不会影响到它自己插件的运作，所以这事和MCDR自己也没啥关系
3. 这也显然与Leaves没有什么关系，Leaves也没有义务去除这些颜色代码
你应该检查的是：
1. 是否有某个Bukkit插件上色，如EssentialsX或者CMI，导致MCDR的Handler不匹配
2. MCDR的Handler是否选择正确，应该是bukkit_handler
3. 该MCDR插件的代码是否正确，大部分MCDR插件只处理客户端的输入与控制台的输入，而不处理控制台的返回信息

**Comment by Bluemangoo** [comment]
你好。我是mcsm的contributer。mcsm的上色是前端行为而且历来是槽点之一。你在启用pty的情况下应该关闭前端上色，pty会传递控制台ansi颜色。

**Comment by CleMooling** [comment]
第四点，issue明显确认了产生问题的部分在原版指令上，和插件并无关系。
该指令在其他服务端上并不会在坐标处渲染字体颜色，或者渲染的颜色能够被自动去除。mcdr没有内置去除ANSI Code的功能，因此这里产生的颜色没有办法被屏蔽，导致解析失败



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月31日(周一) 中午12:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 请提供屏蔽服务器控制台日志颜色输出的功能或方法！ (Issue #83)




 
bbzl，槽点太多了不知道从何说起：
  
MCSM的上色是前端行为，所以和MCSM半毛钱关系都没有
 
MCDR自己的上色行为肯定不会影响到它自己插件的运作，所以这事和MCDR自己也没啥关系
 
这也显然与Leaves没有什么关系，Leaves也没有义务去除这些颜色代码
 你应该检查的是：
 
是否有某个Bukkit插件上色，如EssentialsX或者CMI，导致MCDR的Handler不匹配
 
MCDR的Handler是否选择正确，应该是bukkit_handler
 
该MCDR插件的代码是否正确，大部分MCDR插件只处理客户端的输入与控制台的输入，而不处理控制台的返回信息

**Comment by Bluemangoo** [comment]
你好，看看你的设置。

![image](https://github.com/LeavesMC/Leaves/assets/63218454/29b470ea-a6b0-4cc8-afea-341ec794e8c7)

**Comment by GLDYM** [comment]
> 

那么你应该检测Handler是否选择正确
或者这个MCDR插件的代码是否有问题
或者你使用插件的方式有问题
与上色没有任何关系

**Comment by LsrlYrsc** [comment]
请问，你在Leaves里面发布这样的issue有什么意义吗
虽然有人回答了你但我还是要说一声
是哪里的问题能不能去那里问问题？
不要说这是用Leaves导致的，因为其他服务端也可以这样输出
太抽象了

**Comment by LsrlYrsc** [comment]
这种东西插件应该可以提供的吧
我认为这完全没有必要在服务端里大费周章
~~或者把nogui去掉~~
~~用服务端提供的窗口来进行管理~~

**Comment by CleMooling** [comment]
服务器一般没有带图形化的吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月31日(周一) 中午12:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeavesMC/Leaves] 请提供屏蔽服务器控制台日志颜色输出的功能或方法！ (Issue #83)




 
这种东西插件应该可以提供的吧
 我认为这完全没有必要在服务端里大费周章
 或者把nogui去掉
 用服务端提供的窗口来进行管理

**Comment by LsrlYrsc** [comment]
> 服务器一般没有带图形化的吧
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年7月31日(周一) 中午12:55 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [LeavesMC/Leaves] 请提供屏蔽服务器控制台日志颜色输出的功能或方法！ (Issue #83) 这种东西插件应该可以提供的吧 我认为这完全没有必要在服务端里大费周章 或者把nogui去掉 用服务端提供的窗口来进行管理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

在官方服务器，Paper以及其分支，不使用nogui会有另一个窗口，~~那个窗口完全解决了颜色问题（bushi）~~

**Comment by Bluemangoo** [comment]
大哥你能不能打开github看看串，上面提供了解决办法。

**Comment by GLDYM** [comment]
![b128345edb07a7c7c6bf6c09ec1854d8](https://github.com/LeavesMC/Leaves/assets/49135577/0e18e678-2c9c-4ed7-a1d9-b39a2533f802)
