### ISSUE TITLE
 Linear region file format

### ISSUE THREAD

**Issue by s-yh-china** [LeavesMC/Leaves#89]
### 描述你希望添加的功能。 Describe the feature you'd like.

- [x] Linear region file format
- [ ] Auto convert linear to anvil
- [ ] Auto convert anvil to linear

### 其他 Other

https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools

**Comment by LittleChest** [comment]
求 服务器硬盘要塞不下啦
